import bpy
import sys
sys.path.insert(0, r"/home/egxn/Catcode/tanuki/src")


def setup_miura_tile_male(object_name='miura_tile_male'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeImportOBJ")
    prim_1.location = (0, 0)
    prim_1.label = 'import_obj'
    prim_1.inputs["Path"].default_value = '/home/egxn/Catcode/tanuki_apps/bellows_diecut/src/bellows_diecut/output/mesh/miura_tile_male.obj'
    geom_op_2 = node_tree.nodes.new("GeometryNodeRealizeInstances")
    geom_op_2.location = (300, 0)
    geom_op_2.label = 'import_obj realize'
    node_tree.links.new(prim_1.outputs["Instances"], geom_op_2.inputs["Geometry"])
    geom_op_3 = node_tree.nodes.new("GeometryNodeSetGeometryName")
    geom_op_3.location = (600, 0)
    geom_op_3.label = 'import_obj realize set_name'
    geom_op_3.inputs["Name"].default_value = 'miura_tile_male'
    node_tree.links.new(geom_op_2.outputs["Geometry"], geom_op_3.inputs["Geometry"])
    out_4 = node_tree.nodes.new("NodeGroupOutput")
    out_4.location = (900, 0)
    out_4.label = "output"
    node_tree.links.new(geom_op_3.outputs[0], out_4.inputs[0])

    return node_tree




def setup_miura_tile_female(object_name='miura_tile_female'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeImportOBJ")
    prim_1.location = (0, 0)
    prim_1.label = 'import_obj'
    prim_1.inputs["Path"].default_value = '/home/egxn/Catcode/tanuki_apps/bellows_diecut/src/bellows_diecut/output/mesh/miura_tile_female.obj'
    geom_op_2 = node_tree.nodes.new("GeometryNodeRealizeInstances")
    geom_op_2.location = (300, 0)
    geom_op_2.label = 'import_obj realize'
    node_tree.links.new(prim_1.outputs["Instances"], geom_op_2.inputs["Geometry"])
    geom_op_3 = node_tree.nodes.new("GeometryNodeSetGeometryName")
    geom_op_3.location = (600, 0)
    geom_op_3.label = 'import_obj realize set_name'
    geom_op_3.inputs["Name"].default_value = 'miura_tile_female'
    node_tree.links.new(geom_op_2.outputs["Geometry"], geom_op_3.inputs["Geometry"])
    out_4 = node_tree.nodes.new("NodeGroupOutput")
    out_4.location = (900, 0)
    out_4.label = "output"
    node_tree.links.new(geom_op_3.outputs[0], out_4.inputs[0])

    return node_tree





# Execute all parts
setup_miura_tile_male()
setup_miura_tile_female()

# --- Bake the Geometry Nodes solids to STL (written next to this script) ---
import os
from bellows_diecut.core.exporter import bake_and_export_stl
_stl_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "stl")
bake_and_export_stl('miura_tile_male', os.path.join(_stl_dir, 'miura_tile_male.stl'))
bake_and_export_stl('miura_tile_female', os.path.join(_stl_dir, 'miura_tile_female.stl'))
