"""Parametric Geometry Nodes rollers for the miura bellows pattern.

Run in Blender::  blender -b -P miura_roller_gn.py     (or open + Run Script)

Creates two objects — ``miura_roller_male`` and ``miura_roller_female`` — each
with a ``BellowsRoller`` Geometry Nodes modifier whose inputs stay editable:

    Diameter (mm) · Tiles around · Tiles along · Relief depth · Core wall (mm)

The female is the male's negative (Relief depth < 0) so the pair meshes like gears.
Auto-generated by bellows_diecut.core.roller_gn — do not edit by hand.
"""
import bpy, math

BLOCK_VERTS = [(-20.00000,0.00000,0.00000),(-20.00000,-5.66667,2.56667),(-4.00000,0.00000,-2.56667),(-4.00000,-5.66667,3.85000),(-12.00000,-11.33333,3.85000),(-12.00000,-17.00000,-2.56667),(-12.00000,-5.66667,-7.70000),(-20.00000,-11.33333,-7.70000),(-4.00000,-11.33333,-7.70000),(12.00000,0.00000,-1.54000),(12.00000,-5.66667,2.56667),(4.00000,-11.33333,3.85000),(4.00000,-17.00000,-2.56667),(4.00000,-5.66667,-7.70000),(12.00000,-11.33333,-7.70000),(-12.00000,17.00000,0.00000),(-12.00000,11.33333,2.56667),(4.00000,17.00000,-2.56667),(4.00000,11.33333,3.85000),(-4.00000,5.66667,3.85000),(-4.00000,11.33333,-7.70000),(-12.00000,5.66667,-7.70000),(4.00000,5.66667,-7.70000),(20.00000,17.00000,0.00000),(20.00000,11.33333,2.56667),(12.00000,5.66667,3.85000),(12.00000,11.33333,-7.70000),(20.00000,5.66667,-7.70000),(-20.00000,-17.00000,0.00000),(20.00000,-17.00000,0.00000),(-20.00000,17.00000,0.00000),(-16.00000,-5.66667,-0.32083),(0.00000,-5.66667,-0.64167),(-8.00000,-5.66667,-0.64167),(-16.00000,-11.33333,-0.96250),(-8.00000,-11.33333,-0.64167),(-13.14286,6.47619,-2.20000),(0.00000,-11.33333,-0.64167),(-17.33333,-15.11111,-3.42222),(-4.00000,-15.11111,-4.27778),(13.33333,-7.55556,-2.82333),(8.00000,-5.66667,-0.70583),(8.00000,-11.33333,-0.96250),(4.00000,0.00000,-8.72667),(-8.00000,11.33333,-0.32083),(8.00000,11.33333,-0.64167),(0.00000,11.33333,-0.64167),(-8.00000,5.66667,-0.96250),(0.00000,5.66667,-0.64167),(-4.00000,15.11111,-3.42222),(8.00000,5.66667,-0.38500),(16.00000,11.33333,-0.32083),(16.00000,5.66667,-0.70583),(12.00000,15.11111,-3.42222)]
BLOCK_FACES = [(0,1,31),(1,4,31),(4,6,31),(6,0,31),(2,3,32),(3,11,32),(11,13,32),(13,2,32),(3,2,33),(2,6,33),(6,4,33),(4,3,33),(4,1,34),(1,7,34),(7,5,34),(5,4,34),(3,4,35),(4,5,35),(5,8,35),(8,3,35),(0,6,36),(6,2,36),(2,21,36),(21,16,36),(16,15,36),(15,30,36),(30,0,36),(3,8,37),(8,12,37),(12,11,37),(11,3,37),(5,7,38),(7,28,38),(28,5,38),(8,5,39),(5,12,39),(12,8,39),(9,10,40),(10,14,40),(14,12,40),(12,29,40),(29,27,40),(27,9,40),(10,9,41),(9,13,41),(13,11,41),(11,10,41),(10,11,42),(11,12,42),(12,14,42),(14,10,42),(2,13,43),(13,9,43),(9,22,43),(22,2,43),(15,16,44),(16,19,44),(19,20,44),(20,15,44),(17,18,45),(18,25,45),(25,26,45),(26,17,45),(18,17,46),(17,20,46),(20,19,46),(19,18,46),(19,16,47),(16,21,47),(21,2,47),(2,19,47),(18,19,48),(19,2,48),(2,22,48),(22,18,48),(15,20,49),(20,17,49),(17,15,49),(18,22,50),(22,9,50),(9,25,50),(25,18,50),(24,23,51),(23,26,51),(26,25,51),(25,24,51),(24,25,52),(25,9,52),(9,27,52),(27,24,52),(17,26,53),(26,23,53),(23,17,53)]
BLOCK_DX, BLOCK_DY = 32.0, 34.0
DEF_AROUND, DEF_ALONG, DEF_DIAM, DEF_WALL = 4, 5, 40.74, 4.0


def _block_mesh(obj_name):
    me = bpy.data.meshes.new(obj_name + "_block")
    me.from_pydata([list(v) for v in BLOCK_VERTS], [], [list(f) for f in BLOCK_FACES])
    me.update()
    obj = bpy.data.objects.new(obj_name, me)
    bpy.context.scene.collection.objects.link(obj)
    return obj


def _node_group():
    if "BellowsRoller" in bpy.data.node_groups:
        return bpy.data.node_groups["BellowsRoller"]
    ng = bpy.data.node_groups.new("BellowsRoller", "GeometryNodeTree")
    itf = ng.interface
    itf.new_socket("Geometry", in_out="INPUT", socket_type="NodeSocketGeometry")
    itf.new_socket("Geometry", in_out="OUTPUT", socket_type="NodeSocketGeometry")
    s_diam = itf.new_socket("Diameter", in_out="INPUT", socket_type="NodeSocketFloat")
    s_diam.default_value = DEF_DIAM; s_diam.min_value = 1.0
    s_ar = itf.new_socket("Tiles around", in_out="INPUT", socket_type="NodeSocketInt")
    s_ar.default_value = DEF_AROUND; s_ar.min_value = 1
    s_al = itf.new_socket("Tiles along", in_out="INPUT", socket_type="NodeSocketInt")
    s_al.default_value = DEF_ALONG; s_al.min_value = 1
    s_rd = itf.new_socket("Relief depth", in_out="INPUT", socket_type="NodeSocketFloat")
    s_rd.default_value = 1.0
    s_cw = itf.new_socket("Core wall", in_out="INPUT", socket_type="NodeSocketFloat")
    s_cw.default_value = DEF_WALL; s_cw.min_value = 0.1

    nd, lk = ng.nodes, ng.links
    x = 0
    def add(t, **kw):
        nonlocal x
        n = nd.new(t); n.location = (x, 0); x += 200
        for k, v in kw.items(): setattr(n, k, v)
        return n
    gin = add("NodeGroupInput"); gout = nd.new("NodeGroupOutput"); gout.location = (3200, 0)

    def mul(a, b):
        m = add("ShaderNodeMath"); m.operation = "MULTIPLY"
        _wire(lk, a, m.inputs[0]); _wire(lk, b, m.inputs[1]); return m.outputs[0]
    def sub(a, b):
        m = add("ShaderNodeMath"); m.operation = "SUBTRACT"
        _wire(lk, a, m.inputs[0]); _wire(lk, b, m.inputs[1]); return m.outputs[0]
    def add_(a, b):
        m = add("ShaderNodeMath"); m.operation = "ADD"
        _wire(lk, a, m.inputs[0]); _wire(lk, b, m.inputs[1]); return m.outputs[0]
    def div(a, b):
        m = add("ShaderNodeMath"); m.operation = "DIVIDE"
        _wire(lk, a, m.inputs[0]); _wire(lk, b, m.inputs[1]); return m.outputs[0]

    around = gin.outputs["Tiles around"]; along = gin.outputs["Tiles along"]
    circ = mul(around, BLOCK_DX)                       # circumference (mm)

    # grid of array points (around × along, spacing block_dx/dy)
    grid = add("GeometryNodeMeshGrid")
    _wire(lk, mul(sub(around, 1.0), BLOCK_DX), grid.inputs["Size X"])
    _wire(lk, mul(sub(along, 1.0), BLOCK_DY), grid.inputs["Size Y"])
    _wire(lk, around, grid.inputs["Vertices X"]); _wire(lk, along, grid.inputs["Vertices Y"])
    m2p = add("GeometryNodeMeshToPoints"); lk.new(grid.outputs["Mesh"], m2p.inputs["Mesh"])
    iop = add("GeometryNodeInstanceOnPoints")
    lk.new(m2p.outputs["Points"], iop.inputs["Points"])
    lk.new(gin.outputs["Geometry"], iop.inputs["Instance"])
    rea = add("GeometryNodeRealizeInstances"); lk.new(iop.outputs["Instances"], rea.inputs["Geometry"])
    mg1 = add("GeometryNodeMergeByDistance"); mg1.inputs["Distance"].default_value = 0.001
    lk.new(rea.outputs["Geometry"], mg1.inputs["Geometry"])

    # wrap: pos = (r·cosθ, r·sinθ, y);  θ = x·2π/circ;  r = diam/2 + z·relief_depth
    pos = add("GeometryNodeInputPosition"); sep = add("ShaderNodeSeparateXYZ")
    lk.new(pos.outputs["Position"], sep.inputs["Vector"])
    theta = mul(sep.outputs["X"], div(2 * math.pi, circ))
    r = add_(mul(sep.outputs["Z"], gin.outputs["Relief depth"]),
             div(gin.outputs["Diameter"], 2.0))
    cs = add("ShaderNodeMath"); cs.operation = "COSINE"; _wire(lk, theta, cs.inputs[0])
    sn = add("ShaderNodeMath"); sn.operation = "SINE"; _wire(lk, theta, sn.inputs[0])
    comb = add("ShaderNodeCombineXYZ")
    _wire(lk, mul(r, cs.outputs[0]), comb.inputs["X"])
    _wire(lk, mul(r, sn.outputs[0]), comb.inputs["Y"])
    lk.new(sep.outputs["Y"], comb.inputs["Z"])
    setp = add("GeometryNodeSetPosition")
    lk.new(mg1.outputs["Geometry"], setp.inputs["Geometry"])
    lk.new(comb.outputs["Vector"], setp.inputs["Position"])
    mg2 = add("GeometryNodeMergeByDistance"); mg2.inputs["Distance"].default_value = 0.05
    lk.new(setp.outputs["Geometry"], mg2.inputs["Geometry"])

    # solidify: extrude every face inward (−radial) by Core wall → closed shell
    pos2 = add("GeometryNodeInputPosition"); sep2 = add("ShaderNodeSeparateXYZ")
    lk.new(pos2.outputs["Position"], sep2.inputs["Vector"])
    rad = add("ShaderNodeCombineXYZ")
    lk.new(sep2.outputs["X"], rad.inputs["X"]); lk.new(sep2.outputs["Y"], rad.inputs["Y"])
    nrm = add("ShaderNodeVectorMath"); nrm.operation = "NORMALIZE"; lk.new(rad.outputs["Vector"], nrm.inputs[0])
    negwall = add("ShaderNodeMath"); negwall.operation = "MULTIPLY"
    lk.new(gin.outputs["Core wall"], negwall.inputs[0]); negwall.inputs[1].default_value = -1.0
    off = add("ShaderNodeVectorMath"); off.operation = "SCALE"
    lk.new(nrm.outputs["Vector"], off.inputs[0]); _wire(lk, negwall.outputs[0], off.inputs["Scale"])
    extr = add("GeometryNodeExtrudeMesh"); extr.mode = "FACES"
    lk.new(mg2.outputs["Geometry"], extr.inputs["Mesh"])
    lk.new(off.outputs["Vector"], extr.inputs["Offset"])
    shade = add("GeometryNodeSetShadeSmooth"); shade.inputs["Shade Smooth"].default_value = False
    lk.new(extr.outputs["Mesh"], shade.inputs["Geometry"])
    lk.new(shade.outputs["Geometry"], gout.inputs["Geometry"])
    return ng


def _wire(links, src, dst):
    """Link a socket *src* to input *dst*, or set a constant if *src* is a number."""
    if hasattr(src, "is_output") or hasattr(src, "links") or "Socket" in type(src).__name__:
        links.new(src, dst)
    else:
        dst.default_value = src


def _make_roller(obj_name, relief_depth):
    obj = _block_mesh(obj_name)
    md = obj.modifiers.new("BellowsRoller", "NODES")
    md.node_group = _node_group()
    for it in md.node_group.interface.items_tree:
        if getattr(it, "in_out", "") == "INPUT" and it.name == "Relief depth":
            md[it.identifier] = float(relief_depth)
    return obj


def build():
    male = _make_roller("miura_roller_male", 1.0)
    female = _make_roller("miura_roller_female", -1.0)
    female.location.x = (DEF_DIAM * 1.6)
    return male, female


if __name__ == "__main__":
    build()
