"""Parametric Geometry Nodes rollers for the yoshimura bellows pattern.

Run in Blender::  blender -b -P yoshimura_roller_gn.py     (or open + Run Script)

Creates two objects — ``yoshimura_roller_male`` and ``yoshimura_roller_female`` — each
with a ``BellowsRoller`` Geometry Nodes modifier whose inputs stay editable:

    Diameter (mm) · Tiles around · Tiles along · Relief depth · Core wall (mm)

The female is the male's negative (Relief depth < 0) so the pair meshes like gears.
Auto-generated by bellows_diecut.core.roller_gn — do not edit by hand.
"""
import bpy, math

BLOCK_VERTS = [(-16.00000,-8.00000,0.00000),(-8.00000,0.00000,0.00000),(0.00000,-8.00000,0.00000),(-8.00000,-16.00000,0.00000),(-16.00000,0.00000,0.00000),(0.00000,0.00000,0.00000),(8.00000,0.00000,0.00000),(16.00000,-8.00000,0.00000),(8.00000,-16.00000,0.00000),(16.00000,0.00000,0.00000),(-16.00000,8.00000,0.00000),(-8.00000,16.00000,0.00000),(0.00000,8.00000,0.00000),(-16.00000,16.00000,0.00000),(0.00000,16.00000,0.00000),(8.00000,16.00000,0.00000),(16.00000,8.00000,0.00000),(16.00000,16.00000,0.00000),(-16.00000,-16.00000,0.00000),(16.00000,-16.00000,0.00000),(-8.00000,-8.00000,7.20000),(8.00000,-8.00000,-7.20000),(-8.00000,8.00000,-7.20000),(8.00000,8.00000,7.20000),(-13.33333,-2.66667,0.00000),(0.00000,-2.00000,0.00000),(0.00000,-13.33333,0.00000),(-13.33333,-13.33333,0.00000),(-13.33333,2.66667,0.00000),(0.00000,2.00000,0.00000),(13.33333,-2.66667,0.00000),(13.33333,-13.33333,0.00000),(13.33333,2.66667,0.00000),(-13.33333,13.33333,0.00000),(0.00000,14.00000,0.00000),(13.33333,13.33333,0.00000)]
BLOCK_FACES = [(1,0,20),(2,1,20),(3,2,20),(0,3,20),(6,2,21),(7,6,21),(8,7,21),(2,8,21),(11,10,22),(12,11,22),(1,12,22),(10,1,22),(15,12,23),(16,15,23),(6,16,23),(12,6,23),(0,1,24),(1,4,24),(4,0,24),(1,2,25),(2,6,25),(6,5,25),(5,1,25),(2,3,26),(3,8,26),(8,2,26),(3,0,27),(0,18,27),(18,3,27),(4,1,28),(1,10,28),(10,4,28),(1,5,29),(5,6,29),(6,12,29),(12,1,29),(6,7,30),(7,9,30),(9,6,30),(7,8,31),(8,19,31),(19,7,31),(6,9,32),(9,16,32),(16,6,32),(10,11,33),(11,13,33),(13,10,33),(11,12,34),(12,15,34),(15,14,34),(14,11,34),(15,16,35),(16,17,35),(17,15,35)]
BLOCK_DX, BLOCK_DY = 32.0, 32.0
DEF_AROUND, DEF_ALONG, DEF_DIAM, DEF_WALL = 5, 5, 50.93, 4.0


def _block_mesh(obj_name):
    me = bpy.data.meshes.new(obj_name + "_block")
    me.from_pydata([list(v) for v in BLOCK_VERTS], [], [list(f) for f in BLOCK_FACES])
    me.update()
    obj = bpy.data.objects.new(obj_name, me)
    bpy.context.scene.collection.objects.link(obj)
    return obj


def _node_group():
    if "BellowsRoller" in bpy.data.node_groups:
        return bpy.data.node_groups["BellowsRoller"]
    ng = bpy.data.node_groups.new("BellowsRoller", "GeometryNodeTree")
    itf = ng.interface
    itf.new_socket("Geometry", in_out="INPUT", socket_type="NodeSocketGeometry")
    itf.new_socket("Geometry", in_out="OUTPUT", socket_type="NodeSocketGeometry")
    s_diam = itf.new_socket("Diameter", in_out="INPUT", socket_type="NodeSocketFloat")
    s_diam.default_value = DEF_DIAM; s_diam.min_value = 1.0
    s_ar = itf.new_socket("Tiles around", in_out="INPUT", socket_type="NodeSocketInt")
    s_ar.default_value = DEF_AROUND; s_ar.min_value = 1
    s_al = itf.new_socket("Tiles along", in_out="INPUT", socket_type="NodeSocketInt")
    s_al.default_value = DEF_ALONG; s_al.min_value = 1
    s_rd = itf.new_socket("Relief depth", in_out="INPUT", socket_type="NodeSocketFloat")
    s_rd.default_value = 1.0
    s_cw = itf.new_socket("Core wall", in_out="INPUT", socket_type="NodeSocketFloat")
    s_cw.default_value = DEF_WALL; s_cw.min_value = 0.1

    nd, lk = ng.nodes, ng.links
    x = 0
    def add(t, **kw):
        nonlocal x
        n = nd.new(t); n.location = (x, 0); x += 200
        for k, v in kw.items(): setattr(n, k, v)
        return n
    gin = add("NodeGroupInput"); gout = nd.new("NodeGroupOutput"); gout.location = (3200, 0)

    def mul(a, b):
        m = add("ShaderNodeMath"); m.operation = "MULTIPLY"
        _wire(lk, a, m.inputs[0]); _wire(lk, b, m.inputs[1]); return m.outputs[0]
    def sub(a, b):
        m = add("ShaderNodeMath"); m.operation = "SUBTRACT"
        _wire(lk, a, m.inputs[0]); _wire(lk, b, m.inputs[1]); return m.outputs[0]
    def add_(a, b):
        m = add("ShaderNodeMath"); m.operation = "ADD"
        _wire(lk, a, m.inputs[0]); _wire(lk, b, m.inputs[1]); return m.outputs[0]
    def div(a, b):
        m = add("ShaderNodeMath"); m.operation = "DIVIDE"
        _wire(lk, a, m.inputs[0]); _wire(lk, b, m.inputs[1]); return m.outputs[0]

    around = gin.outputs["Tiles around"]; along = gin.outputs["Tiles along"]
    circ = mul(around, BLOCK_DX)                       # circumference (mm)

    # grid of array points (around × along, spacing block_dx/dy)
    grid = add("GeometryNodeMeshGrid")
    _wire(lk, mul(sub(around, 1.0), BLOCK_DX), grid.inputs["Size X"])
    _wire(lk, mul(sub(along, 1.0), BLOCK_DY), grid.inputs["Size Y"])
    _wire(lk, around, grid.inputs["Vertices X"]); _wire(lk, along, grid.inputs["Vertices Y"])
    m2p = add("GeometryNodeMeshToPoints"); lk.new(grid.outputs["Mesh"], m2p.inputs["Mesh"])
    iop = add("GeometryNodeInstanceOnPoints")
    lk.new(m2p.outputs["Points"], iop.inputs["Points"])
    lk.new(gin.outputs["Geometry"], iop.inputs["Instance"])
    rea = add("GeometryNodeRealizeInstances"); lk.new(iop.outputs["Instances"], rea.inputs["Geometry"])
    mg1 = add("GeometryNodeMergeByDistance"); mg1.inputs["Distance"].default_value = 0.001
    lk.new(rea.outputs["Geometry"], mg1.inputs["Geometry"])

    # wrap: pos = (r·cosθ, r·sinθ, y);  θ = x·2π/circ;  r = diam/2 + z·relief_depth
    pos = add("GeometryNodeInputPosition"); sep = add("ShaderNodeSeparateXYZ")
    lk.new(pos.outputs["Position"], sep.inputs["Vector"])
    theta = mul(sep.outputs["X"], div(2 * math.pi, circ))
    r = add_(mul(sep.outputs["Z"], gin.outputs["Relief depth"]),
             div(gin.outputs["Diameter"], 2.0))
    cs = add("ShaderNodeMath"); cs.operation = "COSINE"; _wire(lk, theta, cs.inputs[0])
    sn = add("ShaderNodeMath"); sn.operation = "SINE"; _wire(lk, theta, sn.inputs[0])
    comb = add("ShaderNodeCombineXYZ")
    _wire(lk, mul(r, cs.outputs[0]), comb.inputs["X"])
    _wire(lk, mul(r, sn.outputs[0]), comb.inputs["Y"])
    lk.new(sep.outputs["Y"], comb.inputs["Z"])
    setp = add("GeometryNodeSetPosition")
    lk.new(mg1.outputs["Geometry"], setp.inputs["Geometry"])
    lk.new(comb.outputs["Vector"], setp.inputs["Position"])
    mg2 = add("GeometryNodeMergeByDistance"); mg2.inputs["Distance"].default_value = 0.05
    lk.new(setp.outputs["Geometry"], mg2.inputs["Geometry"])

    # solidify: extrude every face inward (−radial) by Core wall → closed shell
    pos2 = add("GeometryNodeInputPosition"); sep2 = add("ShaderNodeSeparateXYZ")
    lk.new(pos2.outputs["Position"], sep2.inputs["Vector"])
    rad = add("ShaderNodeCombineXYZ")
    lk.new(sep2.outputs["X"], rad.inputs["X"]); lk.new(sep2.outputs["Y"], rad.inputs["Y"])
    nrm = add("ShaderNodeVectorMath"); nrm.operation = "NORMALIZE"; lk.new(rad.outputs["Vector"], nrm.inputs[0])
    negwall = add("ShaderNodeMath"); negwall.operation = "MULTIPLY"
    lk.new(gin.outputs["Core wall"], negwall.inputs[0]); negwall.inputs[1].default_value = -1.0
    off = add("ShaderNodeVectorMath"); off.operation = "SCALE"
    lk.new(nrm.outputs["Vector"], off.inputs[0]); _wire(lk, negwall.outputs[0], off.inputs["Scale"])
    extr = add("GeometryNodeExtrudeMesh"); extr.mode = "FACES"
    lk.new(mg2.outputs["Geometry"], extr.inputs["Mesh"])
    lk.new(off.outputs["Vector"], extr.inputs["Offset"])
    shade = add("GeometryNodeSetShadeSmooth"); shade.inputs["Shade Smooth"].default_value = False
    lk.new(extr.outputs["Mesh"], shade.inputs["Geometry"])
    lk.new(shade.outputs["Geometry"], gout.inputs["Geometry"])
    return ng


def _wire(links, src, dst):
    """Link a socket *src* to input *dst*, or set a constant if *src* is a number."""
    if hasattr(src, "is_output") or hasattr(src, "links") or "Socket" in type(src).__name__:
        links.new(src, dst)
    else:
        dst.default_value = src


def _make_roller(obj_name, relief_depth):
    obj = _block_mesh(obj_name)
    md = obj.modifiers.new("BellowsRoller", "NODES")
    md.node_group = _node_group()
    for it in md.node_group.interface.items_tree:
        if getattr(it, "in_out", "") == "INPUT" and it.name == "Relief depth":
            md[it.identifier] = float(relief_depth)
    return obj


def build():
    male = _make_roller("yoshimura_roller_male", 1.0)
    female = _make_roller("yoshimura_roller_female", -1.0)
    female.location.x = (DEF_DIAM * 1.6)
    return male, female


if __name__ == "__main__":
    build()
