from print_labo.utils.dev_mode import install_dev_mode

def run_dev_mode():
    install_dev_mode(source_script=PosixPath('/home/egxn/Catcode/tanuki_apps/print_labo/src/print_labo/misc_prints/00_lamp.py'), output_script=PosixPath('/home/egxn/Catcode/tanuki_apps/print_labo/01_lamp.py'), watch_paths=[PosixPath('/home/egxn/Catcode/tanuki_apps/print_labo/src/print_labo/misc_prints')], open_blender=True)

if __name__ == '__main__':
    run_dev_mode()


import bpy


def setup_wood_join(object_name='wood_join'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (0, 280)
    val_2.label = 'cylinder_1 radius'
    val_2.outputs[0].default_value = 22.75
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (0, 560)
    val_3.label = 'cylinder_1 depth'
    val_3.outputs[0].default_value = 60
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 0)
    prim_1.label = 'cylinder_1'
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 16
    vec_5 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_5.location = (300, 280)
    vec_5.label = "tap size"
    vec_5.vector = [20, 40, 20]
    prim_4 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_4.location = (300, 0)
    prim_4.label = 'tap'
    node_tree.links.new(vec_5.outputs["Vector"], prim_4.inputs["Size"])
    vec_7 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_7.location = (600, 280)
    vec_7.label = 'tap position offset'
    vec_7.vector = [0, 12.75, 20]
    setpos_6 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_6.location = (600, 0)
    setpos_6.label = 'tap position'
    node_tree.links.new(prim_4.outputs["Mesh"], setpos_6.inputs["Geometry"])
    node_tree.links.new(vec_7.outputs["Vector"], setpos_6.inputs["Offset"])
    vec_9 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_9.location = (900, 280)
    vec_9.label = "tap size"
    vec_9.vector = [20, 40, 20]
    prim_8 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_8.location = (900, 0)
    prim_8.label = 'tap'
    node_tree.links.new(vec_9.outputs["Vector"], prim_8.inputs["Size"])
    vec_11 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_11.location = (1200, 280)
    vec_11.label = 'tap position offset'
    vec_11.vector = [0, 12.75, -20]
    setpos_10 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_10.location = (1200, 0)
    setpos_10.label = 'tap position'
    node_tree.links.new(prim_8.outputs["Mesh"], setpos_10.inputs["Geometry"])
    node_tree.links.new(vec_11.outputs["Vector"], setpos_10.inputs["Offset"])
    bool_12 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_12.location = (1500, 0)
    bool_12.label = 'union'
    bool_12.operation = "UNION"
    try:
        bool_12.solver = "EXACT"
    except (TypeError, ValueError):
        bool_12.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_12.inputs[1])
    node_tree.links.new(setpos_6.outputs["Geometry"], bool_12.inputs[1])
    node_tree.links.new(setpos_10.outputs["Geometry"], bool_12.inputs[1])
    val_14 = node_tree.nodes.new("ShaderNodeValue")
    val_14.location = (1800, 280)
    val_14.label = 'h_cylinder_1 radius'
    val_14.outputs[0].default_value = 18.0
    val_15 = node_tree.nodes.new("ShaderNodeValue")
    val_15.location = (1800, 560)
    val_15.label = 'h_cylinder_1 depth'
    val_15.outputs[0].default_value = 70
    prim_13 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_13.location = (1800, 0)
    prim_13.label = 'h_cylinder_1'
    node_tree.links.new(val_14.outputs["Value"], prim_13.inputs["Radius"])
    node_tree.links.new(val_15.outputs["Value"], prim_13.inputs["Depth"])
    prim_13.inputs["Vertices"].default_value = 64
    vec_17 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_17.location = (2100, 280)
    vec_17.label = "h_tap size"
    vec_17.vector = [10, 40, 40]
    prim_16 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_16.location = (2100, 0)
    prim_16.label = 'h_tap'
    node_tree.links.new(vec_17.outputs["Vector"], prim_16.inputs["Size"])
    vec_19 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_19.location = (2400, 280)
    vec_19.label = 'h_tap position offset'
    vec_19.vector = [0, 12.75, 30]
    setpos_18 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_18.location = (2400, 0)
    setpos_18.label = 'h_tap position'
    node_tree.links.new(prim_16.outputs["Mesh"], setpos_18.inputs["Geometry"])
    node_tree.links.new(vec_19.outputs["Vector"], setpos_18.inputs["Offset"])
    vec_21 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_21.location = (2700, 280)
    vec_21.label = "h_tap size"
    vec_21.vector = [10, 40, 40]
    prim_20 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_20.location = (2700, 0)
    prim_20.label = 'h_tap'
    node_tree.links.new(vec_21.outputs["Vector"], prim_20.inputs["Size"])
    vec_23 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_23.location = (3000, 280)
    vec_23.label = 'h_tap position offset'
    vec_23.vector = [0, 12.75, -30]
    setpos_22 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_22.location = (3000, 0)
    setpos_22.label = 'h_tap position'
    node_tree.links.new(prim_20.outputs["Mesh"], setpos_22.inputs["Geometry"])
    node_tree.links.new(vec_23.outputs["Vector"], setpos_22.inputs["Offset"])
    bool_24 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_24.location = (3300, 0)
    bool_24.label = 'difference'
    bool_24.operation = "DIFFERENCE"
    try:
        bool_24.solver = "EXACT"
    except (TypeError, ValueError):
        bool_24.solver = "EXACT"
    node_tree.links.new(bool_12.outputs["Mesh"], bool_24.inputs[0])
    node_tree.links.new(prim_13.outputs["Mesh"], bool_24.inputs[1])
    node_tree.links.new(setpos_18.outputs["Geometry"], bool_24.inputs[1])
    node_tree.links.new(setpos_22.outputs["Geometry"], bool_24.inputs[1])
    val_26 = node_tree.nodes.new("ShaderNodeValue")
    val_26.location = (3600, 280)
    val_26.label = 'cylinder_2 radius'
    val_26.outputs[0].default_value = 5
    val_27 = node_tree.nodes.new("ShaderNodeValue")
    val_27.location = (3600, 560)
    val_27.label = 'cylinder_2 depth'
    val_27.outputs[0].default_value = 40
    prim_25 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_25.location = (3600, 0)
    prim_25.label = 'cylinder_2'
    node_tree.links.new(val_26.outputs["Value"], prim_25.inputs["Radius"])
    node_tree.links.new(val_27.outputs["Value"], prim_25.inputs["Depth"])
    prim_25.inputs["Vertices"].default_value = 124
    vec_29 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_29.location = (3900, 280)
    vec_29.label = 'cylinder_2 rotate rotation'
    vec_29.vector = [0.0, 1.5707963267948966, 0.0]
    xform_28 = node_tree.nodes.new("GeometryNodeTransform")
    xform_28.location = (3900, 0)
    xform_28.label = 'cylinder_2 rotate'
    node_tree.links.new(prim_25.outputs["Mesh"], xform_28.inputs["Geometry"])
    node_tree.links.new(vec_29.outputs["Vector"], xform_28.inputs["Rotation"])
    vec_31 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_31.location = (4200, 280)
    vec_31.label = 'cylinder_2 rotate position offset'
    vec_31.vector = [0, 10, 20]
    setpos_30 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_30.location = (4200, 0)
    setpos_30.label = 'cylinder_2 rotate position'
    node_tree.links.new(xform_28.outputs["Geometry"], setpos_30.inputs["Geometry"])
    node_tree.links.new(vec_31.outputs["Vector"], setpos_30.inputs["Offset"])
    val_33 = node_tree.nodes.new("ShaderNodeValue")
    val_33.location = (4500, 280)
    val_33.label = 'cylinder_3 radius'
    val_33.outputs[0].default_value = 5
    val_34 = node_tree.nodes.new("ShaderNodeValue")
    val_34.location = (4500, 560)
    val_34.label = 'cylinder_3 depth'
    val_34.outputs[0].default_value = 40
    prim_32 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_32.location = (4500, 0)
    prim_32.label = 'cylinder_3'
    node_tree.links.new(val_33.outputs["Value"], prim_32.inputs["Radius"])
    node_tree.links.new(val_34.outputs["Value"], prim_32.inputs["Depth"])
    prim_32.inputs["Vertices"].default_value = 124
    vec_36 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_36.location = (4800, 280)
    vec_36.label = 'cylinder_3 rotate rotation'
    vec_36.vector = [0.0, 1.5707963267948966, 0.0]
    xform_35 = node_tree.nodes.new("GeometryNodeTransform")
    xform_35.location = (4800, 0)
    xform_35.label = 'cylinder_3 rotate'
    node_tree.links.new(prim_32.outputs["Mesh"], xform_35.inputs["Geometry"])
    node_tree.links.new(vec_36.outputs["Vector"], xform_35.inputs["Rotation"])
    vec_38 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_38.location = (5100, 280)
    vec_38.label = 'cylinder_3 rotate position offset'
    vec_38.vector = [0, 10, -20]
    setpos_37 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_37.location = (5100, 0)
    setpos_37.label = 'cylinder_3 rotate position'
    node_tree.links.new(xform_35.outputs["Geometry"], setpos_37.inputs["Geometry"])
    node_tree.links.new(vec_38.outputs["Vector"], setpos_37.inputs["Offset"])
    bool_39 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_39.location = (5400, 0)
    bool_39.label = 'union'
    bool_39.operation = "UNION"
    try:
        bool_39.solver = "EXACT"
    except (TypeError, ValueError):
        bool_39.solver = "EXACT"
    node_tree.links.new(bool_24.outputs["Mesh"], bool_39.inputs[1])
    node_tree.links.new(setpos_30.outputs["Geometry"], bool_39.inputs[1])
    node_tree.links.new(setpos_37.outputs["Geometry"], bool_39.inputs[1])
    out_40 = node_tree.nodes.new("NodeGroupOutput")
    out_40.location = (5700, 0)
    out_40.label = "output"
    node_tree.links.new(bool_39.outputs[0], out_40.inputs[0])

    return node_tree





# Execute all parts
setup_wood_join()
