import bpy


def setup_openbuilds_2040_camera_carriage(object_name='openbuilds_2040_camera_carriage'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (0, 280)
    vec_2.label = "carriage_plate size"
    vec_2.vector = [80.0, 80.0, 8.0]
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 0)
    prim_1.label = 'carriage_plate'
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    val_4 = node_tree.nodes.new("ShaderNodeValue")
    val_4.location = (300, 280)
    val_4.label = 'wheel_top_left radius'
    val_4.outputs[0].default_value = 2.6
    val_5 = node_tree.nodes.new("ShaderNodeValue")
    val_5.location = (300, 560)
    val_5.label = 'wheel_top_left depth'
    val_5.outputs[0].default_value = 10.0
    prim_3 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_3.location = (300, 0)
    prim_3.label = 'wheel_top_left'
    node_tree.links.new(val_4.outputs["Value"], prim_3.inputs["Radius"])
    node_tree.links.new(val_5.outputs["Value"], prim_3.inputs["Depth"])
    prim_3.inputs["Vertices"].default_value = 32
    vec_7 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_7.location = (600, 280)
    vec_7.label = 'wheel_top_left position offset'
    vec_7.vector = [-20.0, 30.0, 0]
    setpos_6 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_6.location = (600, 0)
    setpos_6.label = 'wheel_top_left position'
    node_tree.links.new(prim_3.outputs["Mesh"], setpos_6.inputs["Geometry"])
    node_tree.links.new(vec_7.outputs["Vector"], setpos_6.inputs["Offset"])
    val_9 = node_tree.nodes.new("ShaderNodeValue")
    val_9.location = (900, 280)
    val_9.label = 'wheel_top_right radius'
    val_9.outputs[0].default_value = 2.6
    val_10 = node_tree.nodes.new("ShaderNodeValue")
    val_10.location = (900, 560)
    val_10.label = 'wheel_top_right depth'
    val_10.outputs[0].default_value = 10.0
    prim_8 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_8.location = (900, 0)
    prim_8.label = 'wheel_top_right'
    node_tree.links.new(val_9.outputs["Value"], prim_8.inputs["Radius"])
    node_tree.links.new(val_10.outputs["Value"], prim_8.inputs["Depth"])
    prim_8.inputs["Vertices"].default_value = 32
    vec_12 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_12.location = (1200, 280)
    vec_12.label = 'wheel_top_right position offset'
    vec_12.vector = [20.0, 30.0, 0]
    setpos_11 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_11.location = (1200, 0)
    setpos_11.label = 'wheel_top_right position'
    node_tree.links.new(prim_8.outputs["Mesh"], setpos_11.inputs["Geometry"])
    node_tree.links.new(vec_12.outputs["Vector"], setpos_11.inputs["Offset"])
    val_14 = node_tree.nodes.new("ShaderNodeValue")
    val_14.location = (1500, 280)
    val_14.label = 'wheel_bottom_left radius'
    val_14.outputs[0].default_value = 3.6
    val_15 = node_tree.nodes.new("ShaderNodeValue")
    val_15.location = (1500, 560)
    val_15.label = 'wheel_bottom_left depth'
    val_15.outputs[0].default_value = 10.0
    prim_13 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_13.location = (1500, 0)
    prim_13.label = 'wheel_bottom_left'
    node_tree.links.new(val_14.outputs["Value"], prim_13.inputs["Radius"])
    node_tree.links.new(val_15.outputs["Value"], prim_13.inputs["Depth"])
    prim_13.inputs["Vertices"].default_value = 32
    vec_17 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_17.location = (1800, 280)
    vec_17.label = 'wheel_bottom_left position offset'
    vec_17.vector = [-20.0, -30.0, 0]
    setpos_16 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_16.location = (1800, 0)
    setpos_16.label = 'wheel_bottom_left position'
    node_tree.links.new(prim_13.outputs["Mesh"], setpos_16.inputs["Geometry"])
    node_tree.links.new(vec_17.outputs["Vector"], setpos_16.inputs["Offset"])
    val_19 = node_tree.nodes.new("ShaderNodeValue")
    val_19.location = (2100, 280)
    val_19.label = 'wheel_bottom_right radius'
    val_19.outputs[0].default_value = 3.6
    val_20 = node_tree.nodes.new("ShaderNodeValue")
    val_20.location = (2100, 560)
    val_20.label = 'wheel_bottom_right depth'
    val_20.outputs[0].default_value = 10.0
    prim_18 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_18.location = (2100, 0)
    prim_18.label = 'wheel_bottom_right'
    node_tree.links.new(val_19.outputs["Value"], prim_18.inputs["Radius"])
    node_tree.links.new(val_20.outputs["Value"], prim_18.inputs["Depth"])
    prim_18.inputs["Vertices"].default_value = 32
    vec_22 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_22.location = (2400, 280)
    vec_22.label = 'wheel_bottom_right position offset'
    vec_22.vector = [20.0, -30.0, 0]
    setpos_21 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_21.location = (2400, 0)
    setpos_21.label = 'wheel_bottom_right position'
    node_tree.links.new(prim_18.outputs["Mesh"], setpos_21.inputs["Geometry"])
    node_tree.links.new(vec_22.outputs["Vector"], setpos_21.inputs["Offset"])
    val_24 = node_tree.nodes.new("ShaderNodeValue")
    val_24.location = (2700, 280)
    val_24.label = 'tripod_hole_1 radius'
    val_24.outputs[0].default_value = 3
    val_25 = node_tree.nodes.new("ShaderNodeValue")
    val_25.location = (2700, 560)
    val_25.label = 'tripod_hole_1 depth'
    val_25.outputs[0].default_value = 10
    prim_23 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_23.location = (2700, 0)
    prim_23.label = 'tripod_hole_1'
    node_tree.links.new(val_24.outputs["Value"], prim_23.inputs["Radius"])
    node_tree.links.new(val_25.outputs["Value"], prim_23.inputs["Depth"])
    prim_23.inputs["Vertices"].default_value = 32
    val_27 = node_tree.nodes.new("ShaderNodeValue")
    val_27.location = (3000, 280)
    val_27.label = 'tripod_hole_2 radius'
    val_27.outputs[0].default_value = 6
    val_28 = node_tree.nodes.new("ShaderNodeValue")
    val_28.location = (3000, 560)
    val_28.label = 'tripod_hole_2 depth'
    val_28.outputs[0].default_value = 4
    prim_26 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_26.location = (3000, 0)
    prim_26.label = 'tripod_hole_2'
    node_tree.links.new(val_27.outputs["Value"], prim_26.inputs["Radius"])
    node_tree.links.new(val_28.outputs["Value"], prim_26.inputs["Depth"])
    prim_26.inputs["Vertices"].default_value = 32
    vec_30 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_30.location = (3300, 280)
    vec_30.label = 'tripod_hole_2 position offset'
    vec_30.vector = [0, 0, 2]
    setpos_29 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_29.location = (3300, 0)
    setpos_29.label = 'tripod_hole_2 position'
    node_tree.links.new(prim_26.outputs["Mesh"], setpos_29.inputs["Geometry"])
    node_tree.links.new(vec_30.outputs["Vector"], setpos_29.inputs["Offset"])
    bool_31 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_31.location = (3600, 0)
    bool_31.label = 'difference'
    bool_31.operation = "DIFFERENCE"
    try:
        bool_31.solver = "EXACT"
    except (TypeError, ValueError):
        bool_31.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_31.inputs[0])
    node_tree.links.new(setpos_6.outputs["Geometry"], bool_31.inputs[1])
    node_tree.links.new(setpos_11.outputs["Geometry"], bool_31.inputs[1])
    node_tree.links.new(setpos_16.outputs["Geometry"], bool_31.inputs[1])
    node_tree.links.new(setpos_21.outputs["Geometry"], bool_31.inputs[1])
    node_tree.links.new(prim_23.outputs["Mesh"], bool_31.inputs[1])
    node_tree.links.new(setpos_29.outputs["Geometry"], bool_31.inputs[1])
    out_32 = node_tree.nodes.new("NodeGroupOutput")
    out_32.location = (3900, 0)
    out_32.label = "output"
    node_tree.links.new(bool_31.outputs[0], out_32.inputs[0])

    return node_tree





# Execute all parts
setup_openbuilds_2040_camera_carriage()
