import bpy
import os


def setup_film_slider_2(object_name='film_slider_2'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (0, 280)
    vec_2.label = "slider size"
    vec_2.vector = [82, 45, 5]
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 0)
    prim_1.label = 'slider'
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (300, 280)
    vec_4.label = 'slider position offset'
    vec_4.vector = [0, 0, -5]
    setpos_3 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_3.location = (300, 0)
    setpos_3.label = 'slider position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_3.inputs["Geometry"])
    node_tree.links.new(vec_4.outputs["Vector"], setpos_3.inputs["Offset"])
    bool_5 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_5.location = (600, 0)
    bool_5.label = 'union'
    bool_5.operation = "UNION"
    try:
        bool_5.solver = "EXACT"
    except (TypeError, ValueError):
        bool_5.solver = "EXACT"
    node_tree.links.new(setpos_3.outputs["Geometry"], bool_5.inputs[1])
    vec_7 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_7.location = (900, 280)
    vec_7.label = "h_slider size"
    vec_7.vector = [40, 34.5, 100]
    prim_6 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_6.location = (900, 0)
    prim_6.label = 'h_slider'
    node_tree.links.new(vec_7.outputs["Vector"], prim_6.inputs["Size"])
    vec_9 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_9.location = (1200, 280)
    vec_9.label = "h_sprocket_gear size"
    vec_9.vector = [15, 5, 10]
    prim_8 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_8.location = (1200, 0)
    prim_8.label = 'h_sprocket_gear'
    node_tree.links.new(vec_9.outputs["Vector"], prim_8.inputs["Size"])
    vec_11 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_11.location = (1500, 280)
    vec_11.label = 'h_sprocket_gear position offset'
    vec_11.vector = [30, 14.0845, -5]
    setpos_10 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_10.location = (1500, 0)
    setpos_10.label = 'h_sprocket_gear position'
    node_tree.links.new(prim_8.outputs["Mesh"], setpos_10.inputs["Geometry"])
    node_tree.links.new(vec_11.outputs["Vector"], setpos_10.inputs["Offset"])
    vec_13 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_13.location = (1800, 280)
    vec_13.label = "h_sprocket_gear size"
    vec_13.vector = [15, 5, 10]
    prim_12 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_12.location = (1800, 0)
    prim_12.label = 'h_sprocket_gear'
    node_tree.links.new(vec_13.outputs["Vector"], prim_12.inputs["Size"])
    vec_15 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_15.location = (2100, 280)
    vec_15.label = 'h_sprocket_gear position offset'
    vec_15.vector = [30, -14.0845, -5]
    setpos_14 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_14.location = (2100, 0)
    setpos_14.label = 'h_sprocket_gear position'
    node_tree.links.new(prim_12.outputs["Mesh"], setpos_14.inputs["Geometry"])
    node_tree.links.new(vec_15.outputs["Vector"], setpos_14.inputs["Offset"])
    val_17 = node_tree.nodes.new("ShaderNodeValue")
    val_17.location = (2400, 280)
    val_17.label = 'h_sprocket_col radius'
    val_17.outputs[0].default_value = 1.5
    val_18 = node_tree.nodes.new("ShaderNodeValue")
    val_18.location = (2400, 560)
    val_18.label = 'h_sprocket_col depth'
    val_18.outputs[0].default_value = 60
    prim_16 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_16.location = (2400, 0)
    prim_16.label = 'h_sprocket_col'
    node_tree.links.new(val_17.outputs["Value"], prim_16.inputs["Radius"])
    node_tree.links.new(val_18.outputs["Value"], prim_16.inputs["Depth"])
    prim_16.inputs["Vertices"].default_value = 32
    vec_20 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_20.location = (2700, 280)
    vec_20.label = 'h_sprocket_col rotate rotation'
    vec_20.vector = [1.5707963267948966, 0.0, 0.0]
    xform_19 = node_tree.nodes.new("GeometryNodeTransform")
    xform_19.location = (2700, 0)
    xform_19.label = 'h_sprocket_col rotate'
    node_tree.links.new(prim_16.outputs["Mesh"], xform_19.inputs["Geometry"])
    node_tree.links.new(vec_20.outputs["Vector"], xform_19.inputs["Rotation"])
    vec_22 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_22.location = (3000, 280)
    vec_22.label = 'h_sprocket_col rotate position offset'
    vec_22.vector = [30, 0, -7.5]
    setpos_21 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_21.location = (3000, 0)
    setpos_21.label = 'h_sprocket_col rotate position'
    node_tree.links.new(xform_19.outputs["Geometry"], setpos_21.inputs["Geometry"])
    node_tree.links.new(vec_22.outputs["Vector"], setpos_21.inputs["Offset"])
    bool_23 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_23.location = (3300, 0)
    bool_23.label = 'difference'
    bool_23.operation = "DIFFERENCE"
    try:
        bool_23.solver = "EXACT"
    except (TypeError, ValueError):
        bool_23.solver = "EXACT"
    node_tree.links.new(bool_5.outputs["Mesh"], bool_23.inputs[0])
    node_tree.links.new(prim_6.outputs["Mesh"], bool_23.inputs[1])
    node_tree.links.new(setpos_10.outputs["Geometry"], bool_23.inputs[1])
    node_tree.links.new(setpos_14.outputs["Geometry"], bool_23.inputs[1])
    node_tree.links.new(setpos_21.outputs["Geometry"], bool_23.inputs[1])
    val_25 = node_tree.nodes.new("ShaderNodeValue")
    val_25.location = (3600, 280)
    val_25.label = 'h_sprocket_col_base_1 radius'
    val_25.outputs[0].default_value = 4.5
    val_26 = node_tree.nodes.new("ShaderNodeValue")
    val_26.location = (3600, 560)
    val_26.label = 'h_sprocket_col_base_1 depth'
    val_26.outputs[0].default_value = 3
    prim_24 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_24.location = (3600, 0)
    prim_24.label = 'h_sprocket_col_base_1'
    node_tree.links.new(val_25.outputs["Value"], prim_24.inputs["Radius"])
    node_tree.links.new(val_26.outputs["Value"], prim_24.inputs["Depth"])
    prim_24.inputs["Vertices"].default_value = 10
    vec_28 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_28.location = (3900, 280)
    vec_28.label = 'h_sprocket_col_base_1 rotate rotation'
    vec_28.vector = [1.5707963267948966, 0.0, 0.0]
    xform_27 = node_tree.nodes.new("GeometryNodeTransform")
    xform_27.location = (3900, 0)
    xform_27.label = 'h_sprocket_col_base_1 rotate'
    node_tree.links.new(prim_24.outputs["Mesh"], xform_27.inputs["Geometry"])
    node_tree.links.new(vec_28.outputs["Vector"], xform_27.inputs["Rotation"])
    vec_30 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_30.location = (4200, 280)
    vec_30.label = 'h_sprocket_col_base_1 rotate position offset'
    vec_30.vector = [30, 21.0, -7.5]
    setpos_29 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_29.location = (4200, 0)
    setpos_29.label = 'h_sprocket_col_base_1 rotate position'
    node_tree.links.new(xform_27.outputs["Geometry"], setpos_29.inputs["Geometry"])
    node_tree.links.new(vec_30.outputs["Vector"], setpos_29.inputs["Offset"])
    val_32 = node_tree.nodes.new("ShaderNodeValue")
    val_32.location = (4500, 280)
    val_32.label = 'h_sprocket_col_base_2 radius'
    val_32.outputs[0].default_value = 4.5
    val_33 = node_tree.nodes.new("ShaderNodeValue")
    val_33.location = (4500, 560)
    val_33.label = 'h_sprocket_col_base_2 depth'
    val_33.outputs[0].default_value = 3
    prim_31 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_31.location = (4500, 0)
    prim_31.label = 'h_sprocket_col_base_2'
    node_tree.links.new(val_32.outputs["Value"], prim_31.inputs["Radius"])
    node_tree.links.new(val_33.outputs["Value"], prim_31.inputs["Depth"])
    prim_31.inputs["Vertices"].default_value = 10
    vec_35 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_35.location = (4800, 280)
    vec_35.label = 'h_sprocket_col_base_2 rotate rotation'
    vec_35.vector = [1.5707963267948966, 0.0, 0.0]
    xform_34 = node_tree.nodes.new("GeometryNodeTransform")
    xform_34.location = (4800, 0)
    xform_34.label = 'h_sprocket_col_base_2 rotate'
    node_tree.links.new(prim_31.outputs["Mesh"], xform_34.inputs["Geometry"])
    node_tree.links.new(vec_35.outputs["Vector"], xform_34.inputs["Rotation"])
    vec_37 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_37.location = (5100, 280)
    vec_37.label = 'h_sprocket_col_base_2 rotate position offset'
    vec_37.vector = [30, -21.0, -7.5]
    setpos_36 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_36.location = (5100, 0)
    setpos_36.label = 'h_sprocket_col_base_2 rotate position'
    node_tree.links.new(xform_34.outputs["Geometry"], setpos_36.inputs["Geometry"])
    node_tree.links.new(vec_37.outputs["Vector"], setpos_36.inputs["Offset"])
    bool_38 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_38.location = (5400, 0)
    bool_38.label = 'union'
    bool_38.operation = "UNION"
    try:
        bool_38.solver = "EXACT"
    except (TypeError, ValueError):
        bool_38.solver = "EXACT"
    node_tree.links.new(setpos_29.outputs["Geometry"], bool_38.inputs[1])
    node_tree.links.new(setpos_36.outputs["Geometry"], bool_38.inputs[1])
    val_40 = node_tree.nodes.new("ShaderNodeValue")
    val_40.location = (5700, 280)
    val_40.label = 'h_sprocket_col_base radius'
    val_40.outputs[0].default_value = 2.25
    val_41 = node_tree.nodes.new("ShaderNodeValue")
    val_41.location = (5700, 560)
    val_41.label = 'h_sprocket_col_base depth'
    val_41.outputs[0].default_value = 43
    prim_39 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_39.location = (5700, 0)
    prim_39.label = 'h_sprocket_col_base'
    node_tree.links.new(val_40.outputs["Value"], prim_39.inputs["Radius"])
    node_tree.links.new(val_41.outputs["Value"], prim_39.inputs["Depth"])
    prim_39.inputs["Vertices"].default_value = 32
    vec_43 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_43.location = (6000, 280)
    vec_43.label = 'h_sprocket_col_base rotate rotation'
    vec_43.vector = [1.5707963267948966, 0.0, 0.0]
    xform_42 = node_tree.nodes.new("GeometryNodeTransform")
    xform_42.location = (6000, 0)
    xform_42.label = 'h_sprocket_col_base rotate'
    node_tree.links.new(prim_39.outputs["Mesh"], xform_42.inputs["Geometry"])
    node_tree.links.new(vec_43.outputs["Vector"], xform_42.inputs["Rotation"])
    vec_45 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_45.location = (6300, 280)
    vec_45.label = 'h_sprocket_col_base rotate position offset'
    vec_45.vector = [30, 0, -7.5]
    setpos_44 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_44.location = (6300, 0)
    setpos_44.label = 'h_sprocket_col_base rotate position'
    node_tree.links.new(xform_42.outputs["Geometry"], setpos_44.inputs["Geometry"])
    node_tree.links.new(vec_45.outputs["Vector"], setpos_44.inputs["Offset"])
    bool_46 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_46.location = (6600, 0)
    bool_46.label = 'difference'
    bool_46.operation = "DIFFERENCE"
    try:
        bool_46.solver = "EXACT"
    except (TypeError, ValueError):
        bool_46.solver = "EXACT"
    node_tree.links.new(bool_38.outputs["Mesh"], bool_46.inputs[0])
    node_tree.links.new(setpos_44.outputs["Geometry"], bool_46.inputs[1])
    bool_47 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_47.location = (6900, 0)
    bool_47.label = 'union'
    bool_47.operation = "UNION"
    try:
        bool_47.solver = "EXACT"
    except (TypeError, ValueError):
        bool_47.solver = "EXACT"
    node_tree.links.new(bool_23.outputs["Mesh"], bool_47.inputs[1])
    node_tree.links.new(bool_46.outputs["Mesh"], bool_47.inputs[1])
    vec_49 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_49.location = (7200, 280)
    vec_49.label = "join_1 size"
    vec_49.vector = [80.125, 3.125, 3.25]
    prim_48 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_48.location = (7200, 0)
    prim_48.label = 'join_1'
    node_tree.links.new(vec_49.outputs["Vector"], prim_48.inputs["Size"])
    vec_51 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_51.location = (7500, 280)
    vec_51.label = 'join_1 position offset'
    vec_51.vector = [0, 19.0625, -4]
    setpos_50 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_50.location = (7500, 0)
    setpos_50.label = 'join_1 position'
    node_tree.links.new(prim_48.outputs["Mesh"], setpos_50.inputs["Geometry"])
    node_tree.links.new(vec_51.outputs["Vector"], setpos_50.inputs["Offset"])
    vec_53 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_53.location = (7800, 280)
    vec_53.label = "join_1 size"
    vec_53.vector = [80.125, 3.125, 3.25]
    prim_52 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_52.location = (7800, 0)
    prim_52.label = 'join_1'
    node_tree.links.new(vec_53.outputs["Vector"], prim_52.inputs["Size"])
    vec_55 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_55.location = (8100, 280)
    vec_55.label = 'join_1 position offset'
    vec_55.vector = [0, -19.0625, -4]
    setpos_54 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_54.location = (8100, 0)
    setpos_54.label = 'join_1 position'
    node_tree.links.new(prim_52.outputs["Mesh"], setpos_54.inputs["Geometry"])
    node_tree.links.new(vec_55.outputs["Vector"], setpos_54.inputs["Offset"])
    vec_57 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_57.location = (8400, 280)
    vec_57.label = "recess angle size"
    vec_57.vector = [35, 34.5, 35]
    prim_56 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_56.location = (8400, 0)
    prim_56.label = 'recess angle'
    node_tree.links.new(vec_57.outputs["Vector"], prim_56.inputs["Size"])
    vec_59 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_59.location = (8700, 280)
    vec_59.label = 'recess angle rotate rotation'
    vec_59.vector = [0.0, 0.7853981633974483, 0.0]
    xform_58 = node_tree.nodes.new("GeometryNodeTransform")
    xform_58.location = (8700, 0)
    xform_58.label = 'recess angle rotate'
    node_tree.links.new(prim_56.outputs["Mesh"], xform_58.inputs["Geometry"])
    node_tree.links.new(vec_59.outputs["Vector"], xform_58.inputs["Rotation"])
    bool_60 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_60.location = (9000, 0)
    bool_60.label = 'difference'
    bool_60.operation = "DIFFERENCE"
    try:
        bool_60.solver = "EXACT"
    except (TypeError, ValueError):
        bool_60.solver = "EXACT"
    node_tree.links.new(bool_47.outputs["Mesh"], bool_60.inputs[0])
    node_tree.links.new(setpos_50.outputs["Geometry"], bool_60.inputs[1])
    node_tree.links.new(setpos_54.outputs["Geometry"], bool_60.inputs[1])
    node_tree.links.new(xform_58.outputs["Geometry"], bool_60.inputs[1])
    vec_62 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_62.location = (9300, 280)
    vec_62.label = 'difference translate translation'
    vec_62.vector = [0, 0, -3]
    xform_61 = node_tree.nodes.new("GeometryNodeTransform")
    xform_61.location = (9300, 0)
    xform_61.label = 'difference translate'
    node_tree.links.new(bool_60.outputs["Mesh"], xform_61.inputs["Geometry"])
    node_tree.links.new(vec_62.outputs["Vector"], xform_61.inputs["Translation"])
    out_63 = node_tree.nodes.new("NodeGroupOutput")
    out_63.location = (9600, 0)
    out_63.label = "output"
    node_tree.links.new(xform_61.outputs[0], out_63.inputs[0])

    return node_tree





# Execute all parts
setup_film_slider_2()
