import bpy


def setup_dslr_scanner_setup(object_name='dslr_scanner_setup'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (0, 280)
    vec_2.label = "base size"
    vec_2.vector = [60, 80, 7]
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 0)
    prim_1.label = 'base'
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (300, 280)
    vec_4.label = "base_support size"
    vec_4.vector = [80, 15, 7]
    prim_3 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_3.location = (300, 0)
    prim_3.label = 'base_support'
    node_tree.links.new(vec_4.outputs["Vector"], prim_3.inputs["Size"])
    vec_6 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_6.location = (600, 280)
    vec_6.label = 'base_support translate translation'
    vec_6.vector = [0, 32.5, 0]
    xform_5 = node_tree.nodes.new("GeometryNodeTransform")
    xform_5.location = (600, 0)
    xform_5.label = 'base_support translate'
    node_tree.links.new(prim_3.outputs["Mesh"], xform_5.inputs["Geometry"])
    node_tree.links.new(vec_6.outputs["Vector"], xform_5.inputs["Translation"])
    vec_8 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_8.location = (900, 280)
    vec_8.label = "base_support size"
    vec_8.vector = [80, 15, 7]
    prim_7 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_7.location = (900, 0)
    prim_7.label = 'base_support'
    node_tree.links.new(vec_8.outputs["Vector"], prim_7.inputs["Size"])
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (1200, 280)
    vec_10.label = 'base_support translate translation'
    vec_10.vector = [0, -32.5, 0]
    xform_9 = node_tree.nodes.new("GeometryNodeTransform")
    xform_9.location = (1200, 0)
    xform_9.label = 'base_support translate'
    node_tree.links.new(prim_7.outputs["Mesh"], xform_9.inputs["Geometry"])
    node_tree.links.new(vec_10.outputs["Vector"], xform_9.inputs["Translation"])
    vec_12 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_12.location = (1500, 280)
    vec_12.label = "base_support_tube_1 size"
    vec_12.vector = [10, 15, 15]
    prim_11 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_11.location = (1500, 0)
    prim_11.label = 'base_support_tube_1'
    node_tree.links.new(vec_12.outputs["Vector"], prim_11.inputs["Size"])
    vec_14 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_14.location = (1800, 280)
    vec_14.label = 'base_support_tube_1 translate translation'
    vec_14.vector = [35, 32.5, 10]
    xform_13 = node_tree.nodes.new("GeometryNodeTransform")
    xform_13.location = (1800, 0)
    xform_13.label = 'base_support_tube_1 translate'
    node_tree.links.new(prim_11.outputs["Mesh"], xform_13.inputs["Geometry"])
    node_tree.links.new(vec_14.outputs["Vector"], xform_13.inputs["Translation"])
    vec_16 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_16.location = (2100, 280)
    vec_16.label = "base_support_tube_1 size"
    vec_16.vector = [10, 15, 15]
    prim_15 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_15.location = (2100, 0)
    prim_15.label = 'base_support_tube_1'
    node_tree.links.new(vec_16.outputs["Vector"], prim_15.inputs["Size"])
    vec_18 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_18.location = (2400, 280)
    vec_18.label = 'base_support_tube_1 translate translation'
    vec_18.vector = [-35, -32.5, 10]
    xform_17 = node_tree.nodes.new("GeometryNodeTransform")
    xform_17.location = (2400, 0)
    xform_17.label = 'base_support_tube_1 translate'
    node_tree.links.new(prim_15.outputs["Mesh"], xform_17.inputs["Geometry"])
    node_tree.links.new(vec_18.outputs["Vector"], xform_17.inputs["Translation"])
    vec_20 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_20.location = (2700, 280)
    vec_20.label = "base_support_tube_1 size"
    vec_20.vector = [10, 15, 15]
    prim_19 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_19.location = (2700, 0)
    prim_19.label = 'base_support_tube_1'
    node_tree.links.new(vec_20.outputs["Vector"], prim_19.inputs["Size"])
    vec_22 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_22.location = (3000, 280)
    vec_22.label = 'base_support_tube_1 translate translation'
    vec_22.vector = [35, -32.5, 10]
    xform_21 = node_tree.nodes.new("GeometryNodeTransform")
    xform_21.location = (3000, 0)
    xform_21.label = 'base_support_tube_1 translate'
    node_tree.links.new(prim_19.outputs["Mesh"], xform_21.inputs["Geometry"])
    node_tree.links.new(vec_22.outputs["Vector"], xform_21.inputs["Translation"])
    vec_24 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_24.location = (3300, 280)
    vec_24.label = "base_support_tube_1 size"
    vec_24.vector = [10, 15, 15]
    prim_23 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_23.location = (3300, 0)
    prim_23.label = 'base_support_tube_1'
    node_tree.links.new(vec_24.outputs["Vector"], prim_23.inputs["Size"])
    vec_26 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_26.location = (3600, 280)
    vec_26.label = 'base_support_tube_1 translate translation'
    vec_26.vector = [-35, 32.5, 10]
    xform_25 = node_tree.nodes.new("GeometryNodeTransform")
    xform_25.location = (3600, 0)
    xform_25.label = 'base_support_tube_1 translate'
    node_tree.links.new(prim_23.outputs["Mesh"], xform_25.inputs["Geometry"])
    node_tree.links.new(vec_26.outputs["Vector"], xform_25.inputs["Translation"])
    bool_27 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_27.location = (3900, 0)
    bool_27.label = 'union'
    bool_27.operation = "UNION"
    try:
        bool_27.solver = "EXACT"
    except (TypeError, ValueError):
        bool_27.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_27.inputs[1])
    node_tree.links.new(xform_5.outputs["Geometry"], bool_27.inputs[1])
    node_tree.links.new(xform_9.outputs["Geometry"], bool_27.inputs[1])
    node_tree.links.new(xform_13.outputs["Geometry"], bool_27.inputs[1])
    node_tree.links.new(xform_17.outputs["Geometry"], bool_27.inputs[1])
    node_tree.links.new(xform_21.outputs["Geometry"], bool_27.inputs[1])
    node_tree.links.new(xform_25.outputs["Geometry"], bool_27.inputs[1])
    vec_29 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_29.location = (4200, 280)
    vec_29.label = "h_base_1 size"
    vec_29.vector = [50.125, 55.125, 5.125]
    prim_28 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_28.location = (4200, 0)
    prim_28.label = 'h_base_1'
    node_tree.links.new(vec_29.outputs["Vector"], prim_28.inputs["Size"])
    vec_31 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_31.location = (4500, 280)
    vec_31.label = 'h_base_1 translate translation'
    vec_31.vector = [0, 0, 1]
    xform_30 = node_tree.nodes.new("GeometryNodeTransform")
    xform_30.location = (4500, 0)
    xform_30.label = 'h_base_1 translate'
    node_tree.links.new(prim_28.outputs["Mesh"], xform_30.inputs["Geometry"])
    node_tree.links.new(vec_31.outputs["Vector"], xform_30.inputs["Translation"])
    val_33 = node_tree.nodes.new("ShaderNodeValue")
    val_33.location = (4800, 280)
    val_33.label = 'h_base_support_tube_1 radius'
    val_33.outputs[0].default_value = 5.175
    val_34 = node_tree.nodes.new("ShaderNodeValue")
    val_34.location = (4800, 560)
    val_34.label = 'h_base_support_tube_1 depth'
    val_34.outputs[0].default_value = 160
    prim_32 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_32.location = (4800, 0)
    prim_32.label = 'h_base_support_tube_1'
    node_tree.links.new(val_33.outputs["Value"], prim_32.inputs["Radius"])
    node_tree.links.new(val_34.outputs["Value"], prim_32.inputs["Depth"])
    prim_32.inputs["Vertices"].default_value = 32
    vec_36 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_36.location = (5100, 280)
    vec_36.label = 'h_base_support_tube_1 rotate rotation'
    vec_36.vector = [0.0, 1.5707963267948966, 0.0]
    xform_35 = node_tree.nodes.new("GeometryNodeTransform")
    xform_35.location = (5100, 0)
    xform_35.label = 'h_base_support_tube_1 rotate'
    node_tree.links.new(prim_32.outputs["Mesh"], xform_35.inputs["Geometry"])
    node_tree.links.new(vec_36.outputs["Vector"], xform_35.inputs["Rotation"])
    vec_38 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_38.location = (5400, 280)
    vec_38.label = 'h_base_support_tube_1 rotate translate translation'
    vec_38.vector = [0, 32.5, 10.5]
    xform_37 = node_tree.nodes.new("GeometryNodeTransform")
    xform_37.location = (5400, 0)
    xform_37.label = 'h_base_support_tube_1 rotate translate'
    node_tree.links.new(xform_35.outputs["Geometry"], xform_37.inputs["Geometry"])
    node_tree.links.new(vec_38.outputs["Vector"], xform_37.inputs["Translation"])
    val_40 = node_tree.nodes.new("ShaderNodeValue")
    val_40.location = (5700, 280)
    val_40.label = 'h_base_support_tube_1 radius'
    val_40.outputs[0].default_value = 5.175
    val_41 = node_tree.nodes.new("ShaderNodeValue")
    val_41.location = (5700, 560)
    val_41.label = 'h_base_support_tube_1 depth'
    val_41.outputs[0].default_value = 160
    prim_39 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_39.location = (5700, 0)
    prim_39.label = 'h_base_support_tube_1'
    node_tree.links.new(val_40.outputs["Value"], prim_39.inputs["Radius"])
    node_tree.links.new(val_41.outputs["Value"], prim_39.inputs["Depth"])
    prim_39.inputs["Vertices"].default_value = 32
    vec_43 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_43.location = (6000, 280)
    vec_43.label = 'h_base_support_tube_1 rotate rotation'
    vec_43.vector = [0.0, 1.5707963267948966, 0.0]
    xform_42 = node_tree.nodes.new("GeometryNodeTransform")
    xform_42.location = (6000, 0)
    xform_42.label = 'h_base_support_tube_1 rotate'
    node_tree.links.new(prim_39.outputs["Mesh"], xform_42.inputs["Geometry"])
    node_tree.links.new(vec_43.outputs["Vector"], xform_42.inputs["Rotation"])
    vec_45 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_45.location = (6300, 280)
    vec_45.label = 'h_base_support_tube_1 rotate translate translation'
    vec_45.vector = [0, -32.5, 10.5]
    xform_44 = node_tree.nodes.new("GeometryNodeTransform")
    xform_44.location = (6300, 0)
    xform_44.label = 'h_base_support_tube_1 rotate translate'
    node_tree.links.new(xform_42.outputs["Geometry"], xform_44.inputs["Geometry"])
    node_tree.links.new(vec_45.outputs["Vector"], xform_44.inputs["Translation"])
    val_47 = node_tree.nodes.new("ShaderNodeValue")
    val_47.location = (6600, 280)
    val_47.label = 'h_base_support_tube_2 radius'
    val_47.outputs[0].default_value = 10
    val_48 = node_tree.nodes.new("ShaderNodeValue")
    val_48.location = (6600, 560)
    val_48.label = 'h_base_support_tube_2 depth'
    val_48.outputs[0].default_value = 15
    prim_46 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_46.location = (6600, 0)
    prim_46.label = 'h_base_support_tube_2'
    node_tree.links.new(val_47.outputs["Value"], prim_46.inputs["Radius"])
    node_tree.links.new(val_48.outputs["Value"], prim_46.inputs["Depth"])
    prim_46.inputs["Vertices"].default_value = 32
    bool_49 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_49.location = (6900, 0)
    bool_49.label = 'difference'
    bool_49.operation = "DIFFERENCE"
    try:
        bool_49.solver = "EXACT"
    except (TypeError, ValueError):
        bool_49.solver = "EXACT"
    node_tree.links.new(bool_27.outputs["Mesh"], bool_49.inputs[0])
    node_tree.links.new(xform_30.outputs["Geometry"], bool_49.inputs[1])
    node_tree.links.new(xform_37.outputs["Geometry"], bool_49.inputs[1])
    node_tree.links.new(xform_44.outputs["Geometry"], bool_49.inputs[1])
    node_tree.links.new(prim_46.outputs["Mesh"], bool_49.inputs[1])
    out_50 = node_tree.nodes.new("NodeGroupOutput")
    out_50.location = (7200, 0)
    out_50.label = "output"
    node_tree.links.new(bool_49.outputs[0], out_50.inputs[0])

    return node_tree




def setup_cam_mount(object_name='cam_mount'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (0, 280)
    vec_2.label = "base size"
    vec_2.vector = [20, 80, 7]
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 0)
    prim_1.label = 'base'
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (300, 280)
    vec_4.label = "base_support_tube_1 size"
    vec_4.vector = [10, 15, 15]
    prim_3 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_3.location = (300, 0)
    prim_3.label = 'base_support_tube_1'
    node_tree.links.new(vec_4.outputs["Vector"], prim_3.inputs["Size"])
    vec_6 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_6.location = (600, 280)
    vec_6.label = 'base_support_tube_1 translate translation'
    vec_6.vector = [0, 32.5, 10]
    xform_5 = node_tree.nodes.new("GeometryNodeTransform")
    xform_5.location = (600, 0)
    xform_5.label = 'base_support_tube_1 translate'
    node_tree.links.new(prim_3.outputs["Mesh"], xform_5.inputs["Geometry"])
    node_tree.links.new(vec_6.outputs["Vector"], xform_5.inputs["Translation"])
    vec_8 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_8.location = (900, 280)
    vec_8.label = "base_support_tube_1 size"
    vec_8.vector = [10, 15, 15]
    prim_7 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_7.location = (900, 0)
    prim_7.label = 'base_support_tube_1'
    node_tree.links.new(vec_8.outputs["Vector"], prim_7.inputs["Size"])
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (1200, 280)
    vec_10.label = 'base_support_tube_1 translate translation'
    vec_10.vector = [0, -32.5, 10]
    xform_9 = node_tree.nodes.new("GeometryNodeTransform")
    xform_9.location = (1200, 0)
    xform_9.label = 'base_support_tube_1 translate'
    node_tree.links.new(prim_7.outputs["Mesh"], xform_9.inputs["Geometry"])
    node_tree.links.new(vec_10.outputs["Vector"], xform_9.inputs["Translation"])
    vec_12 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_12.location = (1500, 280)
    vec_12.label = "base_support_tube_2 size"
    vec_12.vector = [20, 20, 50]
    prim_11 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_11.location = (1500, 0)
    prim_11.label = 'base_support_tube_2'
    node_tree.links.new(vec_12.outputs["Vector"], prim_11.inputs["Size"])
    vec_14 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_14.location = (1800, 280)
    vec_14.label = 'base_support_tube_2 translate translation'
    vec_14.vector = [0, 0, 28.5]
    xform_13 = node_tree.nodes.new("GeometryNodeTransform")
    xform_13.location = (1800, 0)
    xform_13.label = 'base_support_tube_2 translate'
    node_tree.links.new(prim_11.outputs["Mesh"], xform_13.inputs["Geometry"])
    node_tree.links.new(vec_14.outputs["Vector"], xform_13.inputs["Translation"])
    bool_15 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_15.location = (2100, 0)
    bool_15.label = 'union'
    bool_15.operation = "UNION"
    try:
        bool_15.solver = "EXACT"
    except (TypeError, ValueError):
        bool_15.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_15.inputs[1])
    node_tree.links.new(xform_5.outputs["Geometry"], bool_15.inputs[1])
    node_tree.links.new(xform_9.outputs["Geometry"], bool_15.inputs[1])
    node_tree.links.new(xform_13.outputs["Geometry"], bool_15.inputs[1])
    val_17 = node_tree.nodes.new("ShaderNodeValue")
    val_17.location = (2400, 280)
    val_17.label = 'h_base_support_tube_1 radius'
    val_17.outputs[0].default_value = 5.175
    val_18 = node_tree.nodes.new("ShaderNodeValue")
    val_18.location = (2400, 560)
    val_18.label = 'h_base_support_tube_1 depth'
    val_18.outputs[0].default_value = 160
    prim_16 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_16.location = (2400, 0)
    prim_16.label = 'h_base_support_tube_1'
    node_tree.links.new(val_17.outputs["Value"], prim_16.inputs["Radius"])
    node_tree.links.new(val_18.outputs["Value"], prim_16.inputs["Depth"])
    prim_16.inputs["Vertices"].default_value = 32
    vec_20 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_20.location = (2700, 280)
    vec_20.label = 'h_base_support_tube_1 rotate rotation'
    vec_20.vector = [0.0, 1.5707963267948966, 0.0]
    xform_19 = node_tree.nodes.new("GeometryNodeTransform")
    xform_19.location = (2700, 0)
    xform_19.label = 'h_base_support_tube_1 rotate'
    node_tree.links.new(prim_16.outputs["Mesh"], xform_19.inputs["Geometry"])
    node_tree.links.new(vec_20.outputs["Vector"], xform_19.inputs["Rotation"])
    vec_22 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_22.location = (3000, 280)
    vec_22.label = 'h_base_support_tube_1 rotate translate translation'
    vec_22.vector = [0, 32.5, 10.5]
    xform_21 = node_tree.nodes.new("GeometryNodeTransform")
    xform_21.location = (3000, 0)
    xform_21.label = 'h_base_support_tube_1 rotate translate'
    node_tree.links.new(xform_19.outputs["Geometry"], xform_21.inputs["Geometry"])
    node_tree.links.new(vec_22.outputs["Vector"], xform_21.inputs["Translation"])
    val_24 = node_tree.nodes.new("ShaderNodeValue")
    val_24.location = (3300, 280)
    val_24.label = 'h_base_support_tube_1 radius'
    val_24.outputs[0].default_value = 5.175
    val_25 = node_tree.nodes.new("ShaderNodeValue")
    val_25.location = (3300, 560)
    val_25.label = 'h_base_support_tube_1 depth'
    val_25.outputs[0].default_value = 160
    prim_23 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_23.location = (3300, 0)
    prim_23.label = 'h_base_support_tube_1'
    node_tree.links.new(val_24.outputs["Value"], prim_23.inputs["Radius"])
    node_tree.links.new(val_25.outputs["Value"], prim_23.inputs["Depth"])
    prim_23.inputs["Vertices"].default_value = 32
    vec_27 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_27.location = (3600, 280)
    vec_27.label = 'h_base_support_tube_1 rotate rotation'
    vec_27.vector = [0.0, 1.5707963267948966, 0.0]
    xform_26 = node_tree.nodes.new("GeometryNodeTransform")
    xform_26.location = (3600, 0)
    xform_26.label = 'h_base_support_tube_1 rotate'
    node_tree.links.new(prim_23.outputs["Mesh"], xform_26.inputs["Geometry"])
    node_tree.links.new(vec_27.outputs["Vector"], xform_26.inputs["Rotation"])
    vec_29 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_29.location = (3900, 280)
    vec_29.label = 'h_base_support_tube_1 rotate translate translation'
    vec_29.vector = [0, -32.5, 10.5]
    xform_28 = node_tree.nodes.new("GeometryNodeTransform")
    xform_28.location = (3900, 0)
    xform_28.label = 'h_base_support_tube_1 rotate translate'
    node_tree.links.new(xform_26.outputs["Geometry"], xform_28.inputs["Geometry"])
    node_tree.links.new(vec_29.outputs["Vector"], xform_28.inputs["Translation"])
    val_31 = node_tree.nodes.new("ShaderNodeValue")
    val_31.location = (4200, 280)
    val_31.label = 'h_base_support_tube_2 radius'
    val_31.outputs[0].default_value = 4
    val_32 = node_tree.nodes.new("ShaderNodeValue")
    val_32.location = (4200, 560)
    val_32.label = 'h_base_support_tube_2 depth'
    val_32.outputs[0].default_value = 100
    prim_30 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_30.location = (4200, 0)
    prim_30.label = 'h_base_support_tube_2'
    node_tree.links.new(val_31.outputs["Value"], prim_30.inputs["Radius"])
    node_tree.links.new(val_32.outputs["Value"], prim_30.inputs["Depth"])
    prim_30.inputs["Vertices"].default_value = 32
    vec_34 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_34.location = (4500, 280)
    vec_34.label = 'h_base_support_tube_2 translate translation'
    vec_34.vector = [0, 0, 40]
    xform_33 = node_tree.nodes.new("GeometryNodeTransform")
    xform_33.location = (4500, 0)
    xform_33.label = 'h_base_support_tube_2 translate'
    node_tree.links.new(prim_30.outputs["Mesh"], xform_33.inputs["Geometry"])
    node_tree.links.new(vec_34.outputs["Vector"], xform_33.inputs["Translation"])
    val_36 = node_tree.nodes.new("ShaderNodeValue")
    val_36.location = (4800, 280)
    val_36.label = 'h_base_support_tube_3 radius'
    val_36.outputs[0].default_value = 7
    val_37 = node_tree.nodes.new("ShaderNodeValue")
    val_37.location = (4800, 560)
    val_37.label = 'h_base_support_tube_3 depth'
    val_37.outputs[0].default_value = 50
    prim_35 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_35.location = (4800, 0)
    prim_35.label = 'h_base_support_tube_3'
    node_tree.links.new(val_36.outputs["Value"], prim_35.inputs["Radius"])
    node_tree.links.new(val_37.outputs["Value"], prim_35.inputs["Depth"])
    prim_35.inputs["Vertices"].default_value = 32
    vec_39 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_39.location = (5100, 280)
    vec_39.label = 'h_base_support_tube_3 translate translation'
    vec_39.vector = [0, 0, -3]
    xform_38 = node_tree.nodes.new("GeometryNodeTransform")
    xform_38.location = (5100, 0)
    xform_38.label = 'h_base_support_tube_3 translate'
    node_tree.links.new(prim_35.outputs["Mesh"], xform_38.inputs["Geometry"])
    node_tree.links.new(vec_39.outputs["Vector"], xform_38.inputs["Translation"])
    bool_40 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_40.location = (5400, 0)
    bool_40.label = 'difference'
    bool_40.operation = "DIFFERENCE"
    try:
        bool_40.solver = "EXACT"
    except (TypeError, ValueError):
        bool_40.solver = "EXACT"
    node_tree.links.new(bool_15.outputs["Mesh"], bool_40.inputs[0])
    node_tree.links.new(xform_21.outputs["Geometry"], bool_40.inputs[1])
    node_tree.links.new(xform_28.outputs["Geometry"], bool_40.inputs[1])
    node_tree.links.new(xform_33.outputs["Geometry"], bool_40.inputs[1])
    node_tree.links.new(xform_38.outputs["Geometry"], bool_40.inputs[1])
    vec_42 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_42.location = (5700, 280)
    vec_42.label = 'difference translate translation'
    vec_42.vector = [-80, 0, 0]
    xform_41 = node_tree.nodes.new("GeometryNodeTransform")
    xform_41.location = (5700, 0)
    xform_41.label = 'difference translate'
    node_tree.links.new(bool_40.outputs["Mesh"], xform_41.inputs["Geometry"])
    node_tree.links.new(vec_42.outputs["Vector"], xform_41.inputs["Translation"])
    out_43 = node_tree.nodes.new("NodeGroupOutput")
    out_43.location = (6000, 0)
    out_43.label = "output"
    node_tree.links.new(xform_41.outputs[0], out_43.inputs[0])

    return node_tree




def setup_film_slider(object_name='film_slider'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (0, 280)
    vec_2.label = "slider_base size"
    vec_2.vector = [5, 80, 120]
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 0)
    prim_1.label = 'slider_base'
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (300, 280)
    vec_4.label = 'slider_base translate translation'
    vec_4.vector = [0, 0, 56.5]
    xform_3 = node_tree.nodes.new("GeometryNodeTransform")
    xform_3.location = (300, 0)
    xform_3.label = 'slider_base translate'
    node_tree.links.new(prim_1.outputs["Mesh"], xform_3.inputs["Geometry"])
    node_tree.links.new(vec_4.outputs["Vector"], xform_3.inputs["Translation"])
    vec_6 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_6.location = (600, 280)
    vec_6.label = "base size"
    vec_6.vector = [20, 80, 7]
    prim_5 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_5.location = (600, 0)
    prim_5.label = 'base'
    node_tree.links.new(vec_6.outputs["Vector"], prim_5.inputs["Size"])
    vec_8 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_8.location = (900, 280)
    vec_8.label = 'base translate translation'
    vec_8.vector = [10, 0, 0]
    xform_7 = node_tree.nodes.new("GeometryNodeTransform")
    xform_7.location = (900, 0)
    xform_7.label = 'base translate'
    node_tree.links.new(prim_5.outputs["Mesh"], xform_7.inputs["Geometry"])
    node_tree.links.new(vec_8.outputs["Vector"], xform_7.inputs["Translation"])
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (1200, 280)
    vec_10.label = "base_support_tube_1 size"
    vec_10.vector = [20, 15, 15]
    prim_9 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_9.location = (1200, 0)
    prim_9.label = 'base_support_tube_1'
    node_tree.links.new(vec_10.outputs["Vector"], prim_9.inputs["Size"])
    vec_12 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_12.location = (1500, 280)
    vec_12.label = 'base_support_tube_1 translate translation'
    vec_12.vector = [10, 32.5, 10]
    xform_11 = node_tree.nodes.new("GeometryNodeTransform")
    xform_11.location = (1500, 0)
    xform_11.label = 'base_support_tube_1 translate'
    node_tree.links.new(prim_9.outputs["Mesh"], xform_11.inputs["Geometry"])
    node_tree.links.new(vec_12.outputs["Vector"], xform_11.inputs["Translation"])
    vec_14 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_14.location = (1800, 280)
    vec_14.label = "base_support_tube_1 size"
    vec_14.vector = [20, 15, 15]
    prim_13 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_13.location = (1800, 0)
    prim_13.label = 'base_support_tube_1'
    node_tree.links.new(vec_14.outputs["Vector"], prim_13.inputs["Size"])
    vec_16 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_16.location = (2100, 280)
    vec_16.label = 'base_support_tube_1 translate translation'
    vec_16.vector = [10, -32.5, 10]
    xform_15 = node_tree.nodes.new("GeometryNodeTransform")
    xform_15.location = (2100, 0)
    xform_15.label = 'base_support_tube_1 translate'
    node_tree.links.new(prim_13.outputs["Mesh"], xform_15.inputs["Geometry"])
    node_tree.links.new(vec_16.outputs["Vector"], xform_15.inputs["Translation"])
    bool_17 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_17.location = (2400, 0)
    bool_17.label = 'union'
    bool_17.operation = "UNION"
    try:
        bool_17.solver = "EXACT"
    except (TypeError, ValueError):
        bool_17.solver = "EXACT"
    node_tree.links.new(xform_3.outputs["Geometry"], bool_17.inputs[1])
    node_tree.links.new(xform_7.outputs["Geometry"], bool_17.inputs[1])
    node_tree.links.new(xform_11.outputs["Geometry"], bool_17.inputs[1])
    node_tree.links.new(xform_15.outputs["Geometry"], bool_17.inputs[1])
    val_19 = node_tree.nodes.new("ShaderNodeValue")
    val_19.location = (2700, 280)
    val_19.label = 'column1 radius'
    val_19.outputs[0].default_value = 5.175
    val_20 = node_tree.nodes.new("ShaderNodeValue")
    val_20.location = (2700, 560)
    val_20.label = 'column1 depth'
    val_20.outputs[0].default_value = 100
    prim_18 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_18.location = (2700, 0)
    prim_18.label = 'column1'
    node_tree.links.new(val_19.outputs["Value"], prim_18.inputs["Radius"])
    node_tree.links.new(val_20.outputs["Value"], prim_18.inputs["Depth"])
    prim_18.inputs["Vertices"].default_value = 32
    vec_22 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_22.location = (3000, 280)
    vec_22.label = 'column1 rotate rotation'
    vec_22.vector = [0.0, 1.5707963267948966, 0.0]
    xform_21 = node_tree.nodes.new("GeometryNodeTransform")
    xform_21.location = (3000, 0)
    xform_21.label = 'column1 rotate'
    node_tree.links.new(prim_18.outputs["Mesh"], xform_21.inputs["Geometry"])
    node_tree.links.new(vec_22.outputs["Vector"], xform_21.inputs["Rotation"])
    vec_24 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_24.location = (3300, 280)
    vec_24.label = 'column1 rotate translate translation'
    vec_24.vector = [0, 32.5, 10.5]
    xform_23 = node_tree.nodes.new("GeometryNodeTransform")
    xform_23.location = (3300, 0)
    xform_23.label = 'column1 rotate translate'
    node_tree.links.new(xform_21.outputs["Geometry"], xform_23.inputs["Geometry"])
    node_tree.links.new(vec_24.outputs["Vector"], xform_23.inputs["Translation"])
    val_26 = node_tree.nodes.new("ShaderNodeValue")
    val_26.location = (3600, 280)
    val_26.label = 'column2 radius'
    val_26.outputs[0].default_value = 5.175
    val_27 = node_tree.nodes.new("ShaderNodeValue")
    val_27.location = (3600, 560)
    val_27.label = 'column2 depth'
    val_27.outputs[0].default_value = 100
    prim_25 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_25.location = (3600, 0)
    prim_25.label = 'column2'
    node_tree.links.new(val_26.outputs["Value"], prim_25.inputs["Radius"])
    node_tree.links.new(val_27.outputs["Value"], prim_25.inputs["Depth"])
    prim_25.inputs["Vertices"].default_value = 32
    vec_29 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_29.location = (3900, 280)
    vec_29.label = 'column2 rotate rotation'
    vec_29.vector = [0.0, 1.5707963267948966, 0.0]
    xform_28 = node_tree.nodes.new("GeometryNodeTransform")
    xform_28.location = (3900, 0)
    xform_28.label = 'column2 rotate'
    node_tree.links.new(prim_25.outputs["Mesh"], xform_28.inputs["Geometry"])
    node_tree.links.new(vec_29.outputs["Vector"], xform_28.inputs["Rotation"])
    vec_31 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_31.location = (4200, 280)
    vec_31.label = 'column2 rotate translate translation'
    vec_31.vector = [0, -32.5, 10.5]
    xform_30 = node_tree.nodes.new("GeometryNodeTransform")
    xform_30.location = (4200, 0)
    xform_30.label = 'column2 rotate translate'
    node_tree.links.new(xform_28.outputs["Geometry"], xform_30.inputs["Geometry"])
    node_tree.links.new(vec_31.outputs["Vector"], xform_30.inputs["Translation"])
    vec_33 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_33.location = (4500, 280)
    vec_33.label = "h_slider_1 size"
    vec_33.vector = [100, 40, 34.5]
    prim_32 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_32.location = (4500, 0)
    prim_32.label = 'h_slider_1'
    node_tree.links.new(vec_33.outputs["Vector"], prim_32.inputs["Size"])
    vec_35 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_35.location = (4800, 280)
    vec_35.label = 'h_slider_1 position offset'
    vec_35.vector = [-30, 0, 86.5]
    setpos_34 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_34.location = (4800, 0)
    setpos_34.label = 'h_slider_1 position'
    node_tree.links.new(prim_32.outputs["Mesh"], setpos_34.inputs["Geometry"])
    node_tree.links.new(vec_35.outputs["Vector"], setpos_34.inputs["Offset"])
    vec_37 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_37.location = (5100, 280)
    vec_37.label = "h_slider_2 size"
    vec_37.vector = [0.5, 120, 35.125]
    prim_36 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_36.location = (5100, 0)
    prim_36.label = 'h_slider_2'
    node_tree.links.new(vec_37.outputs["Vector"], prim_36.inputs["Size"])
    vec_39 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_39.location = (5400, 280)
    vec_39.label = 'h_slider_2 position offset'
    vec_39.vector = [2.25, 0, 86.5]
    setpos_38 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_38.location = (5400, 0)
    setpos_38.label = 'h_slider_2 position'
    node_tree.links.new(prim_36.outputs["Mesh"], setpos_38.inputs["Geometry"])
    node_tree.links.new(vec_39.outputs["Vector"], setpos_38.inputs["Offset"])
    vec_41 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_41.location = (5700, 280)
    vec_41.label = "h_slider_3 size"
    vec_41.vector = [40, 40, 34.5]
    prim_40 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_40.location = (5700, 0)
    prim_40.label = 'h_slider_3'
    node_tree.links.new(vec_41.outputs["Vector"], prim_40.inputs["Size"])
    vec_43 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_43.location = (6000, 280)
    vec_43.label = 'h_slider_3 rotate rotation'
    vec_43.vector = [0.0, 0.0, 0.7853981633974483]
    xform_42 = node_tree.nodes.new("GeometryNodeTransform")
    xform_42.location = (6000, 0)
    xform_42.label = 'h_slider_3 rotate'
    node_tree.links.new(prim_40.outputs["Mesh"], xform_42.inputs["Geometry"])
    node_tree.links.new(vec_43.outputs["Vector"], xform_42.inputs["Rotation"])
    vec_45 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_45.location = (6300, 280)
    vec_45.label = 'h_slider_3 rotate position offset'
    vec_45.vector = [5, 0, 86.5]
    setpos_44 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_44.location = (6300, 0)
    setpos_44.label = 'h_slider_3 rotate position'
    node_tree.links.new(xform_42.outputs["Geometry"], setpos_44.inputs["Geometry"])
    node_tree.links.new(vec_45.outputs["Vector"], setpos_44.inputs["Offset"])
    vec_47 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_47.location = (6600, 280)
    vec_47.label = "h_below size"
    vec_47.vector = [30, 30, 30]
    prim_46 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_46.location = (6600, 0)
    prim_46.label = 'h_below'
    node_tree.links.new(vec_47.outputs["Vector"], prim_46.inputs["Size"])
    vec_49 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_49.location = (6900, 280)
    vec_49.label = 'h_below rotate rotation'
    vec_49.vector = [0.7853981633974483, 0.0, 0.0]
    xform_48 = node_tree.nodes.new("GeometryNodeTransform")
    xform_48.location = (6900, 0)
    xform_48.label = 'h_below rotate'
    node_tree.links.new(prim_46.outputs["Mesh"], xform_48.inputs["Geometry"])
    node_tree.links.new(vec_49.outputs["Vector"], xform_48.inputs["Rotation"])
    vec_51 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_51.location = (7200, 280)
    vec_51.label = 'h_below rotate position offset'
    vec_51.vector = [0, 0, 40]
    setpos_50 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_50.location = (7200, 0)
    setpos_50.label = 'h_below rotate position'
    node_tree.links.new(xform_48.outputs["Geometry"], setpos_50.inputs["Geometry"])
    node_tree.links.new(vec_51.outputs["Vector"], setpos_50.inputs["Offset"])
    bool_52 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_52.location = (7500, 0)
    bool_52.label = 'difference'
    bool_52.operation = "DIFFERENCE"
    try:
        bool_52.solver = "EXACT"
    except (TypeError, ValueError):
        bool_52.solver = "EXACT"
    node_tree.links.new(bool_17.outputs["Mesh"], bool_52.inputs[0])
    node_tree.links.new(xform_23.outputs["Geometry"], bool_52.inputs[1])
    node_tree.links.new(xform_30.outputs["Geometry"], bool_52.inputs[1])
    node_tree.links.new(setpos_34.outputs["Geometry"], bool_52.inputs[1])
    node_tree.links.new(setpos_38.outputs["Geometry"], bool_52.inputs[1])
    node_tree.links.new(setpos_44.outputs["Geometry"], bool_52.inputs[1])
    node_tree.links.new(setpos_50.outputs["Geometry"], bool_52.inputs[1])
    vec_54 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_54.location = (7800, 280)
    vec_54.label = "join_1 size"
    vec_54.vector = [3, 40, 3]
    prim_53 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_53.location = (7800, 0)
    prim_53.label = 'join_1'
    node_tree.links.new(vec_54.outputs["Vector"], prim_53.inputs["Size"])
    vec_56 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_56.location = (8100, 280)
    vec_56.label = 'join_1 position offset'
    vec_56.vector = [4, 0, 106.5]
    setpos_55 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_55.location = (8100, 0)
    setpos_55.label = 'join_1 position'
    node_tree.links.new(prim_53.outputs["Mesh"], setpos_55.inputs["Geometry"])
    node_tree.links.new(vec_56.outputs["Vector"], setpos_55.inputs["Offset"])
    vec_58 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_58.location = (8400, 280)
    vec_58.label = "join_1 size"
    vec_58.vector = [3, 40, 3]
    prim_57 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_57.location = (8400, 0)
    prim_57.label = 'join_1'
    node_tree.links.new(vec_58.outputs["Vector"], prim_57.inputs["Size"])
    vec_60 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_60.location = (8700, 280)
    vec_60.label = 'join_1 position offset'
    vec_60.vector = [4, 0, 66.5]
    setpos_59 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_59.location = (8700, 0)
    setpos_59.label = 'join_1 position'
    node_tree.links.new(prim_57.outputs["Mesh"], setpos_59.inputs["Geometry"])
    node_tree.links.new(vec_60.outputs["Vector"], setpos_59.inputs["Offset"])
    bool_61 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_61.location = (9000, 0)
    bool_61.label = 'union'
    bool_61.operation = "UNION"
    try:
        bool_61.solver = "EXACT"
    except (TypeError, ValueError):
        bool_61.solver = "EXACT"
    node_tree.links.new(bool_52.outputs["Mesh"], bool_61.inputs[1])
    node_tree.links.new(setpos_55.outputs["Geometry"], bool_61.inputs[1])
    node_tree.links.new(setpos_59.outputs["Geometry"], bool_61.inputs[1])
    vec_63 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_63.location = (9300, 280)
    vec_63.label = 'union translate translation'
    vec_63.vector = [-200, 0, 0]
    xform_62 = node_tree.nodes.new("GeometryNodeTransform")
    xform_62.location = (9300, 0)
    xform_62.label = 'union translate'
    node_tree.links.new(bool_61.outputs["Mesh"], xform_62.inputs["Geometry"])
    node_tree.links.new(vec_63.outputs["Vector"], xform_62.inputs["Translation"])
    out_64 = node_tree.nodes.new("NodeGroupOutput")
    out_64.location = (9600, 0)
    out_64.label = "output"
    node_tree.links.new(xform_62.outputs[0], out_64.inputs[0])

    return node_tree




def setup_tube_support(object_name='tube_support'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (0, 280)
    val_2.label = 'tube_support radius'
    val_2.outputs[0].default_value = 35.0
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (0, 560)
    val_3.label = 'tube_support depth'
    val_3.outputs[0].default_value = 20
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 0)
    prim_1.label = 'tube_support'
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 32
    val_5 = node_tree.nodes.new("ShaderNodeValue")
    val_5.location = (300, 280)
    val_5.label = 'h_tube_support radius'
    val_5.outputs[0].default_value = 31.25
    val_6 = node_tree.nodes.new("ShaderNodeValue")
    val_6.location = (300, 560)
    val_6.label = 'h_tube_support depth'
    val_6.outputs[0].default_value = 20.25
    prim_4 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_4.location = (300, 0)
    prim_4.label = 'h_tube_support'
    node_tree.links.new(val_5.outputs["Value"], prim_4.inputs["Radius"])
    node_tree.links.new(val_6.outputs["Value"], prim_4.inputs["Depth"])
    prim_4.inputs["Vertices"].default_value = 32
    vec_8 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_8.location = (600, 280)
    vec_8.label = "h_cube size"
    vec_8.vector = [70, 70, 70]
    prim_7 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_7.location = (600, 0)
    prim_7.label = 'h_cube'
    node_tree.links.new(vec_8.outputs["Vector"], prim_7.inputs["Size"])
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (900, 280)
    vec_10.label = 'h_cube position offset'
    vec_10.vector = [-35, 0, 0]
    setpos_9 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_9.location = (900, 0)
    setpos_9.label = 'h_cube position'
    node_tree.links.new(prim_7.outputs["Mesh"], setpos_9.inputs["Geometry"])
    node_tree.links.new(vec_10.outputs["Vector"], setpos_9.inputs["Offset"])
    bool_11 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_11.location = (1200, 0)
    bool_11.label = 'difference'
    bool_11.operation = "DIFFERENCE"
    try:
        bool_11.solver = "EXACT"
    except (TypeError, ValueError):
        bool_11.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_11.inputs[0])
    node_tree.links.new(prim_4.outputs["Mesh"], bool_11.inputs[1])
    node_tree.links.new(setpos_9.outputs["Geometry"], bool_11.inputs[1])
    vec_13 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_13.location = (1500, 280)
    vec_13.label = 'difference rotate rotation'
    vec_13.vector = [0.0, 1.5707963267948966, 0.0]
    xform_12 = node_tree.nodes.new("GeometryNodeTransform")
    xform_12.location = (1500, 0)
    xform_12.label = 'difference rotate'
    node_tree.links.new(bool_11.outputs["Mesh"], xform_12.inputs["Geometry"])
    node_tree.links.new(vec_13.outputs["Vector"], xform_12.inputs["Rotation"])
    vec_15 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_15.location = (1800, 280)
    vec_15.label = 'difference rotate translate translation'
    vec_15.vector = [0, 0, 82]
    xform_14 = node_tree.nodes.new("GeometryNodeTransform")
    xform_14.location = (1800, 0)
    xform_14.label = 'difference rotate translate'
    node_tree.links.new(xform_12.outputs["Geometry"], xform_14.inputs["Geometry"])
    node_tree.links.new(vec_15.outputs["Vector"], xform_14.inputs["Translation"])
    vec_17 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_17.location = (2100, 280)
    vec_17.label = "base size"
    vec_17.vector = [20, 80, 7]
    prim_16 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_16.location = (2100, 0)
    prim_16.label = 'base'
    node_tree.links.new(vec_17.outputs["Vector"], prim_16.inputs["Size"])
    vec_19 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_19.location = (2400, 280)
    vec_19.label = "base_support_tube_1 size"
    vec_19.vector = [20, 15, 15]
    prim_18 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_18.location = (2400, 0)
    prim_18.label = 'base_support_tube_1'
    node_tree.links.new(vec_19.outputs["Vector"], prim_18.inputs["Size"])
    vec_21 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_21.location = (2700, 280)
    vec_21.label = 'base_support_tube_1 translate translation'
    vec_21.vector = [0, 32.5, 10]
    xform_20 = node_tree.nodes.new("GeometryNodeTransform")
    xform_20.location = (2700, 0)
    xform_20.label = 'base_support_tube_1 translate'
    node_tree.links.new(prim_18.outputs["Mesh"], xform_20.inputs["Geometry"])
    node_tree.links.new(vec_21.outputs["Vector"], xform_20.inputs["Translation"])
    vec_23 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_23.location = (3000, 280)
    vec_23.label = "base_support_tube_1 size"
    vec_23.vector = [20, 15, 15]
    prim_22 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_22.location = (3000, 0)
    prim_22.label = 'base_support_tube_1'
    node_tree.links.new(vec_23.outputs["Vector"], prim_22.inputs["Size"])
    vec_25 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_25.location = (3300, 280)
    vec_25.label = 'base_support_tube_1 translate translation'
    vec_25.vector = [0, -32.5, 10]
    xform_24 = node_tree.nodes.new("GeometryNodeTransform")
    xform_24.location = (3300, 0)
    xform_24.label = 'base_support_tube_1 translate'
    node_tree.links.new(prim_22.outputs["Mesh"], xform_24.inputs["Geometry"])
    node_tree.links.new(vec_25.outputs["Vector"], xform_24.inputs["Translation"])
    vec_27 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_27.location = (3600, 280)
    vec_27.label = "base_support_tube_2 size"
    vec_27.vector = [20, 20, 50]
    prim_26 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_26.location = (3600, 0)
    prim_26.label = 'base_support_tube_2'
    node_tree.links.new(vec_27.outputs["Vector"], prim_26.inputs["Size"])
    vec_29 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_29.location = (3900, 280)
    vec_29.label = 'base_support_tube_2 translate translation'
    vec_29.vector = [0, 0, 25]
    xform_28 = node_tree.nodes.new("GeometryNodeTransform")
    xform_28.location = (3900, 0)
    xform_28.label = 'base_support_tube_2 translate'
    node_tree.links.new(prim_26.outputs["Mesh"], xform_28.inputs["Geometry"])
    node_tree.links.new(vec_29.outputs["Vector"], xform_28.inputs["Translation"])
    bool_30 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_30.location = (4200, 0)
    bool_30.label = 'union'
    bool_30.operation = "UNION"
    try:
        bool_30.solver = "EXACT"
    except (TypeError, ValueError):
        bool_30.solver = "EXACT"
    node_tree.links.new(prim_16.outputs["Mesh"], bool_30.inputs[1])
    node_tree.links.new(xform_20.outputs["Geometry"], bool_30.inputs[1])
    node_tree.links.new(xform_24.outputs["Geometry"], bool_30.inputs[1])
    node_tree.links.new(xform_28.outputs["Geometry"], bool_30.inputs[1])
    val_32 = node_tree.nodes.new("ShaderNodeValue")
    val_32.location = (4500, 280)
    val_32.label = 'h_base_support_tube_1 radius'
    val_32.outputs[0].default_value = 5.175
    val_33 = node_tree.nodes.new("ShaderNodeValue")
    val_33.location = (4500, 560)
    val_33.label = 'h_base_support_tube_1 depth'
    val_33.outputs[0].default_value = 160
    prim_31 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_31.location = (4500, 0)
    prim_31.label = 'h_base_support_tube_1'
    node_tree.links.new(val_32.outputs["Value"], prim_31.inputs["Radius"])
    node_tree.links.new(val_33.outputs["Value"], prim_31.inputs["Depth"])
    prim_31.inputs["Vertices"].default_value = 32
    vec_35 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_35.location = (4800, 280)
    vec_35.label = 'h_base_support_tube_1 rotate rotation'
    vec_35.vector = [0.0, 1.5707963267948966, 0.0]
    xform_34 = node_tree.nodes.new("GeometryNodeTransform")
    xform_34.location = (4800, 0)
    xform_34.label = 'h_base_support_tube_1 rotate'
    node_tree.links.new(prim_31.outputs["Mesh"], xform_34.inputs["Geometry"])
    node_tree.links.new(vec_35.outputs["Vector"], xform_34.inputs["Rotation"])
    vec_37 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_37.location = (5100, 280)
    vec_37.label = 'h_base_support_tube_1 rotate translate translation'
    vec_37.vector = [0, 32.5, 10.5]
    xform_36 = node_tree.nodes.new("GeometryNodeTransform")
    xform_36.location = (5100, 0)
    xform_36.label = 'h_base_support_tube_1 rotate translate'
    node_tree.links.new(xform_34.outputs["Geometry"], xform_36.inputs["Geometry"])
    node_tree.links.new(vec_37.outputs["Vector"], xform_36.inputs["Translation"])
    val_39 = node_tree.nodes.new("ShaderNodeValue")
    val_39.location = (5400, 280)
    val_39.label = 'h_base_support_tube_1 radius'
    val_39.outputs[0].default_value = 5.175
    val_40 = node_tree.nodes.new("ShaderNodeValue")
    val_40.location = (5400, 560)
    val_40.label = 'h_base_support_tube_1 depth'
    val_40.outputs[0].default_value = 160
    prim_38 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_38.location = (5400, 0)
    prim_38.label = 'h_base_support_tube_1'
    node_tree.links.new(val_39.outputs["Value"], prim_38.inputs["Radius"])
    node_tree.links.new(val_40.outputs["Value"], prim_38.inputs["Depth"])
    prim_38.inputs["Vertices"].default_value = 32
    vec_42 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_42.location = (5700, 280)
    vec_42.label = 'h_base_support_tube_1 rotate rotation'
    vec_42.vector = [0.0, 1.5707963267948966, 0.0]
    xform_41 = node_tree.nodes.new("GeometryNodeTransform")
    xform_41.location = (5700, 0)
    xform_41.label = 'h_base_support_tube_1 rotate'
    node_tree.links.new(prim_38.outputs["Mesh"], xform_41.inputs["Geometry"])
    node_tree.links.new(vec_42.outputs["Vector"], xform_41.inputs["Rotation"])
    vec_44 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_44.location = (6000, 280)
    vec_44.label = 'h_base_support_tube_1 rotate translate translation'
    vec_44.vector = [0, -32.5, 10.5]
    xform_43 = node_tree.nodes.new("GeometryNodeTransform")
    xform_43.location = (6000, 0)
    xform_43.label = 'h_base_support_tube_1 rotate translate'
    node_tree.links.new(xform_41.outputs["Geometry"], xform_43.inputs["Geometry"])
    node_tree.links.new(vec_44.outputs["Vector"], xform_43.inputs["Translation"])
    bool_45 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_45.location = (6300, 0)
    bool_45.label = 'difference'
    bool_45.operation = "DIFFERENCE"
    try:
        bool_45.solver = "EXACT"
    except (TypeError, ValueError):
        bool_45.solver = "EXACT"
    node_tree.links.new(bool_30.outputs["Mesh"], bool_45.inputs[0])
    node_tree.links.new(xform_36.outputs["Geometry"], bool_45.inputs[1])
    node_tree.links.new(xform_43.outputs["Geometry"], bool_45.inputs[1])
    bool_46 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_46.location = (6600, 0)
    bool_46.label = 'union'
    bool_46.operation = "UNION"
    try:
        bool_46.solver = "EXACT"
    except (TypeError, ValueError):
        bool_46.solver = "EXACT"
    node_tree.links.new(xform_14.outputs["Geometry"], bool_46.inputs[1])
    node_tree.links.new(bool_45.outputs["Mesh"], bool_46.inputs[1])
    vec_48 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_48.location = (6900, 280)
    vec_48.label = 'union translate translation'
    vec_48.vector = [-150, 0, 0]
    xform_47 = node_tree.nodes.new("GeometryNodeTransform")
    xform_47.location = (6900, 0)
    xform_47.label = 'union translate'
    node_tree.links.new(bool_46.outputs["Mesh"], xform_47.inputs["Geometry"])
    node_tree.links.new(vec_48.outputs["Vector"], xform_47.inputs["Translation"])
    out_49 = node_tree.nodes.new("NodeGroupOutput")
    out_49.location = (7200, 0)
    out_49.label = "output"
    node_tree.links.new(xform_47.outputs[0], out_49.inputs[0])

    return node_tree




def setup_film_slider_2(object_name='film_slider_2'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (0, 280)
    vec_2.label = "slider size"
    vec_2.vector = [100, 45, 5]
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 0)
    prim_1.label = 'slider'
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (300, 280)
    vec_4.label = 'slider position offset'
    vec_4.vector = [0, 0, -5]
    setpos_3 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_3.location = (300, 0)
    setpos_3.label = 'slider position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_3.inputs["Geometry"])
    node_tree.links.new(vec_4.outputs["Vector"], setpos_3.inputs["Offset"])
    vec_6 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_6.location = (600, 280)
    vec_6.label = "h_slider size"
    vec_6.vector = [40, 34.5, 30]
    prim_5 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_5.location = (600, 0)
    prim_5.label = 'h_slider'
    node_tree.links.new(vec_6.outputs["Vector"], prim_5.inputs["Size"])
    vec_8 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_8.location = (900, 280)
    vec_8.label = "join_1 size"
    vec_8.vector = [40.125, 3.125, 3.125]
    prim_7 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_7.location = (900, 0)
    prim_7.label = 'join_1'
    node_tree.links.new(vec_8.outputs["Vector"], prim_7.inputs["Size"])
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (1200, 280)
    vec_10.label = 'join_1 position offset'
    vec_10.vector = [0, 20, -4]
    setpos_9 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_9.location = (1200, 0)
    setpos_9.label = 'join_1 position'
    node_tree.links.new(prim_7.outputs["Mesh"], setpos_9.inputs["Geometry"])
    node_tree.links.new(vec_10.outputs["Vector"], setpos_9.inputs["Offset"])
    vec_12 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_12.location = (1500, 280)
    vec_12.label = "join_1 size"
    vec_12.vector = [40.125, 3.125, 3.125]
    prim_11 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_11.location = (1500, 0)
    prim_11.label = 'join_1'
    node_tree.links.new(vec_12.outputs["Vector"], prim_11.inputs["Size"])
    vec_14 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_14.location = (1800, 280)
    vec_14.label = 'join_1 position offset'
    vec_14.vector = [0, -20, -4]
    setpos_13 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_13.location = (1800, 0)
    setpos_13.label = 'join_1 position'
    node_tree.links.new(prim_11.outputs["Mesh"], setpos_13.inputs["Geometry"])
    node_tree.links.new(vec_14.outputs["Vector"], setpos_13.inputs["Offset"])
    vec_16 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_16.location = (2100, 280)
    vec_16.label = "h_sprocket_gear size"
    vec_16.vector = [15, 5, 10]
    prim_15 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_15.location = (2100, 0)
    prim_15.label = 'h_sprocket_gear'
    node_tree.links.new(vec_16.outputs["Vector"], prim_15.inputs["Size"])
    vec_18 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_18.location = (2400, 280)
    vec_18.label = 'h_sprocket_gear position offset'
    vec_18.vector = [30, 14.0845, -5]
    setpos_17 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_17.location = (2400, 0)
    setpos_17.label = 'h_sprocket_gear position'
    node_tree.links.new(prim_15.outputs["Mesh"], setpos_17.inputs["Geometry"])
    node_tree.links.new(vec_18.outputs["Vector"], setpos_17.inputs["Offset"])
    vec_20 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_20.location = (2700, 280)
    vec_20.label = "h_sprocket_gear size"
    vec_20.vector = [15, 5, 10]
    prim_19 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_19.location = (2700, 0)
    prim_19.label = 'h_sprocket_gear'
    node_tree.links.new(vec_20.outputs["Vector"], prim_19.inputs["Size"])
    vec_22 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_22.location = (3000, 280)
    vec_22.label = 'h_sprocket_gear position offset'
    vec_22.vector = [30, -14.0845, -5]
    setpos_21 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_21.location = (3000, 0)
    setpos_21.label = 'h_sprocket_gear position'
    node_tree.links.new(prim_19.outputs["Mesh"], setpos_21.inputs["Geometry"])
    node_tree.links.new(vec_22.outputs["Vector"], setpos_21.inputs["Offset"])
    val_24 = node_tree.nodes.new("ShaderNodeValue")
    val_24.location = (3300, 280)
    val_24.label = 'h_sprocket_col radius'
    val_24.outputs[0].default_value = 4
    val_25 = node_tree.nodes.new("ShaderNodeValue")
    val_25.location = (3300, 560)
    val_25.label = 'h_sprocket_col depth'
    val_25.outputs[0].default_value = 60
    prim_23 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_23.location = (3300, 0)
    prim_23.label = 'h_sprocket_col'
    node_tree.links.new(val_24.outputs["Value"], prim_23.inputs["Radius"])
    node_tree.links.new(val_25.outputs["Value"], prim_23.inputs["Depth"])
    prim_23.inputs["Vertices"].default_value = 32
    vec_27 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_27.location = (3600, 280)
    vec_27.label = 'h_sprocket_col rotate rotation'
    vec_27.vector = [1.5707963267948966, 0.0, 0.0]
    xform_26 = node_tree.nodes.new("GeometryNodeTransform")
    xform_26.location = (3600, 0)
    xform_26.label = 'h_sprocket_col rotate'
    node_tree.links.new(prim_23.outputs["Mesh"], xform_26.inputs["Geometry"])
    node_tree.links.new(vec_27.outputs["Vector"], xform_26.inputs["Rotation"])
    vec_29 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_29.location = (3900, 280)
    vec_29.label = 'h_sprocket_col rotate position offset'
    vec_29.vector = [30, 0, -7.5]
    setpos_28 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_28.location = (3900, 0)
    setpos_28.label = 'h_sprocket_col rotate position'
    node_tree.links.new(xform_26.outputs["Geometry"], setpos_28.inputs["Geometry"])
    node_tree.links.new(vec_29.outputs["Vector"], setpos_28.inputs["Offset"])
    bool_30 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_30.location = (4200, 0)
    bool_30.label = 'difference'
    bool_30.operation = "DIFFERENCE"
    try:
        bool_30.solver = "EXACT"
    except (TypeError, ValueError):
        bool_30.solver = "EXACT"
    node_tree.links.new(setpos_3.outputs["Geometry"], bool_30.inputs[0])
    node_tree.links.new(prim_5.outputs["Mesh"], bool_30.inputs[1])
    node_tree.links.new(setpos_9.outputs["Geometry"], bool_30.inputs[1])
    node_tree.links.new(setpos_13.outputs["Geometry"], bool_30.inputs[1])
    node_tree.links.new(setpos_17.outputs["Geometry"], bool_30.inputs[1])
    node_tree.links.new(setpos_21.outputs["Geometry"], bool_30.inputs[1])
    node_tree.links.new(setpos_28.outputs["Geometry"], bool_30.inputs[1])
    val_32 = node_tree.nodes.new("ShaderNodeValue")
    val_32.location = (4500, 280)
    val_32.label = 'h_sprocket_col_base_1 radius'
    val_32.outputs[0].default_value = 4.5
    val_33 = node_tree.nodes.new("ShaderNodeValue")
    val_33.location = (4500, 560)
    val_33.label = 'h_sprocket_col_base_1 depth'
    val_33.outputs[0].default_value = 3
    prim_31 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_31.location = (4500, 0)
    prim_31.label = 'h_sprocket_col_base_1'
    node_tree.links.new(val_32.outputs["Value"], prim_31.inputs["Radius"])
    node_tree.links.new(val_33.outputs["Value"], prim_31.inputs["Depth"])
    prim_31.inputs["Vertices"].default_value = 10
    vec_35 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_35.location = (4800, 280)
    vec_35.label = 'h_sprocket_col_base_1 rotate rotation'
    vec_35.vector = [1.5707963267948966, 0.0, 0.0]
    xform_34 = node_tree.nodes.new("GeometryNodeTransform")
    xform_34.location = (4800, 0)
    xform_34.label = 'h_sprocket_col_base_1 rotate'
    node_tree.links.new(prim_31.outputs["Mesh"], xform_34.inputs["Geometry"])
    node_tree.links.new(vec_35.outputs["Vector"], xform_34.inputs["Rotation"])
    vec_37 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_37.location = (5100, 280)
    vec_37.label = 'h_sprocket_col_base_1 rotate position offset'
    vec_37.vector = [30, 21.0, -7.5]
    setpos_36 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_36.location = (5100, 0)
    setpos_36.label = 'h_sprocket_col_base_1 rotate position'
    node_tree.links.new(xform_34.outputs["Geometry"], setpos_36.inputs["Geometry"])
    node_tree.links.new(vec_37.outputs["Vector"], setpos_36.inputs["Offset"])
    val_39 = node_tree.nodes.new("ShaderNodeValue")
    val_39.location = (5400, 280)
    val_39.label = 'h_sprocket_col_base_2 radius'
    val_39.outputs[0].default_value = 4.5
    val_40 = node_tree.nodes.new("ShaderNodeValue")
    val_40.location = (5400, 560)
    val_40.label = 'h_sprocket_col_base_2 depth'
    val_40.outputs[0].default_value = 3
    prim_38 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_38.location = (5400, 0)
    prim_38.label = 'h_sprocket_col_base_2'
    node_tree.links.new(val_39.outputs["Value"], prim_38.inputs["Radius"])
    node_tree.links.new(val_40.outputs["Value"], prim_38.inputs["Depth"])
    prim_38.inputs["Vertices"].default_value = 10
    vec_42 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_42.location = (5700, 280)
    vec_42.label = 'h_sprocket_col_base_2 rotate rotation'
    vec_42.vector = [1.5707963267948966, 0.0, 0.0]
    xform_41 = node_tree.nodes.new("GeometryNodeTransform")
    xform_41.location = (5700, 0)
    xform_41.label = 'h_sprocket_col_base_2 rotate'
    node_tree.links.new(prim_38.outputs["Mesh"], xform_41.inputs["Geometry"])
    node_tree.links.new(vec_42.outputs["Vector"], xform_41.inputs["Rotation"])
    vec_44 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_44.location = (6000, 280)
    vec_44.label = 'h_sprocket_col_base_2 rotate position offset'
    vec_44.vector = [30, -21.0, -7.5]
    setpos_43 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_43.location = (6000, 0)
    setpos_43.label = 'h_sprocket_col_base_2 rotate position'
    node_tree.links.new(xform_41.outputs["Geometry"], setpos_43.inputs["Geometry"])
    node_tree.links.new(vec_44.outputs["Vector"], setpos_43.inputs["Offset"])
    bool_45 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_45.location = (6300, 0)
    bool_45.label = 'union'
    bool_45.operation = "UNION"
    try:
        bool_45.solver = "EXACT"
    except (TypeError, ValueError):
        bool_45.solver = "EXACT"
    node_tree.links.new(setpos_36.outputs["Geometry"], bool_45.inputs[1])
    node_tree.links.new(setpos_43.outputs["Geometry"], bool_45.inputs[1])
    val_47 = node_tree.nodes.new("ShaderNodeValue")
    val_47.location = (6600, 280)
    val_47.label = 'h_sprocket_col_base radius'
    val_47.outputs[0].default_value = 2.25
    val_48 = node_tree.nodes.new("ShaderNodeValue")
    val_48.location = (6600, 560)
    val_48.label = 'h_sprocket_col_base depth'
    val_48.outputs[0].default_value = 43
    prim_46 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_46.location = (6600, 0)
    prim_46.label = 'h_sprocket_col_base'
    node_tree.links.new(val_47.outputs["Value"], prim_46.inputs["Radius"])
    node_tree.links.new(val_48.outputs["Value"], prim_46.inputs["Depth"])
    prim_46.inputs["Vertices"].default_value = 32
    vec_50 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_50.location = (6900, 280)
    vec_50.label = 'h_sprocket_col_base rotate rotation'
    vec_50.vector = [1.5707963267948966, 0.0, 0.0]
    xform_49 = node_tree.nodes.new("GeometryNodeTransform")
    xform_49.location = (6900, 0)
    xform_49.label = 'h_sprocket_col_base rotate'
    node_tree.links.new(prim_46.outputs["Mesh"], xform_49.inputs["Geometry"])
    node_tree.links.new(vec_50.outputs["Vector"], xform_49.inputs["Rotation"])
    vec_52 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_52.location = (7200, 280)
    vec_52.label = 'h_sprocket_col_base rotate position offset'
    vec_52.vector = [30, 0, -7.5]
    setpos_51 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_51.location = (7200, 0)
    setpos_51.label = 'h_sprocket_col_base rotate position'
    node_tree.links.new(xform_49.outputs["Geometry"], setpos_51.inputs["Geometry"])
    node_tree.links.new(vec_52.outputs["Vector"], setpos_51.inputs["Offset"])
    bool_53 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_53.location = (7500, 0)
    bool_53.label = 'difference'
    bool_53.operation = "DIFFERENCE"
    try:
        bool_53.solver = "EXACT"
    except (TypeError, ValueError):
        bool_53.solver = "EXACT"
    node_tree.links.new(bool_45.outputs["Mesh"], bool_53.inputs[0])
    node_tree.links.new(setpos_51.outputs["Geometry"], bool_53.inputs[1])
    bool_54 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_54.location = (7800, 0)
    bool_54.label = 'union'
    bool_54.operation = "UNION"
    try:
        bool_54.solver = "EXACT"
    except (TypeError, ValueError):
        bool_54.solver = "EXACT"
    node_tree.links.new(bool_30.outputs["Mesh"], bool_54.inputs[1])
    node_tree.links.new(bool_53.outputs["Mesh"], bool_54.inputs[1])
    vec_56 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_56.location = (8100, 280)
    vec_56.label = 'union rotate rotation'
    vec_56.vector = [-1.5707963267948966, 0.0, 1.5707963267948966]
    xform_55 = node_tree.nodes.new("GeometryNodeTransform")
    xform_55.location = (8100, 0)
    xform_55.label = 'union rotate'
    node_tree.links.new(bool_54.outputs["Mesh"], xform_55.inputs["Geometry"])
    node_tree.links.new(vec_56.outputs["Vector"], xform_55.inputs["Rotation"])
    vec_58 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_58.location = (8400, 280)
    vec_58.label = 'union rotate position offset'
    vec_58.vector = [-200, 0, 82]
    setpos_57 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_57.location = (8400, 0)
    setpos_57.label = 'union rotate position'
    node_tree.links.new(xform_55.outputs["Geometry"], setpos_57.inputs["Geometry"])
    node_tree.links.new(vec_58.outputs["Vector"], setpos_57.inputs["Offset"])
    out_59 = node_tree.nodes.new("NodeGroupOutput")
    out_59.location = (8700, 0)
    out_59.label = "output"
    node_tree.links.new(setpos_57.outputs[0], out_59.inputs[0])

    return node_tree





# Execute all parts
setup_dslr_scanner_setup()
setup_cam_mount()
setup_film_slider()
setup_tube_support()
setup_film_slider_2()
