import bpy


def setup_film_spooler(object_name='film_spooler'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (0, 280)
    vec_2.label = "base size"
    vec_2.vector = [89, 74, 3]
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 0)
    prim_1.label = 'base'
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (300, 280)
    vec_4.label = 'base position offset'
    vec_4.vector = [27, 0, -11.5]
    setpos_3 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_3.location = (300, 0)
    setpos_3.label = 'base position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_3.inputs["Geometry"])
    node_tree.links.new(vec_4.outputs["Vector"], setpos_3.inputs["Offset"])
    vec_6 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_6.location = (600, 280)
    vec_6.label = "h_base size"
    vec_6.vector = [5, 63.5, 5]
    prim_5 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_5.location = (600, 0)
    prim_5.label = 'h_base'
    node_tree.links.new(vec_6.outputs["Vector"], prim_5.inputs["Size"])
    vec_8 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_8.location = (900, 280)
    vec_8.label = 'h_base position offset'
    vec_8.vector = [30, 0, -11.5]
    setpos_7 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_7.location = (900, 0)
    setpos_7.label = 'h_base position'
    node_tree.links.new(prim_5.outputs["Mesh"], setpos_7.inputs["Geometry"])
    node_tree.links.new(vec_8.outputs["Vector"], setpos_7.inputs["Offset"])
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (1200, 280)
    vec_10.label = "h_base_120 size"
    vec_10.vector = [33, 66.25, 5]
    prim_9 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_9.location = (1200, 0)
    prim_9.label = 'h_base_120'
    node_tree.links.new(vec_10.outputs["Vector"], prim_9.inputs["Size"])
    vec_12 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_12.location = (1500, 280)
    vec_12.label = 'h_base_120 position offset'
    vec_12.vector = [63.0, 0, -11.5]
    setpos_11 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_11.location = (1500, 0)
    setpos_11.label = 'h_base_120 position'
    node_tree.links.new(prim_9.outputs["Mesh"], setpos_11.inputs["Geometry"])
    node_tree.links.new(vec_12.outputs["Vector"], setpos_11.inputs["Offset"])
    bool_13 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_13.location = (1800, 0)
    bool_13.label = 'difference'
    bool_13.operation = "DIFFERENCE"
    try:
        bool_13.solver = "EXACT"
    except (TypeError, ValueError):
        bool_13.solver = "EXACT"
    node_tree.links.new(setpos_3.outputs["Geometry"], bool_13.inputs[0])
    node_tree.links.new(setpos_7.outputs["Geometry"], bool_13.inputs[1])
    node_tree.links.new(setpos_11.outputs["Geometry"], bool_13.inputs[1])
    vec_15 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_15.location = (2100, 280)
    vec_15.label = "film_roll_case size"
    vec_15.vector = [30, 49, 23]
    prim_14 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_14.location = (2100, 0)
    prim_14.label = 'film_roll_case'
    node_tree.links.new(vec_15.outputs["Vector"], prim_14.inputs["Size"])
    vec_17 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_17.location = (2400, 280)
    vec_17.label = "h_film_roll_case size"
    vec_17.vector = [32, 44, 26]
    prim_16 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_16.location = (2400, 0)
    prim_16.label = 'h_film_roll_case'
    node_tree.links.new(vec_17.outputs["Vector"], prim_16.inputs["Size"])
    vec_19 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_19.location = (2700, 280)
    vec_19.label = 'h_film_roll_case translate translation'
    vec_19.vector = [3, 0, 3]
    xform_18 = node_tree.nodes.new("GeometryNodeTransform")
    xform_18.location = (2700, 0)
    xform_18.label = 'h_film_roll_case translate'
    node_tree.links.new(prim_16.outputs["Mesh"], xform_18.inputs["Geometry"])
    node_tree.links.new(vec_19.outputs["Vector"], xform_18.inputs["Translation"])
    val_21 = node_tree.nodes.new("ShaderNodeValue")
    val_21.location = (3000, 280)
    val_21.label = 'h_cyl_support radius'
    val_21.outputs[0].default_value = 6
    val_22 = node_tree.nodes.new("ShaderNodeValue")
    val_22.location = (3000, 560)
    val_22.label = 'h_cyl_support depth'
    val_22.outputs[0].default_value = 10
    prim_20 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_20.location = (3000, 0)
    prim_20.label = 'h_cyl_support'
    node_tree.links.new(val_21.outputs["Value"], prim_20.inputs["Radius"])
    node_tree.links.new(val_22.outputs["Value"], prim_20.inputs["Depth"])
    prim_20.inputs["Vertices"].default_value = 32
    vec_24 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_24.location = (3300, 280)
    vec_24.label = 'h_cyl_support rotate rotation'
    vec_24.vector = [1.5707963267948966, 0.0, 0.0]
    xform_23 = node_tree.nodes.new("GeometryNodeTransform")
    xform_23.location = (3300, 0)
    xform_23.label = 'h_cyl_support rotate'
    node_tree.links.new(prim_20.outputs["Mesh"], xform_23.inputs["Geometry"])
    node_tree.links.new(vec_24.outputs["Vector"], xform_23.inputs["Rotation"])
    vec_26 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_26.location = (3600, 280)
    vec_26.label = 'h_cyl_support rotate translate translation'
    vec_26.vector = [0, 21.5, 3]
    xform_25 = node_tree.nodes.new("GeometryNodeTransform")
    xform_25.location = (3600, 0)
    xform_25.label = 'h_cyl_support rotate translate'
    node_tree.links.new(xform_23.outputs["Geometry"], xform_25.inputs["Geometry"])
    node_tree.links.new(vec_26.outputs["Vector"], xform_25.inputs["Translation"])
    vec_28 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_28.location = (3900, 280)
    vec_28.label = "h_cyl_cub_support size"
    vec_28.vector = [12, 12, 17]
    prim_27 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_27.location = (3900, 0)
    prim_27.label = 'h_cyl_cub_support'
    node_tree.links.new(vec_28.outputs["Vector"], prim_27.inputs["Size"])
    vec_30 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_30.location = (4200, 280)
    vec_30.label = 'h_cyl_cub_support translate translation'
    vec_30.vector = [0, 21.5, 11.5]
    xform_29 = node_tree.nodes.new("GeometryNodeTransform")
    xform_29.location = (4200, 0)
    xform_29.label = 'h_cyl_cub_support translate'
    node_tree.links.new(prim_27.outputs["Mesh"], xform_29.inputs["Geometry"])
    node_tree.links.new(vec_30.outputs["Vector"], xform_29.inputs["Translation"])
    vec_32 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_32.location = (4500, 280)
    vec_32.label = "h_film_back size"
    vec_32.vector = [4, 36, 3]
    prim_31 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_31.location = (4500, 0)
    prim_31.label = 'h_film_back'
    node_tree.links.new(vec_32.outputs["Vector"], prim_31.inputs["Size"])
    vec_34 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_34.location = (4800, 280)
    vec_34.label = 'h_film_back translate translation'
    vec_34.vector = [-15, 0, -7.5]
    xform_33 = node_tree.nodes.new("GeometryNodeTransform")
    xform_33.location = (4800, 0)
    xform_33.label = 'h_film_back translate'
    node_tree.links.new(prim_31.outputs["Mesh"], xform_33.inputs["Geometry"])
    node_tree.links.new(vec_34.outputs["Vector"], xform_33.inputs["Translation"])
    bool_35 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_35.location = (5100, 0)
    bool_35.label = 'difference'
    bool_35.operation = "DIFFERENCE"
    try:
        bool_35.solver = "EXACT"
    except (TypeError, ValueError):
        bool_35.solver = "EXACT"
    node_tree.links.new(prim_14.outputs["Mesh"], bool_35.inputs[0])
    node_tree.links.new(xform_18.outputs["Geometry"], bool_35.inputs[1])
    node_tree.links.new(xform_25.outputs["Geometry"], bool_35.inputs[1])
    node_tree.links.new(xform_29.outputs["Geometry"], bool_35.inputs[1])
    node_tree.links.new(xform_33.outputs["Geometry"], bool_35.inputs[1])
    val_37 = node_tree.nodes.new("ShaderNodeValue")
    val_37.location = (5400, 280)
    val_37.label = 'cyl_support radius'
    val_37.outputs[0].default_value = 4.875
    val_38 = node_tree.nodes.new("ShaderNodeValue")
    val_38.location = (5400, 560)
    val_38.label = 'cyl_support depth'
    val_38.outputs[0].default_value = 2
    prim_36 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_36.location = (5400, 0)
    prim_36.label = 'cyl_support'
    node_tree.links.new(val_37.outputs["Value"], prim_36.inputs["Radius"])
    node_tree.links.new(val_38.outputs["Value"], prim_36.inputs["Depth"])
    prim_36.inputs["Vertices"].default_value = 32
    vec_40 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_40.location = (5700, 280)
    vec_40.label = 'cyl_support rotate rotation'
    vec_40.vector = [1.5707963267948966, 0.0, 0.0]
    xform_39 = node_tree.nodes.new("GeometryNodeTransform")
    xform_39.location = (5700, 0)
    xform_39.label = 'cyl_support rotate'
    node_tree.links.new(prim_36.outputs["Mesh"], xform_39.inputs["Geometry"])
    node_tree.links.new(vec_40.outputs["Vector"], xform_39.inputs["Rotation"])
    vec_42 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_42.location = (6000, 280)
    vec_42.label = 'cyl_support rotate translate translation'
    vec_42.vector = [0, -21.5, 3]
    xform_41 = node_tree.nodes.new("GeometryNodeTransform")
    xform_41.location = (6000, 0)
    xform_41.label = 'cyl_support rotate translate'
    node_tree.links.new(xform_39.outputs["Geometry"], xform_41.inputs["Geometry"])
    node_tree.links.new(vec_42.outputs["Vector"], xform_41.inputs["Translation"])
    bool_43 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_43.location = (6300, 0)
    bool_43.label = 'union'
    bool_43.operation = "UNION"
    try:
        bool_43.solver = "EXACT"
    except (TypeError, ValueError):
        bool_43.solver = "EXACT"
    node_tree.links.new(bool_35.outputs["Mesh"], bool_43.inputs[1])
    node_tree.links.new(xform_41.outputs["Geometry"], bool_43.inputs[1])
    vec_45 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_45.location = (6600, 280)
    vec_45.label = "reel size"
    vec_45.vector = [10, 43, 5]
    prim_44 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_44.location = (6600, 0)
    prim_44.label = 'reel'
    node_tree.links.new(vec_45.outputs["Vector"], prim_44.inputs["Size"])
    vec_47 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_47.location = (6900, 280)
    vec_47.label = 'reel translate translation'
    vec_47.vector = [21.5, 0, -8.5]
    xform_46 = node_tree.nodes.new("GeometryNodeTransform")
    xform_46.location = (6900, 0)
    xform_46.label = 'reel translate'
    node_tree.links.new(prim_44.outputs["Mesh"], xform_46.inputs["Geometry"])
    node_tree.links.new(vec_47.outputs["Vector"], xform_46.inputs["Translation"])
    vec_49 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_49.location = (7200, 280)
    vec_49.label = "h_reel size"
    vec_49.vector = [10, 35.25, 6]
    prim_48 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_48.location = (7200, 0)
    prim_48.label = 'h_reel'
    node_tree.links.new(vec_49.outputs["Vector"], prim_48.inputs["Size"])
    vec_51 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_51.location = (7500, 280)
    vec_51.label = 'h_reel translate translation'
    vec_51.vector = [21.5, 0, -8.5]
    xform_50 = node_tree.nodes.new("GeometryNodeTransform")
    xform_50.location = (7500, 0)
    xform_50.label = 'h_reel translate'
    node_tree.links.new(prim_48.outputs["Mesh"], xform_50.inputs["Geometry"])
    node_tree.links.new(vec_51.outputs["Vector"], xform_50.inputs["Translation"])
    bool_52 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_52.location = (7800, 0)
    bool_52.label = 'difference'
    bool_52.operation = "DIFFERENCE"
    try:
        bool_52.solver = "EXACT"
    except (TypeError, ValueError):
        bool_52.solver = "EXACT"
    node_tree.links.new(xform_46.outputs["Geometry"], bool_52.inputs[0])
    node_tree.links.new(xform_50.outputs["Geometry"], bool_52.inputs[1])
    val_54 = node_tree.nodes.new("ShaderNodeValue")
    val_54.location = (8100, 280)
    val_54.label = 'film_120_bridge radius'
    val_54.outputs[0].default_value = 8
    val_55 = node_tree.nodes.new("ShaderNodeValue")
    val_55.location = (8100, 560)
    val_55.label = 'film_120_bridge depth'
    val_55.outputs[0].default_value = 70
    prim_53 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_53.location = (8100, 0)
    prim_53.label = 'film_120_bridge'
    node_tree.links.new(val_54.outputs["Value"], prim_53.inputs["Radius"])
    node_tree.links.new(val_55.outputs["Value"], prim_53.inputs["Depth"])
    prim_53.inputs["Vertices"].default_value = 32
    vec_57 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_57.location = (8400, 280)
    vec_57.label = 'film_120_bridge rotate rotation'
    vec_57.vector = [1.5707963267948966, 0.0, 0.0]
    xform_56 = node_tree.nodes.new("GeometryNodeTransform")
    xform_56.location = (8400, 0)
    xform_56.label = 'film_120_bridge rotate'
    node_tree.links.new(prim_53.outputs["Mesh"], xform_56.inputs["Geometry"])
    node_tree.links.new(vec_57.outputs["Vector"], xform_56.inputs["Rotation"])
    vec_59 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_59.location = (8700, 280)
    vec_59.label = 'film_120_bridge rotate translate translation'
    vec_59.vector = [63.0, 0, 1]
    xform_58 = node_tree.nodes.new("GeometryNodeTransform")
    xform_58.location = (8700, 0)
    xform_58.label = 'film_120_bridge rotate translate'
    node_tree.links.new(xform_56.outputs["Geometry"], xform_58.inputs["Geometry"])
    node_tree.links.new(vec_59.outputs["Vector"], xform_58.inputs["Translation"])
    vec_61 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_61.location = (9000, 280)
    vec_61.label = "bridge_wall size"
    vec_61.vector = [16, 70, 14]
    prim_60 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_60.location = (9000, 0)
    prim_60.label = 'bridge_wall'
    node_tree.links.new(vec_61.outputs["Vector"], prim_60.inputs["Size"])
    vec_63 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_63.location = (9300, 280)
    vec_63.label = 'bridge_wall translate translation'
    vec_63.vector = [63.0, 0, -6]
    xform_62 = node_tree.nodes.new("GeometryNodeTransform")
    xform_62.location = (9300, 0)
    xform_62.label = 'bridge_wall translate'
    node_tree.links.new(prim_60.outputs["Mesh"], xform_62.inputs["Geometry"])
    node_tree.links.new(vec_63.outputs["Vector"], xform_62.inputs["Translation"])
    bool_64 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_64.location = (9600, 0)
    bool_64.label = 'union'
    bool_64.operation = "UNION"
    try:
        bool_64.solver = "EXACT"
    except (TypeError, ValueError):
        bool_64.solver = "EXACT"
    node_tree.links.new(xform_58.outputs["Geometry"], bool_64.inputs[1])
    node_tree.links.new(xform_62.outputs["Geometry"], bool_64.inputs[1])
    val_66 = node_tree.nodes.new("ShaderNodeValue")
    val_66.location = (9900, 280)
    val_66.label = 'h_film_120_bridge radius'
    val_66.outputs[0].default_value = 18
    val_67 = node_tree.nodes.new("ShaderNodeValue")
    val_67.location = (9900, 560)
    val_67.label = 'h_film_120_bridge depth'
    val_67.outputs[0].default_value = 66.25
    prim_65 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_65.location = (9900, 0)
    prim_65.label = 'h_film_120_bridge'
    node_tree.links.new(val_66.outputs["Value"], prim_65.inputs["Radius"])
    node_tree.links.new(val_67.outputs["Value"], prim_65.inputs["Depth"])
    prim_65.inputs["Vertices"].default_value = 32
    vec_69 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_69.location = (10200, 280)
    vec_69.label = 'h_film_120_bridge rotate rotation'
    vec_69.vector = [1.5707963267948966, 0.0, 0.0]
    xform_68 = node_tree.nodes.new("GeometryNodeTransform")
    xform_68.location = (10200, 0)
    xform_68.label = 'h_film_120_bridge rotate'
    node_tree.links.new(prim_65.outputs["Mesh"], xform_68.inputs["Geometry"])
    node_tree.links.new(vec_69.outputs["Vector"], xform_68.inputs["Rotation"])
    vec_71 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_71.location = (10500, 280)
    vec_71.label = 'h_film_120_bridge rotate translate translation'
    vec_71.vector = [63.0, 0, 1]
    xform_70 = node_tree.nodes.new("GeometryNodeTransform")
    xform_70.location = (10500, 0)
    xform_70.label = 'h_film_120_bridge rotate translate'
    node_tree.links.new(xform_68.outputs["Geometry"], xform_70.inputs["Geometry"])
    node_tree.links.new(vec_71.outputs["Vector"], xform_70.inputs["Translation"])
    val_73 = node_tree.nodes.new("ShaderNodeValue")
    val_73.location = (10800, 280)
    val_73.label = 'h_film_axis radius'
    val_73.outputs[0].default_value = 2.5
    val_74 = node_tree.nodes.new("ShaderNodeValue")
    val_74.location = (10800, 560)
    val_74.label = 'h_film_axis depth'
    val_74.outputs[0].default_value = 100.25
    prim_72 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_72.location = (10800, 0)
    prim_72.label = 'h_film_axis'
    node_tree.links.new(val_73.outputs["Value"], prim_72.inputs["Radius"])
    node_tree.links.new(val_74.outputs["Value"], prim_72.inputs["Depth"])
    prim_72.inputs["Vertices"].default_value = 32
    vec_76 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_76.location = (11100, 280)
    vec_76.label = 'h_film_axis rotate rotation'
    vec_76.vector = [1.5707963267948966, 0.0, 0.0]
    xform_75 = node_tree.nodes.new("GeometryNodeTransform")
    xform_75.location = (11100, 0)
    xform_75.label = 'h_film_axis rotate'
    node_tree.links.new(prim_72.outputs["Mesh"], xform_75.inputs["Geometry"])
    node_tree.links.new(vec_76.outputs["Vector"], xform_75.inputs["Rotation"])
    vec_78 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_78.location = (11400, 280)
    vec_78.label = 'h_film_axis rotate translate translation'
    vec_78.vector = [63.0, 0, 1]
    xform_77 = node_tree.nodes.new("GeometryNodeTransform")
    xform_77.location = (11400, 0)
    xform_77.label = 'h_film_axis rotate translate'
    node_tree.links.new(xform_75.outputs["Geometry"], xform_77.inputs["Geometry"])
    node_tree.links.new(vec_78.outputs["Vector"], xform_77.inputs["Translation"])
    bool_79 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_79.location = (11700, 0)
    bool_79.label = 'difference'
    bool_79.operation = "DIFFERENCE"
    try:
        bool_79.solver = "EXACT"
    except (TypeError, ValueError):
        bool_79.solver = "EXACT"
    node_tree.links.new(bool_64.outputs["Mesh"], bool_79.inputs[0])
    node_tree.links.new(xform_70.outputs["Geometry"], bool_79.inputs[1])
    node_tree.links.new(xform_77.outputs["Geometry"], bool_79.inputs[1])
    vec_81 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_81.location = (12000, 280)
    vec_81.label = "film_stop size"
    vec_81.vector = [2, 49, 4]
    prim_80 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_80.location = (12000, 0)
    prim_80.label = 'film_stop'
    node_tree.links.new(vec_81.outputs["Vector"], prim_80.inputs["Size"])
    vec_83 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_83.location = (12300, 280)
    vec_83.label = 'film_stop translate translation'
    vec_83.vector = [14, 0, -8.5]
    xform_82 = node_tree.nodes.new("GeometryNodeTransform")
    xform_82.location = (12300, 0)
    xform_82.label = 'film_stop translate'
    node_tree.links.new(prim_80.outputs["Mesh"], xform_82.inputs["Geometry"])
    node_tree.links.new(vec_83.outputs["Vector"], xform_82.inputs["Translation"])
    vec_85 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_85.location = (12600, 280)
    vec_85.label = "h_film_stop size"
    vec_85.vector = [5, 36, 4]
    prim_84 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_84.location = (12600, 0)
    prim_84.label = 'h_film_stop'
    node_tree.links.new(vec_85.outputs["Vector"], prim_84.inputs["Size"])
    vec_87 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_87.location = (12900, 280)
    vec_87.label = 'h_film_stop translate translation'
    vec_87.vector = [14, 0, -8.5]
    xform_86 = node_tree.nodes.new("GeometryNodeTransform")
    xform_86.location = (12900, 0)
    xform_86.label = 'h_film_stop translate'
    node_tree.links.new(prim_84.outputs["Mesh"], xform_86.inputs["Geometry"])
    node_tree.links.new(vec_87.outputs["Vector"], xform_86.inputs["Translation"])
    bool_88 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_88.location = (13200, 0)
    bool_88.label = 'difference'
    bool_88.operation = "DIFFERENCE"
    try:
        bool_88.solver = "EXACT"
    except (TypeError, ValueError):
        bool_88.solver = "EXACT"
    node_tree.links.new(xform_82.outputs["Geometry"], bool_88.inputs[0])
    node_tree.links.new(xform_86.outputs["Geometry"], bool_88.inputs[1])
    bool_89 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_89.location = (13500, 0)
    bool_89.label = 'union'
    bool_89.operation = "UNION"
    try:
        bool_89.solver = "EXACT"
    except (TypeError, ValueError):
        bool_89.solver = "EXACT"
    node_tree.links.new(bool_13.outputs["Mesh"], bool_89.inputs[1])
    node_tree.links.new(bool_43.outputs["Mesh"], bool_89.inputs[1])
    node_tree.links.new(bool_52.outputs["Mesh"], bool_89.inputs[1])
    node_tree.links.new(bool_79.outputs["Mesh"], bool_89.inputs[1])
    node_tree.links.new(bool_88.outputs["Mesh"], bool_89.inputs[1])
    out_90 = node_tree.nodes.new("NodeGroupOutput")
    out_90.location = (13800, 0)
    out_90.label = "output"
    node_tree.links.new(bool_89.outputs[0], out_90.inputs[0])

    return node_tree




def setup_h_base_120(object_name='h_base_120'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (0, 280)
    vec_2.label = "h_base_120 size"
    vec_2.vector = [30, 63.25, 5]
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 0)
    prim_1.label = 'h_base_120'
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (300, 280)
    vec_4.label = 'h_base_120 position offset'
    vec_4.vector = [52.0, 0, -11.5]
    setpos_3 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_3.location = (300, 0)
    setpos_3.label = 'h_base_120 position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_3.inputs["Geometry"])
    node_tree.links.new(vec_4.outputs["Vector"], setpos_3.inputs["Offset"])
    out_5 = node_tree.nodes.new("NodeGroupOutput")
    out_5.location = (600, 0)
    out_5.label = "output"
    node_tree.links.new(setpos_3.outputs[0], out_5.inputs[0])

    return node_tree





# Execute all parts
setup_film_spooler()
setup_h_base_120()
