import bpy


def setup_film_slider(object_name='film_slider'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (0, 280)
    vec_2.label = "slider_base size"
    vec_2.vector = [52, 45, 7]
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 0)
    prim_1.label = 'slider_base'
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (300, 280)
    vec_4.label = 'slider_base position offset'
    vec_4.vector = [0, 0, 1]
    setpos_3 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_3.location = (300, 0)
    setpos_3.label = 'slider_base position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_3.inputs["Geometry"])
    node_tree.links.new(vec_4.outputs["Vector"], setpos_3.inputs["Offset"])
    vec_6 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_6.location = (600, 280)
    vec_6.label = "h_sprocket_gear size"
    vec_6.vector = [72, 10, 6.5]
    prim_5 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_5.location = (600, 0)
    prim_5.label = 'h_sprocket_gear'
    node_tree.links.new(vec_6.outputs["Vector"], prim_5.inputs["Size"])
    vec_8 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_8.location = (900, 280)
    vec_8.label = 'h_sprocket_gear position offset'
    vec_8.vector = [0, 0, 1.25]
    setpos_7 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_7.location = (900, 0)
    setpos_7.label = 'h_sprocket_gear position'
    node_tree.links.new(prim_5.outputs["Mesh"], setpos_7.inputs["Geometry"])
    node_tree.links.new(vec_8.outputs["Vector"], setpos_7.inputs["Offset"])
    bool_9 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_9.location = (1200, 0)
    bool_9.label = 'union'
    bool_9.operation = "UNION"
    try:
        bool_9.solver = "EXACT"
    except (TypeError, ValueError):
        bool_9.solver = "EXACT"
    node_tree.links.new(setpos_3.outputs["Geometry"], bool_9.inputs[1])
    node_tree.links.new(setpos_7.outputs["Geometry"], bool_9.inputs[1])
    vec_11 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_11.location = (1500, 280)
    vec_11.label = "h_slider size"
    vec_11.vector = [40, 34.25, 30]
    prim_10 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_10.location = (1500, 0)
    prim_10.label = 'h_slider'
    node_tree.links.new(vec_11.outputs["Vector"], prim_10.inputs["Size"])
    vec_13 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_13.location = (1800, 280)
    vec_13.label = "h_slider size"
    vec_13.vector = [160, 35.125, 0.5]
    prim_12 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_12.location = (1800, 0)
    prim_12.label = 'h_slider'
    node_tree.links.new(vec_13.outputs["Vector"], prim_12.inputs["Size"])
    vec_15 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_15.location = (2100, 280)
    vec_15.label = 'h_slider position offset'
    vec_15.vector = [0, 0, -2.25]
    setpos_14 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_14.location = (2100, 0)
    setpos_14.label = 'h_slider position'
    node_tree.links.new(prim_12.outputs["Mesh"], setpos_14.inputs["Geometry"])
    node_tree.links.new(vec_15.outputs["Vector"], setpos_14.inputs["Offset"])
    vec_17 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_17.location = (2400, 280)
    vec_17.label = "h_below size"
    vec_17.vector = [35, 34.25, 35]
    prim_16 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_16.location = (2400, 0)
    prim_16.label = 'h_below'
    node_tree.links.new(vec_17.outputs["Vector"], prim_16.inputs["Size"])
    vec_19 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_19.location = (2700, 280)
    vec_19.label = 'h_below rotate rotation'
    vec_19.vector = [0.0, 0.7853981633974483, 0.0]
    xform_18 = node_tree.nodes.new("GeometryNodeTransform")
    xform_18.location = (2700, 0)
    xform_18.label = 'h_below rotate'
    node_tree.links.new(prim_16.outputs["Mesh"], xform_18.inputs["Geometry"])
    node_tree.links.new(vec_19.outputs["Vector"], xform_18.inputs["Rotation"])
    vec_21 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_21.location = (3000, 280)
    vec_21.label = 'h_below rotate position offset'
    vec_21.vector = [0, 0, -2.25]
    setpos_20 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_20.location = (3000, 0)
    setpos_20.label = 'h_below rotate position'
    node_tree.links.new(xform_18.outputs["Geometry"], setpos_20.inputs["Geometry"])
    node_tree.links.new(vec_21.outputs["Vector"], setpos_20.inputs["Offset"])
    vec_23 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_23.location = (3300, 280)
    vec_23.label = "base_2 size"
    vec_23.vector = [6.125, 48.25, 6]
    prim_22 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_22.location = (3300, 0)
    prim_22.label = 'base_2'
    node_tree.links.new(vec_23.outputs["Vector"], prim_22.inputs["Size"])
    vec_25 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_25.location = (3600, 280)
    vec_25.label = 'base_2 position offset'
    vec_25.vector = [30, 0, 1.5]
    setpos_24 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_24.location = (3600, 0)
    setpos_24.label = 'base_2 position'
    node_tree.links.new(prim_22.outputs["Mesh"], setpos_24.inputs["Geometry"])
    node_tree.links.new(vec_25.outputs["Vector"], setpos_24.inputs["Offset"])
    vec_27 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_27.location = (3900, 280)
    vec_27.label = "base_2 size"
    vec_27.vector = [6.125, 48.25, 6]
    prim_26 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_26.location = (3900, 0)
    prim_26.label = 'base_2'
    node_tree.links.new(vec_27.outputs["Vector"], prim_26.inputs["Size"])
    vec_29 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_29.location = (4200, 280)
    vec_29.label = 'base_2 position offset'
    vec_29.vector = [-30, 0, 1.5]
    setpos_28 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_28.location = (4200, 0)
    setpos_28.label = 'base_2 position'
    node_tree.links.new(prim_26.outputs["Mesh"], setpos_28.inputs["Geometry"])
    node_tree.links.new(vec_29.outputs["Vector"], setpos_28.inputs["Offset"])
    bool_30 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_30.location = (4500, 0)
    bool_30.label = 'difference'
    bool_30.operation = "DIFFERENCE"
    try:
        bool_30.solver = "EXACT"
    except (TypeError, ValueError):
        bool_30.solver = "EXACT"
    node_tree.links.new(bool_9.outputs["Mesh"], bool_30.inputs[0])
    node_tree.links.new(prim_10.outputs["Mesh"], bool_30.inputs[1])
    node_tree.links.new(setpos_14.outputs["Geometry"], bool_30.inputs[1])
    node_tree.links.new(setpos_20.outputs["Geometry"], bool_30.inputs[1])
    node_tree.links.new(setpos_24.outputs["Geometry"], bool_30.inputs[1])
    node_tree.links.new(setpos_28.outputs["Geometry"], bool_30.inputs[1])
    vec_32 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_32.location = (4800, 280)
    vec_32.label = "join_1 size"
    vec_32.vector = [40, 3, 3]
    prim_31 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_31.location = (4800, 0)
    prim_31.label = 'join_1'
    node_tree.links.new(vec_32.outputs["Vector"], prim_31.inputs["Size"])
    vec_34 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_34.location = (5100, 280)
    vec_34.label = 'join_1 position offset'
    vec_34.vector = [0, 20, -4]
    setpos_33 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_33.location = (5100, 0)
    setpos_33.label = 'join_1 position'
    node_tree.links.new(prim_31.outputs["Mesh"], setpos_33.inputs["Geometry"])
    node_tree.links.new(vec_34.outputs["Vector"], setpos_33.inputs["Offset"])
    vec_36 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_36.location = (5400, 280)
    vec_36.label = "join_1 size"
    vec_36.vector = [40, 3, 3]
    prim_35 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_35.location = (5400, 0)
    prim_35.label = 'join_1'
    node_tree.links.new(vec_36.outputs["Vector"], prim_35.inputs["Size"])
    vec_38 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_38.location = (5700, 280)
    vec_38.label = 'join_1 position offset'
    vec_38.vector = [0, -20, -4]
    setpos_37 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_37.location = (5700, 0)
    setpos_37.label = 'join_1 position'
    node_tree.links.new(prim_35.outputs["Mesh"], setpos_37.inputs["Geometry"])
    node_tree.links.new(vec_38.outputs["Vector"], setpos_37.inputs["Offset"])
    bool_39 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_39.location = (6000, 0)
    bool_39.label = 'union'
    bool_39.operation = "UNION"
    try:
        bool_39.solver = "EXACT"
    except (TypeError, ValueError):
        bool_39.solver = "EXACT"
    node_tree.links.new(bool_30.outputs["Mesh"], bool_39.inputs[1])
    node_tree.links.new(setpos_33.outputs["Geometry"], bool_39.inputs[1])
    node_tree.links.new(setpos_37.outputs["Geometry"], bool_39.inputs[1])
    vec_41 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_41.location = (6300, 280)
    vec_41.label = 'union rotate rotation'
    vec_41.vector = [3.141592653589793, 0.0, 0.0]
    xform_40 = node_tree.nodes.new("GeometryNodeTransform")
    xform_40.location = (6300, 0)
    xform_40.label = 'union rotate'
    node_tree.links.new(bool_39.outputs["Mesh"], xform_40.inputs["Geometry"])
    node_tree.links.new(vec_41.outputs["Vector"], xform_40.inputs["Rotation"])
    vec_43 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_43.location = (6600, 280)
    vec_43.label = 'union rotate translate translation'
    vec_43.vector = [0, 0, 11.05]
    xform_42 = node_tree.nodes.new("GeometryNodeTransform")
    xform_42.location = (6600, 0)
    xform_42.label = 'union rotate translate'
    node_tree.links.new(xform_40.outputs["Geometry"], xform_42.inputs["Geometry"])
    node_tree.links.new(vec_43.outputs["Vector"], xform_42.inputs["Translation"])
    out_44 = node_tree.nodes.new("NodeGroupOutput")
    out_44.location = (6900, 0)
    out_44.label = "output"
    node_tree.links.new(xform_42.outputs[0], out_44.inputs[0])

    return node_tree




def setup_film_slider_2(object_name='film_slider_2'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (0, 280)
    vec_2.label = "slider size"
    vec_2.vector = [80, 45, 5]
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 0)
    prim_1.label = 'slider'
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (300, 280)
    vec_4.label = 'slider position offset'
    vec_4.vector = [0, 0, -5]
    setpos_3 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_3.location = (300, 0)
    setpos_3.label = 'slider position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_3.inputs["Geometry"])
    node_tree.links.new(vec_4.outputs["Vector"], setpos_3.inputs["Offset"])
    vec_6 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_6.location = (600, 280)
    vec_6.label = "h_slider size"
    vec_6.vector = [40, 34.5, 30]
    prim_5 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_5.location = (600, 0)
    prim_5.label = 'h_slider'
    node_tree.links.new(vec_6.outputs["Vector"], prim_5.inputs["Size"])
    vec_8 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_8.location = (900, 280)
    vec_8.label = "join_1 size"
    vec_8.vector = [40.125, 3.125, 3.125]
    prim_7 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_7.location = (900, 0)
    prim_7.label = 'join_1'
    node_tree.links.new(vec_8.outputs["Vector"], prim_7.inputs["Size"])
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (1200, 280)
    vec_10.label = 'join_1 position offset'
    vec_10.vector = [0, 20, -4]
    setpos_9 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_9.location = (1200, 0)
    setpos_9.label = 'join_1 position'
    node_tree.links.new(prim_7.outputs["Mesh"], setpos_9.inputs["Geometry"])
    node_tree.links.new(vec_10.outputs["Vector"], setpos_9.inputs["Offset"])
    vec_12 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_12.location = (1500, 280)
    vec_12.label = "join_1 size"
    vec_12.vector = [40.125, 3.125, 3.125]
    prim_11 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_11.location = (1500, 0)
    prim_11.label = 'join_1'
    node_tree.links.new(vec_12.outputs["Vector"], prim_11.inputs["Size"])
    vec_14 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_14.location = (1800, 280)
    vec_14.label = 'join_1 position offset'
    vec_14.vector = [0, -20, -4]
    setpos_13 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_13.location = (1800, 0)
    setpos_13.label = 'join_1 position'
    node_tree.links.new(prim_11.outputs["Mesh"], setpos_13.inputs["Geometry"])
    node_tree.links.new(vec_14.outputs["Vector"], setpos_13.inputs["Offset"])
    vec_16 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_16.location = (2100, 280)
    vec_16.label = "h_sprocket_gear size"
    vec_16.vector = [15, 5, 10]
    prim_15 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_15.location = (2100, 0)
    prim_15.label = 'h_sprocket_gear'
    node_tree.links.new(vec_16.outputs["Vector"], prim_15.inputs["Size"])
    vec_18 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_18.location = (2400, 280)
    vec_18.label = 'h_sprocket_gear position offset'
    vec_18.vector = [30, 14.0845, -5]
    setpos_17 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_17.location = (2400, 0)
    setpos_17.label = 'h_sprocket_gear position'
    node_tree.links.new(prim_15.outputs["Mesh"], setpos_17.inputs["Geometry"])
    node_tree.links.new(vec_18.outputs["Vector"], setpos_17.inputs["Offset"])
    vec_20 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_20.location = (2700, 280)
    vec_20.label = "h_sprocket_gear size"
    vec_20.vector = [15, 5, 10]
    prim_19 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_19.location = (2700, 0)
    prim_19.label = 'h_sprocket_gear'
    node_tree.links.new(vec_20.outputs["Vector"], prim_19.inputs["Size"])
    vec_22 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_22.location = (3000, 280)
    vec_22.label = 'h_sprocket_gear position offset'
    vec_22.vector = [30, -14.0845, -5]
    setpos_21 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_21.location = (3000, 0)
    setpos_21.label = 'h_sprocket_gear position'
    node_tree.links.new(prim_19.outputs["Mesh"], setpos_21.inputs["Geometry"])
    node_tree.links.new(vec_22.outputs["Vector"], setpos_21.inputs["Offset"])
    val_24 = node_tree.nodes.new("ShaderNodeValue")
    val_24.location = (3300, 280)
    val_24.label = 'h_sprocket_col radius'
    val_24.outputs[0].default_value = 4
    val_25 = node_tree.nodes.new("ShaderNodeValue")
    val_25.location = (3300, 560)
    val_25.label = 'h_sprocket_col depth'
    val_25.outputs[0].default_value = 60
    prim_23 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_23.location = (3300, 0)
    prim_23.label = 'h_sprocket_col'
    node_tree.links.new(val_24.outputs["Value"], prim_23.inputs["Radius"])
    node_tree.links.new(val_25.outputs["Value"], prim_23.inputs["Depth"])
    prim_23.inputs["Vertices"].default_value = 32
    vec_27 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_27.location = (3600, 280)
    vec_27.label = 'h_sprocket_col rotate rotation'
    vec_27.vector = [1.5707963267948966, 0.0, 0.0]
    xform_26 = node_tree.nodes.new("GeometryNodeTransform")
    xform_26.location = (3600, 0)
    xform_26.label = 'h_sprocket_col rotate'
    node_tree.links.new(prim_23.outputs["Mesh"], xform_26.inputs["Geometry"])
    node_tree.links.new(vec_27.outputs["Vector"], xform_26.inputs["Rotation"])
    vec_29 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_29.location = (3900, 280)
    vec_29.label = 'h_sprocket_col rotate position offset'
    vec_29.vector = [30, 0, -7.5]
    setpos_28 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_28.location = (3900, 0)
    setpos_28.label = 'h_sprocket_col rotate position'
    node_tree.links.new(xform_26.outputs["Geometry"], setpos_28.inputs["Geometry"])
    node_tree.links.new(vec_29.outputs["Vector"], setpos_28.inputs["Offset"])
    bool_30 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_30.location = (4200, 0)
    bool_30.label = 'difference'
    bool_30.operation = "DIFFERENCE"
    try:
        bool_30.solver = "EXACT"
    except (TypeError, ValueError):
        bool_30.solver = "EXACT"
    node_tree.links.new(setpos_3.outputs["Geometry"], bool_30.inputs[0])
    node_tree.links.new(prim_5.outputs["Mesh"], bool_30.inputs[1])
    node_tree.links.new(setpos_9.outputs["Geometry"], bool_30.inputs[1])
    node_tree.links.new(setpos_13.outputs["Geometry"], bool_30.inputs[1])
    node_tree.links.new(setpos_17.outputs["Geometry"], bool_30.inputs[1])
    node_tree.links.new(setpos_21.outputs["Geometry"], bool_30.inputs[1])
    node_tree.links.new(setpos_28.outputs["Geometry"], bool_30.inputs[1])
    val_32 = node_tree.nodes.new("ShaderNodeValue")
    val_32.location = (4500, 280)
    val_32.label = 'h_sprocket_col_base_1 radius'
    val_32.outputs[0].default_value = 4.5
    val_33 = node_tree.nodes.new("ShaderNodeValue")
    val_33.location = (4500, 560)
    val_33.label = 'h_sprocket_col_base_1 depth'
    val_33.outputs[0].default_value = 3
    prim_31 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_31.location = (4500, 0)
    prim_31.label = 'h_sprocket_col_base_1'
    node_tree.links.new(val_32.outputs["Value"], prim_31.inputs["Radius"])
    node_tree.links.new(val_33.outputs["Value"], prim_31.inputs["Depth"])
    prim_31.inputs["Vertices"].default_value = 10
    vec_35 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_35.location = (4800, 280)
    vec_35.label = 'h_sprocket_col_base_1 rotate rotation'
    vec_35.vector = [1.5707963267948966, 0.0, 0.0]
    xform_34 = node_tree.nodes.new("GeometryNodeTransform")
    xform_34.location = (4800, 0)
    xform_34.label = 'h_sprocket_col_base_1 rotate'
    node_tree.links.new(prim_31.outputs["Mesh"], xform_34.inputs["Geometry"])
    node_tree.links.new(vec_35.outputs["Vector"], xform_34.inputs["Rotation"])
    vec_37 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_37.location = (5100, 280)
    vec_37.label = 'h_sprocket_col_base_1 rotate position offset'
    vec_37.vector = [30, 21.0, -7.5]
    setpos_36 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_36.location = (5100, 0)
    setpos_36.label = 'h_sprocket_col_base_1 rotate position'
    node_tree.links.new(xform_34.outputs["Geometry"], setpos_36.inputs["Geometry"])
    node_tree.links.new(vec_37.outputs["Vector"], setpos_36.inputs["Offset"])
    val_39 = node_tree.nodes.new("ShaderNodeValue")
    val_39.location = (5400, 280)
    val_39.label = 'h_sprocket_col_base_2 radius'
    val_39.outputs[0].default_value = 4.5
    val_40 = node_tree.nodes.new("ShaderNodeValue")
    val_40.location = (5400, 560)
    val_40.label = 'h_sprocket_col_base_2 depth'
    val_40.outputs[0].default_value = 3
    prim_38 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_38.location = (5400, 0)
    prim_38.label = 'h_sprocket_col_base_2'
    node_tree.links.new(val_39.outputs["Value"], prim_38.inputs["Radius"])
    node_tree.links.new(val_40.outputs["Value"], prim_38.inputs["Depth"])
    prim_38.inputs["Vertices"].default_value = 10
    vec_42 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_42.location = (5700, 280)
    vec_42.label = 'h_sprocket_col_base_2 rotate rotation'
    vec_42.vector = [1.5707963267948966, 0.0, 0.0]
    xform_41 = node_tree.nodes.new("GeometryNodeTransform")
    xform_41.location = (5700, 0)
    xform_41.label = 'h_sprocket_col_base_2 rotate'
    node_tree.links.new(prim_38.outputs["Mesh"], xform_41.inputs["Geometry"])
    node_tree.links.new(vec_42.outputs["Vector"], xform_41.inputs["Rotation"])
    vec_44 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_44.location = (6000, 280)
    vec_44.label = 'h_sprocket_col_base_2 rotate position offset'
    vec_44.vector = [30, -21.0, -7.5]
    setpos_43 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_43.location = (6000, 0)
    setpos_43.label = 'h_sprocket_col_base_2 rotate position'
    node_tree.links.new(xform_41.outputs["Geometry"], setpos_43.inputs["Geometry"])
    node_tree.links.new(vec_44.outputs["Vector"], setpos_43.inputs["Offset"])
    bool_45 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_45.location = (6300, 0)
    bool_45.label = 'union'
    bool_45.operation = "UNION"
    try:
        bool_45.solver = "EXACT"
    except (TypeError, ValueError):
        bool_45.solver = "EXACT"
    node_tree.links.new(setpos_36.outputs["Geometry"], bool_45.inputs[1])
    node_tree.links.new(setpos_43.outputs["Geometry"], bool_45.inputs[1])
    val_47 = node_tree.nodes.new("ShaderNodeValue")
    val_47.location = (6600, 280)
    val_47.label = 'h_sprocket_col_base radius'
    val_47.outputs[0].default_value = 2.25
    val_48 = node_tree.nodes.new("ShaderNodeValue")
    val_48.location = (6600, 560)
    val_48.label = 'h_sprocket_col_base depth'
    val_48.outputs[0].default_value = 43
    prim_46 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_46.location = (6600, 0)
    prim_46.label = 'h_sprocket_col_base'
    node_tree.links.new(val_47.outputs["Value"], prim_46.inputs["Radius"])
    node_tree.links.new(val_48.outputs["Value"], prim_46.inputs["Depth"])
    prim_46.inputs["Vertices"].default_value = 32
    vec_50 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_50.location = (6900, 280)
    vec_50.label = 'h_sprocket_col_base rotate rotation'
    vec_50.vector = [1.5707963267948966, 0.0, 0.0]
    xform_49 = node_tree.nodes.new("GeometryNodeTransform")
    xform_49.location = (6900, 0)
    xform_49.label = 'h_sprocket_col_base rotate'
    node_tree.links.new(prim_46.outputs["Mesh"], xform_49.inputs["Geometry"])
    node_tree.links.new(vec_50.outputs["Vector"], xform_49.inputs["Rotation"])
    vec_52 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_52.location = (7200, 280)
    vec_52.label = 'h_sprocket_col_base rotate position offset'
    vec_52.vector = [30, 0, -7.5]
    setpos_51 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_51.location = (7200, 0)
    setpos_51.label = 'h_sprocket_col_base rotate position'
    node_tree.links.new(xform_49.outputs["Geometry"], setpos_51.inputs["Geometry"])
    node_tree.links.new(vec_52.outputs["Vector"], setpos_51.inputs["Offset"])
    bool_53 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_53.location = (7500, 0)
    bool_53.label = 'difference'
    bool_53.operation = "DIFFERENCE"
    try:
        bool_53.solver = "EXACT"
    except (TypeError, ValueError):
        bool_53.solver = "EXACT"
    node_tree.links.new(bool_45.outputs["Mesh"], bool_53.inputs[0])
    node_tree.links.new(setpos_51.outputs["Geometry"], bool_53.inputs[1])
    bool_54 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_54.location = (7800, 0)
    bool_54.label = 'union'
    bool_54.operation = "UNION"
    try:
        bool_54.solver = "EXACT"
    except (TypeError, ValueError):
        bool_54.solver = "EXACT"
    node_tree.links.new(bool_30.outputs["Mesh"], bool_54.inputs[1])
    node_tree.links.new(bool_53.outputs["Mesh"], bool_54.inputs[1])
    vec_56 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_56.location = (8100, 280)
    vec_56.label = 'union rotate rotation'
    vec_56.vector = [3.141592653589793, 0.0, 0.0]
    xform_55 = node_tree.nodes.new("GeometryNodeTransform")
    xform_55.location = (8100, 0)
    xform_55.label = 'union rotate'
    node_tree.links.new(bool_54.outputs["Mesh"], xform_55.inputs["Geometry"])
    node_tree.links.new(vec_56.outputs["Vector"], xform_55.inputs["Rotation"])
    vec_58 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_58.location = (8400, 280)
    vec_58.label = 'union rotate translate translation'
    vec_58.vector = [0, 0, 11.05]
    xform_57 = node_tree.nodes.new("GeometryNodeTransform")
    xform_57.location = (8400, 0)
    xform_57.label = 'union rotate translate'
    node_tree.links.new(xform_55.outputs["Geometry"], xform_57.inputs["Geometry"])
    node_tree.links.new(vec_58.outputs["Vector"], xform_57.inputs["Translation"])
    out_59 = node_tree.nodes.new("NodeGroupOutput")
    out_59.location = (8700, 0)
    out_59.label = "output"
    node_tree.links.new(xform_57.outputs[0], out_59.inputs[0])

    return node_tree




def setup_film_slider_3(object_name='film_slider_3'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (0, 280)
    val_2.label = 'base_1 radius'
    val_2.outputs[0].default_value = 6
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (0, 560)
    val_3.label = 'base_1 depth'
    val_3.outputs[0].default_value = 6
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 0)
    prim_1.label = 'base_1'
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 32
    val_5 = node_tree.nodes.new("ShaderNodeValue")
    val_5.location = (300, 280)
    val_5.label = 'column_y radius'
    val_5.outputs[0].default_value = 5.05
    val_6 = node_tree.nodes.new("ShaderNodeValue")
    val_6.location = (300, 560)
    val_6.label = 'column_y depth'
    val_6.outputs[0].default_value = 6
    prim_4 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_4.location = (300, 0)
    prim_4.label = 'column_y'
    node_tree.links.new(val_5.outputs["Value"], prim_4.inputs["Radius"])
    node_tree.links.new(val_6.outputs["Value"], prim_4.inputs["Depth"])
    prim_4.inputs["Vertices"].default_value = 32
    vec_8 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_8.location = (600, 280)
    vec_8.label = 'column_y position offset'
    vec_8.vector = [0, 0, 0]
    setpos_7 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_7.location = (600, 0)
    setpos_7.label = 'column_y position'
    node_tree.links.new(prim_4.outputs["Mesh"], setpos_7.inputs["Geometry"])
    node_tree.links.new(vec_8.outputs["Vector"], setpos_7.inputs["Offset"])
    bool_9 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_9.location = (900, 0)
    bool_9.label = 'difference'
    bool_9.operation = "DIFFERENCE"
    try:
        bool_9.solver = "EXACT"
    except (TypeError, ValueError):
        bool_9.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_9.inputs[0])
    node_tree.links.new(setpos_7.outputs["Geometry"], bool_9.inputs[1])
    vec_11 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_11.location = (1200, 280)
    vec_11.label = 'difference translate translation'
    vec_11.vector = [30, 30, 3.555]
    xform_10 = node_tree.nodes.new("GeometryNodeTransform")
    xform_10.location = (1200, 0)
    xform_10.label = 'difference translate'
    node_tree.links.new(bool_9.outputs["Mesh"], xform_10.inputs["Geometry"])
    node_tree.links.new(vec_11.outputs["Vector"], xform_10.inputs["Translation"])
    val_13 = node_tree.nodes.new("ShaderNodeValue")
    val_13.location = (1500, 280)
    val_13.label = 'base_1 radius'
    val_13.outputs[0].default_value = 6
    val_14 = node_tree.nodes.new("ShaderNodeValue")
    val_14.location = (1500, 560)
    val_14.label = 'base_1 depth'
    val_14.outputs[0].default_value = 6
    prim_12 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_12.location = (1500, 0)
    prim_12.label = 'base_1'
    node_tree.links.new(val_13.outputs["Value"], prim_12.inputs["Radius"])
    node_tree.links.new(val_14.outputs["Value"], prim_12.inputs["Depth"])
    prim_12.inputs["Vertices"].default_value = 32
    val_16 = node_tree.nodes.new("ShaderNodeValue")
    val_16.location = (1800, 280)
    val_16.label = 'column_y radius'
    val_16.outputs[0].default_value = 5.05
    val_17 = node_tree.nodes.new("ShaderNodeValue")
    val_17.location = (1800, 560)
    val_17.label = 'column_y depth'
    val_17.outputs[0].default_value = 6
    prim_15 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_15.location = (1800, 0)
    prim_15.label = 'column_y'
    node_tree.links.new(val_16.outputs["Value"], prim_15.inputs["Radius"])
    node_tree.links.new(val_17.outputs["Value"], prim_15.inputs["Depth"])
    prim_15.inputs["Vertices"].default_value = 32
    vec_19 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_19.location = (2100, 280)
    vec_19.label = 'column_y position offset'
    vec_19.vector = [0, 0, 0]
    setpos_18 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_18.location = (2100, 0)
    setpos_18.label = 'column_y position'
    node_tree.links.new(prim_15.outputs["Mesh"], setpos_18.inputs["Geometry"])
    node_tree.links.new(vec_19.outputs["Vector"], setpos_18.inputs["Offset"])
    bool_20 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_20.location = (2400, 0)
    bool_20.label = 'difference'
    bool_20.operation = "DIFFERENCE"
    try:
        bool_20.solver = "EXACT"
    except (TypeError, ValueError):
        bool_20.solver = "EXACT"
    node_tree.links.new(prim_12.outputs["Mesh"], bool_20.inputs[0])
    node_tree.links.new(setpos_18.outputs["Geometry"], bool_20.inputs[1])
    vec_22 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_22.location = (2700, 280)
    vec_22.label = 'difference translate translation'
    vec_22.vector = [-30, 30, 3.555]
    xform_21 = node_tree.nodes.new("GeometryNodeTransform")
    xform_21.location = (2700, 0)
    xform_21.label = 'difference translate'
    node_tree.links.new(bool_20.outputs["Mesh"], xform_21.inputs["Geometry"])
    node_tree.links.new(vec_22.outputs["Vector"], xform_21.inputs["Translation"])
    val_24 = node_tree.nodes.new("ShaderNodeValue")
    val_24.location = (3000, 280)
    val_24.label = 'base_1 radius'
    val_24.outputs[0].default_value = 6
    val_25 = node_tree.nodes.new("ShaderNodeValue")
    val_25.location = (3000, 560)
    val_25.label = 'base_1 depth'
    val_25.outputs[0].default_value = 6
    prim_23 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_23.location = (3000, 0)
    prim_23.label = 'base_1'
    node_tree.links.new(val_24.outputs["Value"], prim_23.inputs["Radius"])
    node_tree.links.new(val_25.outputs["Value"], prim_23.inputs["Depth"])
    prim_23.inputs["Vertices"].default_value = 32
    val_27 = node_tree.nodes.new("ShaderNodeValue")
    val_27.location = (3300, 280)
    val_27.label = 'column_y radius'
    val_27.outputs[0].default_value = 5.05
    val_28 = node_tree.nodes.new("ShaderNodeValue")
    val_28.location = (3300, 560)
    val_28.label = 'column_y depth'
    val_28.outputs[0].default_value = 6
    prim_26 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_26.location = (3300, 0)
    prim_26.label = 'column_y'
    node_tree.links.new(val_27.outputs["Value"], prim_26.inputs["Radius"])
    node_tree.links.new(val_28.outputs["Value"], prim_26.inputs["Depth"])
    prim_26.inputs["Vertices"].default_value = 32
    vec_30 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_30.location = (3600, 280)
    vec_30.label = 'column_y position offset'
    vec_30.vector = [0, 0, 0]
    setpos_29 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_29.location = (3600, 0)
    setpos_29.label = 'column_y position'
    node_tree.links.new(prim_26.outputs["Mesh"], setpos_29.inputs["Geometry"])
    node_tree.links.new(vec_30.outputs["Vector"], setpos_29.inputs["Offset"])
    bool_31 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_31.location = (3900, 0)
    bool_31.label = 'difference'
    bool_31.operation = "DIFFERENCE"
    try:
        bool_31.solver = "EXACT"
    except (TypeError, ValueError):
        bool_31.solver = "EXACT"
    node_tree.links.new(prim_23.outputs["Mesh"], bool_31.inputs[0])
    node_tree.links.new(setpos_29.outputs["Geometry"], bool_31.inputs[1])
    vec_33 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_33.location = (4200, 280)
    vec_33.label = 'difference translate translation'
    vec_33.vector = [30, -30, 3.555]
    xform_32 = node_tree.nodes.new("GeometryNodeTransform")
    xform_32.location = (4200, 0)
    xform_32.label = 'difference translate'
    node_tree.links.new(bool_31.outputs["Mesh"], xform_32.inputs["Geometry"])
    node_tree.links.new(vec_33.outputs["Vector"], xform_32.inputs["Translation"])
    val_35 = node_tree.nodes.new("ShaderNodeValue")
    val_35.location = (4500, 280)
    val_35.label = 'base_1 radius'
    val_35.outputs[0].default_value = 6
    val_36 = node_tree.nodes.new("ShaderNodeValue")
    val_36.location = (4500, 560)
    val_36.label = 'base_1 depth'
    val_36.outputs[0].default_value = 6
    prim_34 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_34.location = (4500, 0)
    prim_34.label = 'base_1'
    node_tree.links.new(val_35.outputs["Value"], prim_34.inputs["Radius"])
    node_tree.links.new(val_36.outputs["Value"], prim_34.inputs["Depth"])
    prim_34.inputs["Vertices"].default_value = 32
    val_38 = node_tree.nodes.new("ShaderNodeValue")
    val_38.location = (4800, 280)
    val_38.label = 'column_y radius'
    val_38.outputs[0].default_value = 5.05
    val_39 = node_tree.nodes.new("ShaderNodeValue")
    val_39.location = (4800, 560)
    val_39.label = 'column_y depth'
    val_39.outputs[0].default_value = 6
    prim_37 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_37.location = (4800, 0)
    prim_37.label = 'column_y'
    node_tree.links.new(val_38.outputs["Value"], prim_37.inputs["Radius"])
    node_tree.links.new(val_39.outputs["Value"], prim_37.inputs["Depth"])
    prim_37.inputs["Vertices"].default_value = 32
    vec_41 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_41.location = (5100, 280)
    vec_41.label = 'column_y position offset'
    vec_41.vector = [0, 0, 0]
    setpos_40 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_40.location = (5100, 0)
    setpos_40.label = 'column_y position'
    node_tree.links.new(prim_37.outputs["Mesh"], setpos_40.inputs["Geometry"])
    node_tree.links.new(vec_41.outputs["Vector"], setpos_40.inputs["Offset"])
    bool_42 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_42.location = (5400, 0)
    bool_42.label = 'difference'
    bool_42.operation = "DIFFERENCE"
    try:
        bool_42.solver = "EXACT"
    except (TypeError, ValueError):
        bool_42.solver = "EXACT"
    node_tree.links.new(prim_34.outputs["Mesh"], bool_42.inputs[0])
    node_tree.links.new(setpos_40.outputs["Geometry"], bool_42.inputs[1])
    vec_44 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_44.location = (5700, 280)
    vec_44.label = 'difference translate translation'
    vec_44.vector = [-30, -30, 3.555]
    xform_43 = node_tree.nodes.new("GeometryNodeTransform")
    xform_43.location = (5700, 0)
    xform_43.label = 'difference translate'
    node_tree.links.new(bool_42.outputs["Mesh"], xform_43.inputs["Geometry"])
    node_tree.links.new(vec_44.outputs["Vector"], xform_43.inputs["Translation"])
    vec_46 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_46.location = (6000, 280)
    vec_46.label = "base_2 size"
    vec_46.vector = [49.5, 6, 6]
    prim_45 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_45.location = (6000, 0)
    prim_45.label = 'base_2'
    node_tree.links.new(vec_46.outputs["Vector"], prim_45.inputs["Size"])
    vec_48 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_48.location = (6300, 280)
    vec_48.label = 'base_2 position offset'
    vec_48.vector = [0, 30, 3.555]
    setpos_47 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_47.location = (6300, 0)
    setpos_47.label = 'base_2 position'
    node_tree.links.new(prim_45.outputs["Mesh"], setpos_47.inputs["Geometry"])
    node_tree.links.new(vec_48.outputs["Vector"], setpos_47.inputs["Offset"])
    vec_50 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_50.location = (6600, 280)
    vec_50.label = "base_2 size"
    vec_50.vector = [49.5, 6, 6]
    prim_49 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_49.location = (6600, 0)
    prim_49.label = 'base_2'
    node_tree.links.new(vec_50.outputs["Vector"], prim_49.inputs["Size"])
    vec_52 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_52.location = (6900, 280)
    vec_52.label = 'base_2 position offset'
    vec_52.vector = [0, -30, 3.555]
    setpos_51 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_51.location = (6900, 0)
    setpos_51.label = 'base_2 position'
    node_tree.links.new(prim_49.outputs["Mesh"], setpos_51.inputs["Geometry"])
    node_tree.links.new(vec_52.outputs["Vector"], setpos_51.inputs["Offset"])
    vec_54 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_54.location = (7200, 280)
    vec_54.label = "base_2 size"
    vec_54.vector = [6, 49.5, 12]
    prim_53 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_53.location = (7200, 0)
    prim_53.label = 'base_2'
    node_tree.links.new(vec_54.outputs["Vector"], prim_53.inputs["Size"])
    vec_56 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_56.location = (7500, 280)
    vec_56.label = 'base_2 position offset'
    vec_56.vector = [30, 0, 6.555]
    setpos_55 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_55.location = (7500, 0)
    setpos_55.label = 'base_2 position'
    node_tree.links.new(prim_53.outputs["Mesh"], setpos_55.inputs["Geometry"])
    node_tree.links.new(vec_56.outputs["Vector"], setpos_55.inputs["Offset"])
    vec_58 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_58.location = (7800, 280)
    vec_58.label = "base_2 size"
    vec_58.vector = [6, 49.5, 12]
    prim_57 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_57.location = (7800, 0)
    prim_57.label = 'base_2'
    node_tree.links.new(vec_58.outputs["Vector"], prim_57.inputs["Size"])
    vec_60 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_60.location = (8100, 280)
    vec_60.label = 'base_2 position offset'
    vec_60.vector = [-30, 0, 6.555]
    setpos_59 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_59.location = (8100, 0)
    setpos_59.label = 'base_2 position'
    node_tree.links.new(prim_57.outputs["Mesh"], setpos_59.inputs["Geometry"])
    node_tree.links.new(vec_60.outputs["Vector"], setpos_59.inputs["Offset"])
    bool_61 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_61.location = (8400, 0)
    bool_61.label = 'union'
    bool_61.operation = "UNION"
    try:
        bool_61.solver = "EXACT"
    except (TypeError, ValueError):
        bool_61.solver = "EXACT"
    node_tree.links.new(xform_10.outputs["Geometry"], bool_61.inputs[1])
    node_tree.links.new(xform_21.outputs["Geometry"], bool_61.inputs[1])
    node_tree.links.new(xform_32.outputs["Geometry"], bool_61.inputs[1])
    node_tree.links.new(xform_43.outputs["Geometry"], bool_61.inputs[1])
    node_tree.links.new(setpos_47.outputs["Geometry"], bool_61.inputs[1])
    node_tree.links.new(setpos_51.outputs["Geometry"], bool_61.inputs[1])
    node_tree.links.new(setpos_55.outputs["Geometry"], bool_61.inputs[1])
    node_tree.links.new(setpos_59.outputs["Geometry"], bool_61.inputs[1])
    out_62 = node_tree.nodes.new("NodeGroupOutput")
    out_62.location = (8700, 0)
    out_62.label = "output"
    node_tree.links.new(bool_61.outputs[0], out_62.inputs[0])

    return node_tree





# Execute all parts
setup_film_slider()
setup_film_slider_2()
setup_film_slider_3()
