import bpy


def setup_tube_support(object_name='tube_support'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (0, 280)
    val_2.label = 'slider_base radius'
    val_2.outputs[0].default_value = 32.5
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (0, 560)
    val_3.label = 'slider_base depth'
    val_3.outputs[0].default_value = 3
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 0)
    prim_1.label = 'slider_base'
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 32
    vec_5 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_5.location = (300, 280)
    vec_5.label = "join_1 size"
    vec_5.vector = [40, 3, 3]
    prim_4 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_4.location = (300, 0)
    prim_4.label = 'join_1'
    node_tree.links.new(vec_5.outputs["Vector"], prim_4.inputs["Size"])
    vec_7 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_7.location = (600, 280)
    vec_7.label = 'join_1 position offset'
    vec_7.vector = [0, 19.125, 3]
    setpos_6 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_6.location = (600, 0)
    setpos_6.label = 'join_1 position'
    node_tree.links.new(prim_4.outputs["Mesh"], setpos_6.inputs["Geometry"])
    node_tree.links.new(vec_7.outputs["Vector"], setpos_6.inputs["Offset"])
    vec_9 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_9.location = (900, 280)
    vec_9.label = "join_2 size"
    vec_9.vector = [40, 3, 3]
    prim_8 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_8.location = (900, 0)
    prim_8.label = 'join_2'
    node_tree.links.new(vec_9.outputs["Vector"], prim_8.inputs["Size"])
    vec_11 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_11.location = (1200, 280)
    vec_11.label = 'join_2 position offset'
    vec_11.vector = [0, -18.875, 3]
    setpos_10 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_10.location = (1200, 0)
    setpos_10.label = 'join_2 position'
    node_tree.links.new(prim_8.outputs["Mesh"], setpos_10.inputs["Geometry"])
    node_tree.links.new(vec_11.outputs["Vector"], setpos_10.inputs["Offset"])
    vec_13 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_13.location = (1500, 280)
    vec_13.label = "border size"
    vec_13.vector = [132.875, 77.875, 3]
    prim_12 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_12.location = (1500, 0)
    prim_12.label = 'border'
    node_tree.links.new(vec_13.outputs["Vector"], prim_12.inputs["Size"])
    vec_15 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_15.location = (1800, 280)
    vec_15.label = "h_border size"
    vec_15.vector = [128, 73, 3]
    prim_14 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_14.location = (1800, 0)
    prim_14.label = 'h_border'
    node_tree.links.new(vec_15.outputs["Vector"], prim_14.inputs["Size"])
    bool_16 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_16.location = (2100, 0)
    bool_16.label = 'difference'
    bool_16.operation = "DIFFERENCE"
    try:
        bool_16.solver = "EXACT"
    except (TypeError, ValueError):
        bool_16.solver = "EXACT"
    node_tree.links.new(prim_12.outputs["Mesh"], bool_16.inputs[0])
    node_tree.links.new(prim_14.outputs["Mesh"], bool_16.inputs[1])
    vec_18 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_18.location = (2400, 280)
    vec_18.label = "border_middle_1 size"
    vec_18.vector = [10, 78, 3]
    prim_17 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_17.location = (2400, 0)
    prim_17.label = 'border_middle_1'
    node_tree.links.new(vec_18.outputs["Vector"], prim_17.inputs["Size"])
    vec_20 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_20.location = (2700, 280)
    vec_20.label = "border_middle_2 size"
    vec_20.vector = [128, 10, 3]
    prim_19 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_19.location = (2700, 0)
    prim_19.label = 'border_middle_2'
    node_tree.links.new(vec_20.outputs["Vector"], prim_19.inputs["Size"])
    bool_21 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_21.location = (3000, 0)
    bool_21.label = 'union'
    bool_21.operation = "UNION"
    try:
        bool_21.solver = "EXACT"
    except (TypeError, ValueError):
        bool_21.solver = "EXACT"
    node_tree.links.new(bool_16.outputs["Mesh"], bool_21.inputs[1])
    node_tree.links.new(prim_17.outputs["Mesh"], bool_21.inputs[1])
    node_tree.links.new(prim_19.outputs["Mesh"], bool_21.inputs[1])
    bool_22 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_22.location = (3300, 0)
    bool_22.label = 'union'
    bool_22.operation = "UNION"
    try:
        bool_22.solver = "EXACT"
    except (TypeError, ValueError):
        bool_22.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_22.inputs[1])
    node_tree.links.new(setpos_6.outputs["Geometry"], bool_22.inputs[1])
    node_tree.links.new(setpos_10.outputs["Geometry"], bool_22.inputs[1])
    node_tree.links.new(bool_21.outputs["Mesh"], bool_22.inputs[1])
    vec_24 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_24.location = (3600, 280)
    vec_24.label = "h_slider_base size"
    vec_24.vector = [40, 33.75, 8]
    prim_23 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_23.location = (3600, 0)
    prim_23.label = 'h_slider_base'
    node_tree.links.new(vec_24.outputs["Vector"], prim_23.inputs["Size"])
    bool_25 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_25.location = (3900, 0)
    bool_25.label = 'difference'
    bool_25.operation = "DIFFERENCE"
    try:
        bool_25.solver = "EXACT"
    except (TypeError, ValueError):
        bool_25.solver = "EXACT"
    node_tree.links.new(bool_22.outputs["Mesh"], bool_25.inputs[0])
    node_tree.links.new(prim_23.outputs["Mesh"], bool_25.inputs[1])
    vec_27 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_27.location = (4200, 280)
    vec_27.label = "h_cube_border size"
    vec_27.vector = [33.75, 33.75, 33.75]
    prim_26 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_26.location = (4200, 0)
    prim_26.label = 'h_cube_border'
    node_tree.links.new(vec_27.outputs["Vector"], prim_26.inputs["Size"])
    vec_29 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_29.location = (4500, 280)
    vec_29.label = 'h_cube_border rotate rotation'
    vec_29.vector = [0.0, 0.7853981633974483, 0.0]
    xform_28 = node_tree.nodes.new("GeometryNodeTransform")
    xform_28.location = (4500, 0)
    xform_28.label = 'h_cube_border rotate'
    node_tree.links.new(prim_26.outputs["Mesh"], xform_28.inputs["Geometry"])
    node_tree.links.new(vec_29.outputs["Vector"], xform_28.inputs["Rotation"])
    vec_31 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_31.location = (4800, 280)
    vec_31.label = 'h_cube_border rotate translate translation'
    vec_31.vector = [0, 0, 3]
    xform_30 = node_tree.nodes.new("GeometryNodeTransform")
    xform_30.location = (4800, 0)
    xform_30.label = 'h_cube_border rotate translate'
    node_tree.links.new(xform_28.outputs["Geometry"], xform_30.inputs["Geometry"])
    node_tree.links.new(vec_31.outputs["Vector"], xform_30.inputs["Translation"])
    bool_32 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_32.location = (5100, 0)
    bool_32.label = 'difference'
    bool_32.operation = "DIFFERENCE"
    try:
        bool_32.solver = "EXACT"
    except (TypeError, ValueError):
        bool_32.solver = "EXACT"
    node_tree.links.new(bool_25.outputs["Mesh"], bool_32.inputs[0])
    node_tree.links.new(xform_30.outputs["Geometry"], bool_32.inputs[1])
    out_33 = node_tree.nodes.new("NodeGroupOutput")
    out_33.location = (5400, 0)
    out_33.label = "output"
    node_tree.links.new(bool_32.outputs[0], out_33.inputs[0])

    return node_tree




def setup_film_slider_round(object_name='film_slider_round'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (0, 280)
    val_2.label = 'slider radius'
    val_2.outputs[0].default_value = 32.5
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (0, 560)
    val_3.label = 'slider depth'
    val_3.outputs[0].default_value = 10
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 0)
    prim_1.label = 'slider'
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 32
    vec_5 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_5.location = (300, 280)
    vec_5.label = "h_slider size"
    vec_5.vector = [48, 34, 30]
    prim_4 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_4.location = (300, 0)
    prim_4.label = 'h_slider'
    node_tree.links.new(vec_5.outputs["Vector"], prim_4.inputs["Size"])
    vec_7 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_7.location = (600, 280)
    vec_7.label = "join_1 size"
    vec_7.vector = [40.125, 3.125, 3.125]
    prim_6 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_6.location = (600, 0)
    prim_6.label = 'join_1'
    node_tree.links.new(vec_7.outputs["Vector"], prim_6.inputs["Size"])
    vec_9 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_9.location = (900, 280)
    vec_9.label = 'join_1 position offset'
    vec_9.vector = [0, 19.125, -3.5]
    setpos_8 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_8.location = (900, 0)
    setpos_8.label = 'join_1 position'
    node_tree.links.new(prim_6.outputs["Mesh"], setpos_8.inputs["Geometry"])
    node_tree.links.new(vec_9.outputs["Vector"], setpos_8.inputs["Offset"])
    vec_11 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_11.location = (1200, 280)
    vec_11.label = "join_1 size"
    vec_11.vector = [40.125, 3.125, 3.125]
    prim_10 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_10.location = (1200, 0)
    prim_10.label = 'join_1'
    node_tree.links.new(vec_11.outputs["Vector"], prim_10.inputs["Size"])
    vec_13 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_13.location = (1500, 280)
    vec_13.label = 'join_1 position offset'
    vec_13.vector = [0, -19.125, -3.5]
    setpos_12 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_12.location = (1500, 0)
    setpos_12.label = 'join_1 position'
    node_tree.links.new(prim_10.outputs["Mesh"], setpos_12.inputs["Geometry"])
    node_tree.links.new(vec_13.outputs["Vector"], setpos_12.inputs["Offset"])
    val_15 = node_tree.nodes.new("ShaderNodeValue")
    val_15.location = (1800, 280)
    val_15.label = 'h_tube_1 radius'
    val_15.outputs[0].default_value = 30.625
    val_16 = node_tree.nodes.new("ShaderNodeValue")
    val_16.location = (1800, 560)
    val_16.label = 'h_tube_1 depth'
    val_16.outputs[0].default_value = 6
    prim_14 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_14.location = (1800, 0)
    prim_14.label = 'h_tube_1'
    node_tree.links.new(val_15.outputs["Value"], prim_14.inputs["Radius"])
    node_tree.links.new(val_16.outputs["Value"], prim_14.inputs["Depth"])
    prim_14.inputs["Vertices"].default_value = 128
    vec_18 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_18.location = (2100, 280)
    vec_18.label = 'h_tube_1 position offset'
    vec_18.vector = [0, 0, 2]
    setpos_17 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_17.location = (2100, 0)
    setpos_17.label = 'h_tube_1 position'
    node_tree.links.new(prim_14.outputs["Mesh"], setpos_17.inputs["Geometry"])
    node_tree.links.new(vec_18.outputs["Vector"], setpos_17.inputs["Offset"])
    bool_19 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_19.location = (2400, 0)
    bool_19.label = 'difference'
    bool_19.operation = "DIFFERENCE"
    try:
        bool_19.solver = "EXACT"
    except (TypeError, ValueError):
        bool_19.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_19.inputs[0])
    node_tree.links.new(prim_4.outputs["Mesh"], bool_19.inputs[1])
    node_tree.links.new(setpos_8.outputs["Geometry"], bool_19.inputs[1])
    node_tree.links.new(setpos_12.outputs["Geometry"], bool_19.inputs[1])
    node_tree.links.new(setpos_17.outputs["Geometry"], bool_19.inputs[1])
    out_20 = node_tree.nodes.new("NodeGroupOutput")
    out_20.location = (2700, 0)
    out_20.label = "output"
    node_tree.links.new(bool_19.outputs[0], out_20.inputs[0])

    return node_tree





# Execute all parts
setup_tube_support()
setup_film_slider_round()
