"""Parametric **Geometry Nodes** rollers for Blender.

Where :mod:`core.roller` bakes a finished roller mesh, this module emits a
self-contained Blender script that builds a *live, parametric* Geometry Nodes
setup: a flat fold-relief block is **arrayed**, **wrapped onto a cylinder**, and
**solidified**, all driven by Group-Input sliders on the modifier — so diameter,
tile counts, relief depth and wall stay editable in the Blender viewport.

The fold relief itself (the foldcore arrangement) is computed in Python and baked
into the block mesh (it cannot be expressed in Geometry Nodes); everything that is
*geometric repetition / deformation* is done in the node tree.

Generate with :func:`generate_rollers_gn` → ``output/<name>_roller_gn.py``; run it
in Blender (``blender -b -P <name>_roller_gn.py``) to get the male + female
roller objects, each carrying the ``BellowsRoller`` node group.
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np

from . import tessellate, foldcore

#: Per-pattern block = the minimal grid that tiles seamlessly on a regular array.
#: Square patterns repeat every tile; Yoshimura's egg-crate needs a 2×2 parity
#: block; Miura's brick repeats every 2 rows.
_BLOCK_GRID = {
    "yoshimura": (2, 2),
    "miura": (2, 2),
}


def _block_grid(name: str) -> tuple[int, int]:
    return _BLOCK_GRID.get(name, (1, 1))


def flat_block(name: str):
    """Flat fold-relief block for *name* — ``(verts (N,3), faces (M,3), dx, dy)``.

    ``verts`` is the foldcore **surface** (single layer, ``z`` = relief, centred)
    of the minimal seamless tile block; ``dx``/``dy`` are the block's tiling pitch
    (mm), i.e. the array spacing that makes neighbouring copies meet.
    """
    spec = tessellate.TILE_SPECS[name]
    tx, ty = spec["tile"]
    gn, gm = _block_grid(name)
    dx = gn * spec.get("pitch_x", 1.0) * tx
    dy = gm * ty

    if name.startswith("accordion"):
        # The accordion crease cell intentionally overhangs its pitch by one
        # slant so adjacent cells share that side.  A GN roller block must be
        # exactly one pitch wide, otherwise the array overlaps and the wrap
        # diameter is computed from the wrong circumference.
        pat, dx = tessellate.tessellate_periodic(name, gn, gm)
    else:
        pat = tessellate.tessellate(name, grid=(gn, gm))

    params = tessellate.tile_params(name)
    # periodic in x so the wrapped (around) seam meets without a relief step
    pts, z, tris, _b = foldcore.build_surface(pat, params, wrap_period=dx)
    verts = np.column_stack([pts[:, 0], pts[:, 1], z])
    return verts, np.asarray(tris, np.int64), float(dx), float(dy)


def _defaults(name: str):
    """Default slider values: ``(tiles_around, tiles_along, diameter, wall)``."""
    from .roller import min_tiles_around, _CORE_WALL

    gn, gm = _block_grid(name)
    n_around = max(1, round(min_tiles_around(name) / gn))
    _gn2, m = tessellate.TILE_SPECS[name]["grid"]
    n_along = max(1, round(m / gm))
    _v, _f, dx, _dy = flat_block(name)
    diameter = n_around * dx / math.pi          # circumference / π
    return n_around, n_along, round(diameter, 2), float(_CORE_WALL)


# ---------------------------------------------------------------------------
# Blender script emission
# ---------------------------------------------------------------------------

def build_script(name: str) -> str:
    """Return a self-contained Blender Python script for the *name* GN rollers."""
    verts, faces, dx, dy = flat_block(name)
    n_around, n_along, diameter, wall = _defaults(name)
    vlist = "[" + ",".join(f"({x:.5f},{y:.5f},{z:.5f})" for x, y, z in verts) + "]"
    flist = "[" + ",".join(f"({int(a)},{int(b)},{int(c)})" for a, b, c in faces) + "]"

    return _TEMPLATE.format(
        name=name, verts=vlist, faces=flist, dx=dx, dy=dy,
        n_around=n_around, n_along=n_along, diameter=diameter, wall=wall,
    )


def generate_rollers_gn(name: str, output_dir: str | Path) -> Path:
    """Write ``<output_dir>/<name>_roller_gn.py`` and return its path."""
    out = Path(output_dir) / f"{name}_roller_gn.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_script(name))
    return out


_TEMPLATE = r'''"""Parametric Geometry Nodes rollers for the {name} bellows pattern.

Run in Blender::  blender -b -P {name}_roller_gn.py     (or open + Run Script)

Creates two objects — ``{name}_roller_male`` and ``{name}_roller_female`` — each
with a ``BellowsRoller`` Geometry Nodes modifier whose inputs stay editable:

    Diameter (mm) · Tiles around · Tiles along · Relief depth · Core wall (mm)

The female is the male's negative (Relief depth < 0) so the pair meshes like gears.
Auto-generated by bellows_diecut.core.roller_gn — do not edit by hand.
"""
import bpy, math

BLOCK_VERTS = {verts}
BLOCK_FACES = {faces}
BLOCK_DX, BLOCK_DY = {dx}, {dy}
DEF_AROUND, DEF_ALONG, DEF_DIAM, DEF_WALL = {n_around}, {n_along}, {diameter}, {wall}


def _block_mesh(obj_name):
    me = bpy.data.meshes.new(obj_name + "_block")
    me.from_pydata([list(v) for v in BLOCK_VERTS], [], [list(f) for f in BLOCK_FACES])
    me.update()
    obj = bpy.data.objects.new(obj_name, me)
    bpy.context.scene.collection.objects.link(obj)
    return obj


def _node_group():
    if "BellowsRoller" in bpy.data.node_groups:
        return bpy.data.node_groups["BellowsRoller"]
    ng = bpy.data.node_groups.new("BellowsRoller", "GeometryNodeTree")
    itf = ng.interface
    itf.new_socket("Geometry", in_out="INPUT", socket_type="NodeSocketGeometry")
    itf.new_socket("Geometry", in_out="OUTPUT", socket_type="NodeSocketGeometry")
    s_diam = itf.new_socket("Diameter", in_out="INPUT", socket_type="NodeSocketFloat")
    s_diam.default_value = DEF_DIAM; s_diam.min_value = 1.0
    s_ar = itf.new_socket("Tiles around", in_out="INPUT", socket_type="NodeSocketInt")
    s_ar.default_value = DEF_AROUND; s_ar.min_value = 1
    s_al = itf.new_socket("Tiles along", in_out="INPUT", socket_type="NodeSocketInt")
    s_al.default_value = DEF_ALONG; s_al.min_value = 1
    s_rd = itf.new_socket("Relief depth", in_out="INPUT", socket_type="NodeSocketFloat")
    s_rd.default_value = 1.0
    s_cw = itf.new_socket("Core wall", in_out="INPUT", socket_type="NodeSocketFloat")
    s_cw.default_value = DEF_WALL; s_cw.min_value = 0.1

    nd, lk = ng.nodes, ng.links
    x = 0
    def add(t, **kw):
        nonlocal x
        n = nd.new(t); n.location = (x, 0); x += 200
        for k, v in kw.items(): setattr(n, k, v)
        return n
    gin = add("NodeGroupInput"); gout = nd.new("NodeGroupOutput"); gout.location = (3200, 0)

    def mul(a, b):
        m = add("ShaderNodeMath"); m.operation = "MULTIPLY"
        _wire(lk, a, m.inputs[0]); _wire(lk, b, m.inputs[1]); return m.outputs[0]
    def sub(a, b):
        m = add("ShaderNodeMath"); m.operation = "SUBTRACT"
        _wire(lk, a, m.inputs[0]); _wire(lk, b, m.inputs[1]); return m.outputs[0]
    def add_(a, b):
        m = add("ShaderNodeMath"); m.operation = "ADD"
        _wire(lk, a, m.inputs[0]); _wire(lk, b, m.inputs[1]); return m.outputs[0]
    def div(a, b):
        m = add("ShaderNodeMath"); m.operation = "DIVIDE"
        _wire(lk, a, m.inputs[0]); _wire(lk, b, m.inputs[1]); return m.outputs[0]

    around = gin.outputs["Tiles around"]; along = gin.outputs["Tiles along"]
    circ = mul(around, BLOCK_DX)                       # circumference (mm)

    # grid of array points (around × along, spacing block_dx/dy)
    grid = add("GeometryNodeMeshGrid")
    _wire(lk, mul(sub(around, 1.0), BLOCK_DX), grid.inputs["Size X"])
    _wire(lk, mul(sub(along, 1.0), BLOCK_DY), grid.inputs["Size Y"])
    _wire(lk, around, grid.inputs["Vertices X"]); _wire(lk, along, grid.inputs["Vertices Y"])
    m2p = add("GeometryNodeMeshToPoints"); lk.new(grid.outputs["Mesh"], m2p.inputs["Mesh"])
    iop = add("GeometryNodeInstanceOnPoints")
    lk.new(m2p.outputs["Points"], iop.inputs["Points"])
    lk.new(gin.outputs["Geometry"], iop.inputs["Instance"])
    rea = add("GeometryNodeRealizeInstances"); lk.new(iop.outputs["Instances"], rea.inputs["Geometry"])
    mg1 = add("GeometryNodeMergeByDistance"); mg1.inputs["Distance"].default_value = 0.001
    lk.new(rea.outputs["Geometry"], mg1.inputs["Geometry"])

    # wrap: pos = (r·cosθ, r·sinθ, y);  θ = x·2π/circ;  r = diam/2 + z·relief_depth
    pos = add("GeometryNodeInputPosition"); sep = add("ShaderNodeSeparateXYZ")
    lk.new(pos.outputs["Position"], sep.inputs["Vector"])
    theta = mul(sep.outputs["X"], div(2 * math.pi, circ))
    r = add_(mul(sep.outputs["Z"], gin.outputs["Relief depth"]),
             div(gin.outputs["Diameter"], 2.0))
    cs = add("ShaderNodeMath"); cs.operation = "COSINE"; _wire(lk, theta, cs.inputs[0])
    sn = add("ShaderNodeMath"); sn.operation = "SINE"; _wire(lk, theta, sn.inputs[0])
    comb = add("ShaderNodeCombineXYZ")
    _wire(lk, mul(r, cs.outputs[0]), comb.inputs["X"])
    _wire(lk, mul(r, sn.outputs[0]), comb.inputs["Y"])
    lk.new(sep.outputs["Y"], comb.inputs["Z"])
    setp = add("GeometryNodeSetPosition")
    lk.new(mg1.outputs["Geometry"], setp.inputs["Geometry"])
    lk.new(comb.outputs["Vector"], setp.inputs["Position"])
    mg2 = add("GeometryNodeMergeByDistance"); mg2.inputs["Distance"].default_value = 0.05
    lk.new(setp.outputs["Geometry"], mg2.inputs["Geometry"])

    # solidify: extrude every face inward (−radial) by Core wall → closed shell
    pos2 = add("GeometryNodeInputPosition"); sep2 = add("ShaderNodeSeparateXYZ")
    lk.new(pos2.outputs["Position"], sep2.inputs["Vector"])
    rad = add("ShaderNodeCombineXYZ")
    lk.new(sep2.outputs["X"], rad.inputs["X"]); lk.new(sep2.outputs["Y"], rad.inputs["Y"])
    nrm = add("ShaderNodeVectorMath"); nrm.operation = "NORMALIZE"; lk.new(rad.outputs["Vector"], nrm.inputs[0])
    negwall = add("ShaderNodeMath"); negwall.operation = "MULTIPLY"
    lk.new(gin.outputs["Core wall"], negwall.inputs[0]); negwall.inputs[1].default_value = -1.0
    off = add("ShaderNodeVectorMath"); off.operation = "SCALE"
    lk.new(nrm.outputs["Vector"], off.inputs[0]); _wire(lk, negwall.outputs[0], off.inputs["Scale"])
    extr = add("GeometryNodeExtrudeMesh"); extr.mode = "FACES"
    lk.new(mg2.outputs["Geometry"], extr.inputs["Mesh"])
    lk.new(off.outputs["Vector"], extr.inputs["Offset"])
    shade = add("GeometryNodeSetShadeSmooth"); shade.inputs["Shade Smooth"].default_value = False
    lk.new(extr.outputs["Mesh"], shade.inputs["Geometry"])
    lk.new(shade.outputs["Geometry"], gout.inputs["Geometry"])
    return ng


def _wire(links, src, dst):
    """Link a socket *src* to input *dst*, or set a constant if *src* is a number."""
    if hasattr(src, "is_output") or hasattr(src, "links") or "Socket" in type(src).__name__:
        links.new(src, dst)
    else:
        dst.default_value = src


def _make_roller(obj_name, relief_depth):
    obj = _block_mesh(obj_name)
    md = obj.modifiers.new("BellowsRoller", "NODES")
    md.node_group = _node_group()
    for it in md.node_group.interface.items_tree:
        if getattr(it, "in_out", "") == "INPUT" and it.name == "Relief depth":
            md[it.identifier] = float(relief_depth)
    return obj


def build():
    male = _make_roller("{name}_roller_male", 1.0)
    female = _make_roller("{name}_roller_female", -1.0)
    female.location.x = (DEF_DIAM * 1.6)
    return male, female


if __name__ == "__main__":
    build()
'''


__all__ = ["flat_block", "build_script", "generate_rollers_gn"]
