"""Naranjos Halo CE level — assembly and JMS export.

This script is the final step in the Naranjos map pipeline.  It takes the
building geometry generated by ``generate_naranjos_dsl()`` and wraps it in a
**sealed world volume** (sky envelope) to produce a single valid ``bsp_world``
object ready for Halo CE's ``tool.exe`` BSP compiler.

Pipeline overview (from the halo_maps README)
---------------------------------------------
1. ``setup_scene()``                — metric units, standard collections
2. ``generate_naranjos_dsl()``      — create all building objects
   *(these two steps run in generate_dsl.py; bsp_merged is their output)*
3. ``assemble_naranjos_level()``    — **THIS FILE**
   a. Load ``bsp_merged`` into a bmesh and assign ``naranjos_wall`` material
   b. Remove any exact duplicate faces (safety pass against coplanar overlaps)
   c. Fill all open boundary edges with ``+portal`` faces to seal the buildings
   d. Add sky envelope geometry — 6-face inverted box (``+sky`` material)
   e. Triangulate the whole bmesh
   f. Write the combined bmesh to the new ``bsp_world`` object
4. ``validate_and_report()``        — sealed / manifold / normals checks
5. ``export_level()``               — write ``naranjos.jms``

Materials used
--------------
``naranjos_wall``  (slot 0)
    All building geometry (walls, slabs, campus paving) inherited from
    ``bsp_merged``.

``+portal``  (slot 1)
    Faces added to fill every door (and window) opening in the building
    walls.  Halo CE renders portal faces as invisible and passable, which
    keeps the BSP sealed while preserving the door holes.

``+sky``  (slot 2)
    All six faces of the sky envelope.  Halo CE renders these as open sky
    rather than a solid surface, but they must exist to seal the BSP.

Design notes
------------
* **No separate ground plane** — ``bsp_merged`` already contains the campus
  paving slab produced by ``generate_naranjos_dsl()``.  Adding a redundant
  z = 0 ground plane would create coplanar-overlap validation failures.

* **Two disconnected sealed volumes** — The sky envelope is a standalone
  6-face closed box that does *not* share edges with the building mesh.
  Halo CE's ``tool.exe`` BSP compiler accepts multiple disconnected sealed
  sub-volumes inside ``bsp_world``; each becomes a separate leaf cluster.

* **Outward-normals check** — The validator may flag a "false positive"
  because the sky envelope's inward-facing normals contribute a negative
  signed-volume term.  This does not prevent a successful Halo CE BSP
  compile; the flag is expected and can be ignored.

Usage
-----
Run inside Blender after ``generate_naranjos_dsl()`` has been executed::

    import importlib
    import halo_maps.naranjos.level as lvl
    importlib.reload(lvl)
    lvl.assemble_and_export()

Or from the command line::

    blender --background src/halo_maps/naranjos/blend/naranjos_dsl_updated.blend \\
        --python src/halo_maps/naranjos/level.py
"""

from __future__ import annotations

import sys
from pathlib import Path

_SRC_ROOT = Path(__file__).resolve().parent
for candidate in (_SRC_ROOT, *_SRC_ROOT.parents):
    if (candidate / "src" / "halo_maps").exists():
        _SRC_ROOT = str(candidate / "src")
        break
else:
    _SRC_ROOT = str(_SRC_ROOT)
if _SRC_ROOT not in sys.path:
    sys.path.insert(0, _SRC_ROOT)

import bpy
import bmesh

from halo_maps.export import export_jms
from halo_maps.naranjos.validate_bsp import validate

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_DIR = Path(__file__).resolve().parent

WALL_MAT    = "naranjos_wall"
FLOOR_MAT   = "naranjos_floor"
HALL_MAT    = "naranjos_hall"
ROOF_MAT    = "naranjos_roof"
WALL_RO_MAT = "naranjos_wall!"   # render-only (!) for NM-edge faces
PORTAL_MAT  = "+portal"
SKY_MAT     = "+sky"

# Material slot indices — must match the appending order in assemble_naranjos_level.
WALL_IDX    = 0   # vertical walls
FLOOR_IDX   = 1   # ground-level paving
HALL_IDX    = 2   # indoor floors / slab undersides
ROOF_IDX    = 3   # building rooftops
WALL_RO_IDX = 4   # render-only walls (NM-edge workaround — no collision, still rendered)
PORTAL_IDX  = 5   # door / window portal seals
SKY_IDX     = 6   # sky envelope

#: Default name of the building mesh produced by generate_naranjos_dsl().
BSP_SOURCE_NAME = "bsp_merged"

#: Name of the final assembled BSP object.
BSP_WORLD_NAME = "bsp_world"

#: Height of the sky box above ground in Blender units.
SKY_HEIGHT_BU: float = 40.0

#: Margin added around the campus footprint for the sky envelope walls.
GROUND_MARGIN_BU: float = 10.0

#: Default JMS output path (HEK convention: models/<name>.jms).
DEFAULT_JMS_PATH = str(_DIR / "models" / "naranjos.jms")

WALL_TIF  = str(_DIR / "materials" / "wall.tif")
FLOOR_TIF = str(_DIR / "materials" / "floor.tif")
HALL_TIF  = str(_DIR / "materials" / "hall.tif")
ROOF_TIF  = str(_DIR / "materials" / "roof.tif")

WALL_TILE_BU:  float = 1.0   # 1 BU ≈ 0.55 m per tile
FLOOR_TILE_BU: float = 1.0
HALL_TILE_BU:  float = 1.0
ROOF_TILE_BU:  float = 1.0


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _ensure_collection(name: str) -> bpy.types.Collection:
    if name not in bpy.data.collections:
        coll = bpy.data.collections.new(name)
        bpy.context.scene.collection.children.link(coll)
    return bpy.data.collections[name]


def _move_to_collection(obj: bpy.types.Object, coll_name: str) -> None:
    coll = _ensure_collection(coll_name)
    for c in list(obj.users_collection):
        c.objects.unlink(obj)
    coll.objects.link(obj)


def _ensure_material(name: str, image_path: str | None = None) -> bpy.types.Material:
    """Get or create a Blender material.  If *image_path* is given and the
    material has no node tree yet, set up a Principled-BSDF + Image-Texture
    node graph so the texture is visible in the viewport and the image is
    packed into the .blend for later JMS path resolution."""
    mat = bpy.data.materials.get(name)
    if mat is None:
        mat = bpy.data.materials.new(name)

    if image_path:
        mat.use_nodes = True
        nodes = mat.node_tree.nodes
        links = mat.node_tree.links
        # Find existing Image Texture node, or build the full node tree from scratch
        tex = next((n for n in nodes if n.type == "TEX_IMAGE"), None)
        if tex is None:
            nodes.clear()
            out  = nodes.new("ShaderNodeOutputMaterial");  out.location  = (300, 0)
            bsdf = nodes.new("ShaderNodeBsdfPrincipled");  bsdf.location = (0, 0)
            tex  = nodes.new("ShaderNodeTexImage");         tex.location  = (-300, 0)
            links.new(tex.outputs["Color"], bsdf.inputs["Base Color"])
            links.new(bsdf.outputs["BSDF"], out.inputs["Surface"])
        # Always update the image so stale materials from previous runs are fixed
        try:
            img = bpy.data.images.load(image_path, check_existing=True)
            img.colorspace_settings.name = "sRGB"
            if bpy.data.filepath:
                try:
                    img.filepath = bpy.path.relpath(image_path)
                except ValueError:
                    pass
            tex.image = img
        except Exception as exc:
            print(f"[naranjos-level] WARNING: could not load {image_path}: {exc}")

    return mat


def _generate_box_uvs(
    bm: bmesh.types.BMesh,
    tile_by_mat: "dict[int, float] | None" = None,
    default_tile: float = 1.0,
) -> None:
    """Add a 'UVMap' UV layer using planar (box) projection.

    Each face is projected onto the plane perpendicular to its dominant normal
    axis and scaled by *tile_by_mat[face.material_index]* (or *default_tile*
    when the index is not in the dict).  Existing UV layers are replaced.
    """
    for layer in list(bm.loops.layers.uv.values()):
        bm.loops.layers.uv.remove(layer)
    uv = bm.loops.layers.uv.new("UVMap")
    tile_map = tile_by_mat or {}
    for face in bm.faces:
        tile_bu = tile_map.get(face.material_index, default_tile)
        inv = 1.0 / max(tile_bu, 1e-6)
        n = face.normal.normalized()
        ax, ay, az = abs(n.x), abs(n.y), abs(n.z)
        for loop in face.loops:
            co = loop.vert.co
            if ax >= ay and ax >= az:
                loop[uv].uv = (co.y * inv, co.z * inv)
            elif ay >= ax and ay >= az:
                loop[uv].uv = (co.x * inv, co.z * inv)
            else:
                loop[uv].uv = (co.x * inv, co.y * inv)


def _classify_face_material(
    face: "bmesh.types.BMFace", z_min: float, z_max: float
) -> int:
    """Return the material index for a building face.

    Vertical faces (|n.z| < 0.5) → WALL.
    Downward-facing horizontal → HALL (underside of slabs / ceilings).
    Upward-facing horizontal by fraction of building Z range:
        bottom 10 % → FLOOR, top 35 % → ROOF, rest → HALL.
    Adjust the 0.10 / 0.65 thresholds in-place if the classification looks
    wrong in Blender Material Preview.
    """
    nz = face.normal.normalized().z
    if abs(nz) < 0.5:
        return WALL_IDX
    if nz < 0.0:
        return HALL_IDX
    z_center = sum(v.co.z for v in face.verts) / len(face.verts)
    z_frac = (z_center - z_min) / max(z_max - z_min, 0.01)
    if z_frac < 0.10:
        return FLOOR_IDX
    if z_frac > 0.65:
        return ROOF_IDX
    return HALL_IDX


def _dissolve_coplanar_nm_edges(bm: "bmesh.types.BMesh", precision: int = 4) -> int:
    """Dissolve NM edges where ALL surrounding faces are on the same plane.

    These arise when a bisect splits a face flush with an adjacent coplanar face,
    leaving 3 coplanar faces sharing one edge.  Dissolving the edge merges them
    back into a single face (then re-triangulated later).

    Returns the number of edges dissolved.
    """
    def _pk(face):
        n = face.normal.normalized()
        if (n.x, n.y, n.z) < (0.0, 0.0, 0.0):
            n.negate()
        d   = -n.dot(face.verts[0].co)
        p   = 10 ** precision
        return (round(n.x * p), round(n.y * p), round(n.z * p), round(d * p))

    bm.edges.ensure_lookup_table()
    to_dissolve = [
        e for e in bm.edges
        if len(e.link_faces) > 2 and len({_pk(f) for f in e.link_faces}) == 1
    ]
    if not to_dissolve:
        return 0
    bmesh.ops.dissolve_edges(bm, edges=to_dissolve,
                             use_verts=False, use_face_split=False)
    bm.edges.ensure_lookup_table()
    bm.faces.ensure_lookup_table()
    return len(to_dissolve)


def _mark_nm_wall_faces_readonly(bm: "bmesh.types.BMesh") -> int:
    """Mark wall faces touching remaining NM edges as render-only (WALL_RO_IDX).

    After back-to-back and coplanar fixes, the remaining NM edges come from
    unavoidable 3-way staircase/wall junctions.  Assigning 'naranjos_wall!'
    (render-only, symbol '!') to those faces tells tool.exe to exclude them
    from collision NM checking while keeping them visible.

    This is a workaround for testing.  Production fix requires geometry redesign.

    Returns the number of faces re-marked.
    """
    bm.edges.ensure_lookup_table()
    bm.faces.ensure_lookup_table()

    nm_wall_faces: set = set()
    for e in bm.edges:
        if len(e.link_faces) > 2:
            for f in e.link_faces:
                if f.material_index == WALL_IDX:
                    nm_wall_faces.add(f)

    for f in nm_wall_faces:
        f.material_index = WALL_RO_IDX
    return len(nm_wall_faces)


def _load_source_into_bm(
    source: bpy.types.Object,
) -> bmesh.types.BMesh:
    """Evaluate *source* and load it into a fresh BMesh with world matrix applied.

    The caller owns the returned BMesh and must call ``bm.free()`` when done.
    """
    bpy.context.view_layer.update()
    depsgraph = bpy.context.evaluated_depsgraph_get()
    eval_obj  = source.evaluated_get(depsgraph)
    eval_mesh = eval_obj.to_mesh()

    bm = bmesh.new()
    bm.from_mesh(eval_mesh)
    eval_obj.to_mesh_clear()

    # Apply world matrix so the mesh is in world space.
    mat = source.matrix_world
    for v in bm.verts:
        v.co = mat @ v.co

    return bm


def _delete_duplicate_faces(bm: bmesh.types.BMesh, precision: int = 5) -> int:
    """Remove exact duplicate faces (same rounded vertex coordinate set).

    Runs a round-coordinate keying pass identical to the one already done
    inside ``_create_merged_bsp`` in ``generate_dsl.py``; kept here as a
    safety net for any duplicates introduced during subsequent merges.

    Returns the number of faces removed.
    """
    bm.faces.ensure_lookup_table()
    seen: dict = {}
    dupes: list = []
    for face in bm.faces:
        key = tuple(sorted(
            (round(v.co.x, precision), round(v.co.y, precision), round(v.co.z, precision))
            for v in face.verts
        ))
        if key in seen:
            dupes.append(face)
        else:
            seen[key] = face
    if dupes:
        bmesh.ops.delete(bm, geom=dupes, context="FACES")
        bm.faces.ensure_lookup_table()
    return len(dupes)


def _fix_coplanar_overlaps(
    bm: bmesh.types.BMesh,
    precision: int = 5,
    wall_mat_index: int | None = None,
    _skip_normal_update: bool = False,
) -> int:
    """Remove faces that overlap a coplanar neighbour using Sutherland-Hodgman clipping.

    For each coplanar pair (A, B) with no shared vertices, compute the 2-D
    intersection area.  If the overlap is significant (> 1 % of the smaller
    face's area), delete the smaller face.

    This replaces the old ``_all_verts_inside`` containment check, which
    required ALL vertices of B to be strictly inside A and therefore missed
    the common case where a small wall-cap triangle partially overlaps a
    larger union-fill triangle.

    Returns the number of faces removed.
    """

    # ── 2-D helpers ──────────────────────────────────────────────────────────

    def _poly_area(pts):
        """Signed area of a 2-D polygon (shoelace)."""
        a = 0.0
        n = len(pts)
        for i in range(n):
            x0, y0 = pts[i]
            x1, y1 = pts[(i + 1) % n]
            a += x0 * y1 - x1 * y0
        return a * 0.5

    def _line_isect(p1, p2, p3, p4):
        """Intersection of line p1→p2 with line p3→p4."""
        x1, y1 = p1;  x2, y2 = p2;  x3, y3 = p3;  x4, y4 = p4
        den = (x1 - x2) * (y3 - y4) - (y1 - y2) * (x3 - x4)
        if abs(den) < 1e-12:
            return p2
        px = ((x1 * y2 - y1 * x2) * (x3 - x4) - (x1 - x2) * (x3 * y4 - y3 * x4)) / den
        py = ((x1 * y2 - y1 * x2) * (y3 - y4) - (y1 - y2) * (x3 * y4 - y3 * x4)) / den
        return px, py

    def _inside_edge(p, a, b, ccw):
        """Return True if point p is inside the half-plane defined by edge a→b."""
        cross = (b[0] - a[0]) * (p[1] - a[1]) - (b[1] - a[1]) * (p[0] - a[0])
        return cross >= -1e-9 if ccw else cross <= 1e-9

    def _convex_clip(subject, clip):
        """Sutherland-Hodgman clipping; handles both CCW and CW clip polygons."""
        output = list(subject)
        ccw = _poly_area(clip) >= 0      # ← match winding of clip polygon
        n = len(clip)
        for i in range(n):
            if not output:
                break
            a = clip[(i - 1) % n]
            b = clip[i]
            inp = output
            output = []
            prev = inp[-1]
            for cur in inp:
                cur_in  = _inside_edge(cur,  a, b, ccw)
                prev_in = _inside_edge(prev, a, b, ccw)
                if cur_in:
                    if not prev_in:
                        output.append(_line_isect(prev, cur, a, b))
                    output.append(cur)
                elif prev_in:
                    output.append(_line_isect(prev, cur, a, b))
                prev = cur
        return output

    def _project(face):
        """Project face verts to 2-D by dropping the dominant normal axis."""
        n = face.normal.normalized()
        axis = max(range(3), key=lambda i: abs(n[i]))
        pts = []
        for v in face.verts:
            c = v.co
            if axis == 0:    pts.append((c.y, c.z))
            elif axis == 1:  pts.append((c.x, c.z))
            else:            pts.append((c.x, c.y))
        return pts

    def _plane_key(face):
        n = face.normal.normalized()
        if (n.x, n.y, n.z) < (0.0, 0.0, 0.0):
            n.negate()
        d = -n.dot(face.verts[0].co)
        p = 10 ** precision
        return (round(n.x * p), round(n.y * p), round(n.z * p), round(d * p))

    # ── Group faces by plane ──────────────────────────────────────────────────

    bm.faces.ensure_lookup_table()
    if not _skip_normal_update:
        bm.normal_update()
    groups: dict = {}
    for face in bm.faces:
        if len(face.verts) != 3:
            continue
        if wall_mat_index is not None and face.material_index != wall_mat_index:
            continue
        groups.setdefault(_plane_key(face), []).append(face)

    # ── Detect overlapping pairs; mark smaller for deletion ──────────────────

    to_delete: set = set()
    for faces in groups.values():
        if len(faces) < 2:
            continue
        # Pre-compute projections and areas
        proj = {f: _project(f) for f in faces}
        area = {f: abs(_poly_area(proj[f])) for f in faces}

        for i, a in enumerate(faces):
            if a in to_delete:
                continue
            pts_a = proj[a]
            area_a = area[a]
            if area_a < 1e-10:
                to_delete.add(a)
                continue
            for b in faces[i + 1:]:
                if b in to_delete:
                    continue
                # Skip pairs that share 2+ vertices (adjacent tiles / back-to-back walls)
                if sum(1 for v in a.verts if v in set(b.verts)) >= 2:
                    continue
                pts_b = proj[b]
                area_b = area[b]
                if area_b < 1e-10:
                    to_delete.add(b)
                    continue
                # Compute overlap via Sutherland-Hodgman
                clipped = _convex_clip(pts_a, pts_b)
                if len(clipped) < 3:
                    continue
                overlap = abs(_poly_area(clipped))
                if overlap < 1e-8:
                    continue
                # Delete the smaller face (the one more likely to be redundant)
                if area_a <= area_b:
                    to_delete.add(a)
                    break  # a is gone; move to next a
                else:
                    to_delete.add(b)

    if not to_delete:
        return 0

    # ── Safety check: prune to_delete to avoid unfillable open-path holes ────
    # Horizontal faces (|n.z| > 0.9) are ceiling/floor fills produced by
    # holes_fill in _union_horizontal_faces.  They are redundant fills, not
    # structural walls, so we bypass the safety check for them — any open
    # boundary chains they leave are patched by _fill_open_boundary_paths.
    # Vertical faces (structural walls) still go through the full safety check.
    HORIZ_Z = 0.9  # |n.z| threshold for "horizontal"

    horiz_delete: set = set()  # bypass safety check
    vert_delete: set = set()
    for _f in to_delete:
        if abs(_f.normal.normalized().z) > HORIZ_Z:
            horiz_delete.add(_f)
        else:
            vert_delete.add(_f)

    # Apply safety check only to the vertical subset.
    from collections import defaultdict as _dd

    safe_delete: set = set(vert_delete)

    for _guard in range(len(vert_delete) + 1):
        # Compute combined boundary edge-vertex degree map for vertical faces only.
        # Faces in horiz_delete are treated as "will be deleted" so they do NOT
        # count as surviving neighbours when computing remaining.
        all_deleting = safe_delete | horiz_delete
        deg: dict = _dd(int)
        edge_owner: dict = {}  # edge → face in safe_delete that contributes it
        for face in safe_delete:
            for e in face.edges:
                remaining = sum(1 for lf in e.link_faces if lf not in all_deleting)
                if remaining == 1:
                    deg[e.verts[0]] += 1
                    deg[e.verts[1]] += 1
                    edge_owner[e] = face

        open_verts = [v for v, d in deg.items() if d == 1]
        if not open_verts:
            break  # all would-be-boundary edges form closed loops → safe

        # Remove the face owning the first problematic (degree-1) edge.
        culprit = None
        for v in open_verts:
            for e, f in edge_owner.items():
                if v in e.verts and f in safe_delete:
                    culprit = f
                    break
            if culprit:
                break
        if culprit:
            safe_delete.discard(culprit)
        else:
            break  # can't improve further

    all_delete = safe_delete | horiz_delete
    if all_delete:
        bmesh.ops.delete(bm, geom=list(all_delete), context="FACES")
        bm.faces.ensure_lookup_table()
    return len(all_delete)


def _fix_back_to_back_nm_edges(bm: bmesh.types.BMesh) -> int:
    """Remove duplicate wall faces that create back-to-back NM edges.

    When two buildings share a wall plane, ``remove_doubles`` merges their
    boundary vertices so their wall triangles share edges → non-manifold
    (3+ faces per edge).  Specifically: building A generates wall faces with
    normal pointing *away* from A (canonical direction) and building B
    generates wall faces at the same plane pointing *away* from B (the opposite
    direction = anti-canonical).  After the vertex merge they share edges.

    Strategy
    --------
    1. Find every NM edge whose link_faces have *both* a canonical group
       (normal (x,y,z) ≥ (0,0,0)) and an anti-canonical group.
    2. Collect every anti-canonical face that participates in at least one such
       NM edge.  These are the "duplicate" wall faces from building B.
    3. Delete them in one go, leaving closed boundary loops that the caller
       fills with portal faces.

    Returns the number of faces deleted.
    """
    bm.verts.ensure_lookup_table()
    bm.edges.ensure_lookup_table()
    bm.faces.ensure_lookup_table()

    def _is_canonical(face: bmesh.types.BMFace) -> bool:
        n = face.normal.normalized()
        return (n.x, n.y, n.z) >= (0.0, 0.0, 0.0)

    to_delete: set = set()

    for e in bm.edges:
        if len(e.link_faces) < 3:
            continue
        link = list(e.link_faces)
        has_canon = any(_is_canonical(f) for f in link)
        has_anti  = any(not _is_canonical(f) for f in link)
        if has_canon and has_anti:
            for f in link:
                if not _is_canonical(f):
                    to_delete.add(f)

    if not to_delete:
        return 0

    bmesh.ops.delete(bm, geom=list(to_delete), context="FACES")
    bm.verts.ensure_lookup_table()
    bm.edges.ensure_lookup_table()
    bm.faces.ensure_lookup_table()
    bm.normal_update()
    return len(to_delete)


def _fill_boundary_with_portal(bm: bmesh.types.BMesh) -> int:
    """Fill every open boundary-edge loop with a face, assign PORTAL_IDX.

    Uses ``bmesh.ops.holes_fill`` which finds closed loops of boundary edges
    and inserts one spanning face per loop.  Each new face gets material slot
    ``PORTAL_IDX`` so Halo CE treats the opening as a portal (invisible,
    passable) rather than a solid wall.

    Returns the number of portal faces added.
    """
    bm.edges.ensure_lookup_table()
    boundary = [e for e in bm.edges if len(e.link_faces) < 2]
    if not boundary:
        return 0

    result = bmesh.ops.holes_fill(bm, edges=boundary, sides=0)
    new_faces = result.get("faces", [])
    for f in new_faces:
        f.material_index = PORTAL_IDX
    return len(new_faces)


def _fill_open_boundary_paths(bm: bmesh.types.BMesh) -> int:
    """Patch open boundary-edge chains that ``holes_fill`` cannot close.

    When a coplanar face is deleted its edges may leave 3 boundary edges that
    form a *path* (two endpoint vertices, no closed loop).  ``holes_fill``
    requires a closed loop; it silently skips open paths.

    For each such open path we add wall triangles to close the gap:
    * Walk the boundary chain from one endpoint to the other collecting
      the ordered vertex list V = [v0, v1, …, vN].
    * Triangulate the fan V[0]-V[i]-V[i+1] for i in 1..N-1 and assign
      WALL_IDX to each new triangle.

    Returns the number of faces added.
    """
    bm.verts.ensure_lookup_table()
    bm.edges.ensure_lookup_table()

    boundary_edges = [e for e in bm.edges if len(e.link_faces) < 2]
    if not boundary_edges:
        return 0

    # Build adjacency: vert → list of boundary-edge neighbours
    from collections import defaultdict
    adj: dict = defaultdict(list)
    for e in boundary_edges:
        a, b = e.verts
        adj[a].append(b)
        adj[b].append(a)

    # Find connected components of boundary-edge graph
    visited_verts: set = set()
    components: list = []
    for start in adj:
        if start in visited_verts:
            continue
        comp_verts: set = set()
        stack = [start]
        while stack:
            v = stack.pop()
            if v in comp_verts:
                continue
            comp_verts.add(v)
            stack.extend(nb for nb in adj[v] if nb not in comp_verts)
        visited_verts |= comp_verts
        components.append(comp_verts)

    n_added = 0
    for comp in components:
        # Degree-1 vertices are endpoints of an open chain.
        endpoints = [v for v in comp if len(adj[v]) == 1]
        if not endpoints:
            continue  # closed loop — holes_fill handles it

        # Walk the chain from one endpoint to the other.
        start = endpoints[0]
        chain: list = [start]
        prev = None
        cur = start
        while True:
            nbs = [nb for nb in adj[cur] if nb is not prev]
            if not nbs:
                break
            nxt = nbs[0]
            chain.append(nxt)
            prev, cur = cur, nxt
            if len(adj[cur]) == 1 and cur is not start:
                break  # reached other endpoint

        if len(chain) < 3:
            continue

        # Fan-triangulate the chain polygon.
        anchor = chain[0]
        for i in range(1, len(chain) - 1):
            v0 = anchor
            v1 = chain[i]
            v2 = chain[i + 1]
            try:
                face = bm.faces.new([v0, v1, v2])
                face.material_index = WALL_IDX
                n_added += 1
            except ValueError:
                pass  # face already exists

    if n_added:
        bm.faces.ensure_lookup_table()
        bm.normal_update()
    return n_added


def _add_sky_envelope(
    bm: bmesh.types.BMesh,
    x0: float, x1: float,
    y0: float, y1: float,
    z_bot: float, z_top: float,
) -> None:
    """Append a 6-face sky envelope with inward-facing normals to *bm*.

    The envelope is a closed box large enough to surround the entire campus.
    All six faces are assigned ``SKY_IDX`` so that Halo CE renders them as
    open sky.  Normals are flipped inward (toward the campus interior) as
    required by Halo CE's BSP convention.

    The new geometry is appended to *bm* without merging vertices with
    existing geometry — the sky envelope forms its own separate sealed volume.
    """
    v000 = bm.verts.new((x0, y0, z_bot))
    v100 = bm.verts.new((x1, y0, z_bot))
    v110 = bm.verts.new((x1, y1, z_bot))
    v010 = bm.verts.new((x0, y1, z_bot))
    v001 = bm.verts.new((x0, y0, z_top))
    v101 = bm.verts.new((x1, y0, z_top))
    v111 = bm.verts.new((x1, y1, z_top))
    v011 = bm.verts.new((x0, y1, z_top))

    # 6 faces with CCW winding (outward normals initially)
    sky_faces = [
        bm.faces.new([v001, v011, v111, v101]),  # top
        bm.faces.new([v000, v100, v110, v010]),  # bottom
        bm.faces.new([v000, v001, v101, v100]),  # front  (y = y0)
        bm.faces.new([v110, v111, v011, v010]),  # back   (y = y1)
        bm.faces.new([v000, v010, v011, v001]),  # left   (x = x0)
        bm.faces.new([v100, v101, v111, v110]),  # right  (x = x1)
    ]

    # Flip inward — Halo CE requires normals to face the playable area.
    bmesh.ops.reverse_faces(bm, faces=sky_faces)

    for f in sky_faces:
        f.material_index = SKY_IDX


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def assemble_naranjos_level(
    bsp_source_name: str = BSP_SOURCE_NAME,
    output_name: str = BSP_WORLD_NAME,
    sky_height_bu: float = SKY_HEIGHT_BU,
    ground_margin_bu: float = GROUND_MARGIN_BU,
) -> bpy.types.Object | None:
    """Build the final ``bsp_world`` object from buildings + sky envelope.

    All mesh operations use bmesh directly, avoiding ``bpy.ops.object.join``
    and its implicit vertex-merge semantics.

    Sealing strategy
    ~~~~~~~~~~~~~~~~
    * Building door / window openings are filled with ``+portal`` faces so
      that ``bsp_merged`` itself becomes a sealed manifold.
    * A sky envelope (closed box, inward normals) is appended as a second
      disconnected sealed volume.
    * No separate ground plane is created: ``bsp_merged`` already includes
      the campus paving slab generated by ``generate_naranjos_dsl()``.

    Parameters
    ----------
    bsp_source_name:
        Name of the merged building object created by ``generate_naranjos_dsl()``.
    output_name:
        Name for the assembled, ready-to-export BSP object.
    sky_height_bu:
        Minimum top of the sky envelope above z = 0 (Blender units).
    ground_margin_bu:
        Space added around the campus bounding box for the sky envelope walls.

    Returns
    -------
    The assembled ``bsp_world`` object, or ``None`` if the source was missing.
    """
    source = bpy.data.objects.get(bsp_source_name)
    if source is None:
        print(
            f"[naranjos-level] ERROR: '{bsp_source_name}' not found. "
            "Run generate_naranjos_dsl() first."
        )
        return None

    # ── 1. Load bsp_merged into a working bmesh ────────────────────────────
    bm = _load_source_into_bm(source)
    bm.verts.ensure_lookup_table()
    bm.edges.ensure_lookup_table()
    bm.faces.ensure_lookup_table()
    print(
        f"[naranjos-level] bsp_merged loaded: "
        f"{len(bm.verts)} verts, {len(bm.faces)} faces"
    )

    # ── 2. Assign WALL_IDX to every face ──────────────────────────────────
    for f in bm.faces:
        f.material_index = WALL_IDX

    # ── 2b. Fix anti-parallel back-to-back NM edges ───────────────────────
    n_btb = _fix_back_to_back_nm_edges(bm)
    if n_btb:
        print(f"[naranjos-level] Removed {n_btb} back-to-back NM face(s)")

    # ── 3. Safety: remove any exact duplicate faces ────────────────────────
    n_dup = _delete_duplicate_faces(bm)
    if n_dup:
        print(f"[naranjos-level] Removed {n_dup} duplicate faces")

    # ── 4. Fill open boundary edges with +portal faces ────────────────────
    bm.edges.ensure_lookup_table()
    n_boundary_before = sum(1 for e in bm.edges if len(e.link_faces) < 2)
    print(f"[naranjos-level] Boundary edges before portal fill: {n_boundary_before}")

    n_portal = _fill_boundary_with_portal(bm)
    print(f"[naranjos-level] Portal faces added: {n_portal}")

    bm.edges.ensure_lookup_table()
    n_boundary_after = sum(1 for e in bm.edges if len(e.link_faces) < 2)
    if n_boundary_after:
        print(
            f"[naranjos-level] WARNING: {n_boundary_after} boundary edges remain "
            "after portal fill — complex topology or non-planar loops detected."
        )
    else:
        print("[naranjos-level] Buildings sealed ✓")

    # ── 5. Compute campus bounding box from the (now clean) building mesh ──
    xs = [v.co.x for v in bm.verts]
    ys = [v.co.y for v in bm.verts]
    zs = [v.co.z for v in bm.verts]
    x_min, x_max = min(xs), max(xs)
    y_min, y_max = min(ys), max(ys)
    z_min, z_max = min(zs), max(zs)
    print(
        f"[naranjos-level] Campus bounds: "
        f"X=[{x_min:.2f}, {x_max:.2f}]  "
        f"Y=[{y_min:.2f}, {y_max:.2f}]  "
        f"Z=[{z_min:.2f}, {z_max:.2f}] BU"
    )

    # ── 6. Sky envelope parameters ─────────────────────────────────────────
    gx0 = x_min - ground_margin_bu
    gx1 = x_max + ground_margin_bu
    gy0 = y_min - ground_margin_bu
    gy1 = y_max + ground_margin_bu
    sky_top = max(z_max + 5.0, float(sky_height_bu))
    sky_bot = z_min - 1.0      # 1 BU below the lowest building geometry

    print(
        f"[naranjos-level] Sky envelope: "
        f"X=[{gx0:.1f}, {gx1:.1f}]  "
        f"Y=[{gy0:.1f}, {gy1:.1f}]  "
        f"Z=[{sky_bot:.1f}, {sky_top:.1f}]  "
        f"(height={sky_top - sky_bot:.1f} BU)"
    )

    # ── 7. Append sky envelope geometry ───────────────────────────────────
    _add_sky_envelope(bm, gx0, gx1, gy0, gy1, sky_bot, sky_top)

    # ── 8. Triangulate everything ─────────────────────────────────────────
    bm.faces.ensure_lookup_table()
    bmesh.ops.triangulate(bm, faces=bm.faces)
    bm.normal_update()   # ← required before any normal-based grouping

    # ── 8a. Dissolve coplanar NM edges ────────────────────────────────────
    n_cp_nm = _dissolve_coplanar_nm_edges(bm)
    if n_cp_nm:
        print(f"[naranjos-level] Dissolved {n_cp_nm} coplanar NM edge(s)")
        ngons = [f for f in bm.faces if len(f.verts) > 3]
        if ngons:
            bmesh.ops.triangulate(bm, faces=ngons)
        bm.normal_update()

    # ── 8b. Remove coplanar overlapping faces introduced by triangulation ──
    # Only consider wall faces (slot 0); portals and sky are intentional quads.
    n_overlap = _fix_coplanar_overlaps(bm, wall_mat_index=WALL_IDX)
    if n_overlap:
        print(f"[naranjos-level] Removed {n_overlap} coplanar-overlap faces")
        # Re-seal any boundary edges that coplanar removal may have opened.
        bm.edges.ensure_lookup_table()
        n_new_boundary = sum(1 for e in bm.edges if len(e.link_faces) < 2)
        if n_new_boundary:
            n_resealed = _fill_boundary_with_portal(bm)
            print(f"[naranjos-level] Re-sealed {n_resealed} portal(s) after coplanar fix")
            # Triangulate the newly added portal faces (holes_fill creates ngons)
            bm.faces.ensure_lookup_table()
            new_portal_ngons = [
                f for f in bm.faces
                if f.material_index == PORTAL_IDX and len(f.verts) > 3
            ]
            if new_portal_ngons:
                bmesh.ops.triangulate(bm, faces=new_portal_ngons)
                print(
                    f"[naranjos-level] Triangulated {len(new_portal_ngons)} new portal ngon(s)"
                )
    else:
        print("[naranjos-level] No coplanar overlaps found ✓")

    # ── 8c. Fix any T-junctions introduced by portal-fill triangulation ───────
    # The ngon portals created by _fill_boundary_with_portal are triangulated
    # in steps 8 and 8b.  Those new diagonal edges may pass through existing
    # vertices, creating T-junctions not present in bsp_merged.  Run the same
    # targeted T-junction splitter used in generate_dsl to clean them up, then
    # re-triangulate any ngons it creates.
    from halo_maps.naranjos.generate_dsl import (
        _fix_t_junctions_targeted,
        _fix_t_junctions_nonmanifold,
        MERGE_DISTANCE_BU as _MERGE_DIST,
    )
    total_tj_fixed = 0
    for _pass in range(5):
        bm.verts.ensure_lookup_table()
        bm.edges.ensure_lookup_table()
        bm.faces.ensure_lookup_table()
        n_tj1 = _fix_t_junctions_targeted(bm)
        if n_tj1:
            bmesh.ops.remove_doubles(bm, verts=bm.verts, dist=_MERGE_DIST)
        n_tj2 = _fix_t_junctions_nonmanifold(bm)
        if n_tj2:
            bmesh.ops.remove_doubles(bm, verts=bm.verts, dist=_MERGE_DIST)
        total_tj_fixed += n_tj1 + n_tj2
        if not n_tj1 and not n_tj2:
            break
    # Re-triangulate any ngons created by edge splits above.
    bm.faces.ensure_lookup_table()
    ngons = [f for f in bm.faces if len(f.verts) > 3]
    if ngons:
        bmesh.ops.triangulate(bm, faces=ngons)
        print(f"[naranjos-level] Re-triangulated {len(ngons)} ngon(s) after T-junction fix")
    if total_tj_fixed:
        print(f"[naranjos-level] T-junction fix: {total_tj_fixed} split(s) total")
    else:
        print("[naranjos-level] No T-junctions in bsp_world ✓")

    # ── 8d. Final seal + coplanar cleanup after T-junction re-triangulation ───
    # Steps 8b/8c can introduce new boundary edges (from bisect_plane cuts that
    # don't form closed loops) and new coplanar overlaps (from new diagonals
    # landing inside existing coplanar triangles).  Run one last fix pass.
    bm.edges.ensure_lookup_table()
    n_final_boundary = sum(1 for e in bm.edges if len(e.link_faces) < 2)
    if n_final_boundary:
        n_final_portal = _fill_boundary_with_portal(bm)
        print(f"[naranjos-level] Final re-seal: {n_final_portal} portal(s) added")
        # Triangulate any new portal ngons
        bm.faces.ensure_lookup_table()
        new_ngons = [
            f for f in bm.faces
            if f.material_index == PORTAL_IDX and len(f.verts) > 3
        ]
        if new_ngons:
            bmesh.ops.triangulate(bm, faces=new_ngons)

    bm.normal_update()
    n_final_overlap = _fix_coplanar_overlaps(bm, wall_mat_index=WALL_IDX)
    if n_final_overlap:
        print(f"[naranjos-level] Final coplanar cleanup: removed {n_final_overlap} face(s)")
        # Re-seal anything opened by this final cleanup
        bm.edges.ensure_lookup_table()
        n_post = sum(1 for e in bm.edges if len(e.link_faces) < 2)
        if n_post:
            n_post_portal = _fill_boundary_with_portal(bm)
            print(f"[naranjos-level] Post-cleanup re-seal: {n_post_portal} portal(s)")
            bm.faces.ensure_lookup_table()
            post_ngons = [
                f for f in bm.faces
                if f.material_index == PORTAL_IDX and len(f.verts) > 3
            ]
            if post_ngons:
                bmesh.ops.triangulate(bm, faces=post_ngons)
    else:
        print("[naranjos-level] No residual coplanar overlaps ✓")

    # ── 8e. Report remaining NM edges (back-to-back walls) ────────────────
    # NM edges from adjacent buildings sharing wall planes are resolved at the
    # generate_dsl level (see generate_dsl._remove_back_to_back_walls).
    # Late coplanar NM dissolve: portal sealing / triangulation can create a few
    # coplanar overlapping faces (portal-fill coincident with a wall face).
    bm.edges.ensure_lookup_table()
    n_nm = sum(1 for e in bm.edges if len(e.link_faces) > 2)
    if n_nm:
        n_cp2 = _dissolve_coplanar_nm_edges(bm)
        if n_cp2:
            bm.faces.ensure_lookup_table()
            ngons = [f for f in bm.faces if len(f.verts) > 3]
            if ngons:
                bmesh.ops.triangulate(bm, faces=ngons)
            bm.normal_update()
            bm.edges.ensure_lookup_table()
            n_nm = sum(1 for e in bm.edges if len(e.link_faces) > 2)
            print(f"[naranjos-level] Dissolved {n_cp2} late coplanar NM edge(s)")

    # Classify remaining NM edges: only those whose 3+ faces are ALL collideable
    # (not +portal / +sky / render-only) are real tool.exe "couldn't update edge"
    # errors.  An edge with 2 collideable + 1 portal face is manifold for
    # collision (tool.exe processes portals separately), so it is harmless.
    if n_nm:
        coll_nm = 0
        for e in bm.edges:
            if len(e.link_faces) <= 2:
                continue
            coll_faces = sum(
                1 for f in e.link_faces
                if f.material_index not in (PORTAL_IDX, SKY_IDX, WALL_RO_IDX)
            )
            if coll_faces > 2:
                coll_nm += 1
        if coll_nm:
            print(f"[naranjos-level] WARNING: {coll_nm} collideable NM edge(s) remain "
                  f"(of {n_nm} total) — real tool.exe errors")
        else:
            print(f"[naranjos-level] {n_nm} NM edge(s) remain, all on portal/sky/"
                  f"render-only faces → harmless for tool.exe collision ✓")
    else:
        print("[naranjos-level] No NM edges ✓")

    n_verts = len(bm.verts)
    n_faces = len(bm.faces)
    print(
        f"[naranjos-level] '{output_name}' assembled: "
        f"{n_verts} verts, {n_faces} triangles"
    )

    # ── 8f. Hide source mesh so it doesn't overlap bsp_world in the viewport ──
    src_obj = bpy.data.objects.get(bsp_source_name)
    if src_obj is not None:
        src_obj.hide_viewport = True
        src_obj.hide_render   = True

    # ── 9. Write bmesh into a new Mesh datablock ───────────────────────────
    # Remove any stale bsp_world from previous runs.
    old = bpy.data.objects.get(output_name)
    if old is not None:
        bpy.data.objects.remove(old, do_unlink=True)
    # Remove stale mesh datablock with the same name, if any.
    old_mesh = bpy.data.meshes.get(output_name)
    if old_mesh is not None:
        bpy.data.meshes.remove(old_mesh)

    result_mesh = bpy.data.meshes.new(output_name)
    bm.to_mesh(result_mesh)
    bm.free()
    result_mesh.update()

    # ── 10. Assign material slots in index order ───────────────────────────
    #   0 WALL_IDX    → naranjos_wall    (vertical walls)
    #   1 FLOOR_IDX   → naranjos_floor   (ground-level paving)
    #   2 HALL_IDX    → naranjos_hall    (indoor floors / slab undersides)
    #   3 ROOF_IDX    → naranjos_roof    (building rooftops)
    #   4 WALL_RO_IDX → naranjos_wall!   (render-only, NM-edge workaround)
    #   5 PORTAL_IDX  → +portal
    #   6 SKY_IDX     → +sky
    import os as _os
    result_mesh.materials.append(_ensure_material(WALL_MAT,    image_path=WALL_TIF  if _os.path.isfile(WALL_TIF)  else None))
    result_mesh.materials.append(_ensure_material(FLOOR_MAT,   image_path=FLOOR_TIF if _os.path.isfile(FLOOR_TIF) else None))
    result_mesh.materials.append(_ensure_material(HALL_MAT,    image_path=HALL_TIF  if _os.path.isfile(HALL_TIF)  else None))
    result_mesh.materials.append(_ensure_material(ROOF_MAT,    image_path=ROOF_TIF  if _os.path.isfile(ROOF_TIF)  else None))
    result_mesh.materials.append(_ensure_material(WALL_RO_MAT, image_path=WALL_TIF  if _os.path.isfile(WALL_TIF)  else None))
    result_mesh.materials.append(_ensure_material(PORTAL_MAT))
    result_mesh.materials.append(_ensure_material(SKY_MAT))

    # ── 11. Create and link the bsp_world object ───────────────────────────
    # Created BEFORE the read-back so that step 9b can use the evaluator
    # (eval_obj.to_mesh()), the same code-path validate_bsp uses.
    bsp_obj = bpy.data.objects.new(output_name, result_mesh)
    bsp_obj.location = (0.0, 0.0, 0.0)
    _ensure_collection("BSP").objects.link(bsp_obj)
    bpy.context.view_layer.objects.active = bsp_obj

    # ── 9b. Post-write coplanar verification (read-back loop via evaluator) ─
    # Load the mesh via the depsgraph evaluator (exactly as validate_bsp does)
    # so that plane-key precision matches.  Repeat until stable (max 5 passes).
    for _rb_iter in range(5):
        bpy.context.view_layer.update()
        _depsgraph = bpy.context.evaluated_depsgraph_get()
        _eval_obj  = bsp_obj.evaluated_get(_depsgraph)
        _eval_mesh = _eval_obj.to_mesh()
        bm_check = bmesh.new()
        bm_check.from_mesh(_eval_mesh)
        _eval_obj.to_mesh_clear()
        bm_check.verts.ensure_lookup_table()
        bm_check.edges.ensure_lookup_table()
        bm_check.faces.ensure_lookup_table()
        # Do NOT call normal_update: normals come from the evaluated mesh's
        # stored float32 normals, identical to what validate_bsp will see.
        n_readback = _fix_coplanar_overlaps(bm_check, wall_mat_index=WALL_IDX,
                                            _skip_normal_update=True)
        bm_check.edges.ensure_lookup_table()
        n_rb_bnd = sum(1 for e in bm_check.edges if len(e.link_faces) < 2)
        rb_modified = n_readback > 0 or n_rb_bnd > 0

        if n_readback:
            print(f"[naranjos-level] Read-back[{_rb_iter}] coplanar fix: "
                  f"removed {n_readback} face(s)")
        if n_rb_bnd:
            print(f"[naranjos-level] Read-back[{_rb_iter}] boundary: "
                  f"{n_rb_bnd} edge(s)")

        if rb_modified:
            if n_rb_bnd:
                n_rb_portal = _fill_boundary_with_portal(bm_check)
                if n_rb_portal:
                    print(f"[naranjos-level] Read-back[{_rb_iter}] re-seal: "
                          f"{n_rb_portal} portal(s)")
                bm_check.faces.ensure_lookup_table()
                rb_ngons = [
                    f for f in bm_check.faces
                    if f.material_index == PORTAL_IDX and len(f.verts) > 3
                ]
                if rb_ngons:
                    bmesh.ops.triangulate(bm_check, faces=rb_ngons)
                bm_check.edges.ensure_lookup_table()
                remaining_bnd = sum(1 for e in bm_check.edges if len(e.link_faces) < 2)
                if remaining_bnd:
                    n_patched = _fill_open_boundary_paths(bm_check)
                    if n_patched:
                        print(f"[naranjos-level] Read-back[{_rb_iter}] "
                              f"patched {n_patched} open-path triangle(s)")
                        bm_check.normal_update()
                        _fix_coplanar_overlaps(bm_check, wall_mat_index=WALL_IDX)
                    bm_check.edges.ensure_lookup_table()
                    still_bnd = sum(1 for e in bm_check.edges if len(e.link_faces) < 2)
                    if still_bnd:
                        print(f"[naranjos-level] WARNING: {still_bnd} boundary "
                              f"edge(s) remain after read-back patching")
            bm_check.to_mesh(result_mesh)
            result_mesh.update()
            bm_check.free()
        else:
            print("[naranjos-level] Read-back: mesh verified clean ✓")
            bm_check.free()
            break  # stable — no more overlaps or boundary edges

    # ── 9c. Reclassify building faces into WALL / FLOOR / HALL / ROOF ────────
    # Done after the read-back loop so repair triangles are also classified.
    bpy.context.view_layer.update()
    _dg_f = bpy.context.evaluated_depsgraph_get()
    _ev_f  = bsp_obj.evaluated_get(_dg_f)
    _em_f  = _ev_f.to_mesh()
    bm_final = bmesh.new()
    bm_final.from_mesh(_em_f)
    _ev_f.to_mesh_clear()
    bm_final.faces.ensure_lookup_table()
    bm_final.normal_update()

    _bz = [v.co.z
           for f in bm_final.faces if f.material_index == WALL_IDX
           for v in f.verts]
    if _bz:
        _z_min, _z_max = min(_bz), max(_bz)
        _n_recl = 0
        for f in bm_final.faces:
            if f.material_index == WALL_IDX:
                new_mi = _classify_face_material(f, _z_min, _z_max)
                if new_mi != WALL_IDX:
                    f.material_index = new_mi
                    _n_recl += 1
        _counts = " | ".join(
            f"{lbl}={sum(1 for f in bm_final.faces if f.material_index == idx)}"
            for lbl, idx in [("wall", WALL_IDX), ("floor", FLOOR_IDX),
                              ("hall", HALL_IDX),  ("roof", ROOF_IDX)]
        )
        print(
            f"[naranjos-level] Material classification "
            f"(z=[{_z_min:.2f}, {_z_max:.2f}] BU): {_counts}"
        )

    # ── 9d. Per-material box-mapped UVs ────────────────────────────────────────
    _generate_box_uvs(bm_final, tile_by_mat={
        WALL_IDX:    WALL_TILE_BU,
        FLOOR_IDX:   FLOOR_TILE_BU,
        HALL_IDX:    HALL_TILE_BU,
        ROOF_IDX:    ROOF_TILE_BU,
        WALL_RO_IDX: WALL_TILE_BU,
    })

    bm_final.to_mesh(result_mesh)
    result_mesh.update()
    bm_final.free()
    print("[naranjos-level] Per-material UVs generated ✓")

    return bsp_obj


def validate_and_report(obj_name: str = BSP_WORLD_NAME) -> bool:
    """Run BSP validation on *obj_name* and print a summary.

    Returns ``True`` if all checks pass, ``False`` otherwise.

    Note: the *outward normals* check may report a false positive for
    ``bsp_world`` because the sky envelope's inward normals give a negative
    signed-volume contribution.  This is expected and does not prevent a
    successful Halo CE BSP compile.
    """
    bpy.context.view_layer.update()

    # ── Pre-validate coplanar cleanup (validate-exact) ────────────────────
    # Use validate_bsp's own _plane_key / _project_tri / _convex_clip so the
    # plane-key computation is guaranteed identical to what validate will use.
    from halo_maps.naranjos.validate_bsp import (
        _plane_key    as _vbsp_pk,
        _project_tri  as _vbsp_proj,
        _convex_clip  as _vbsp_clip,
        _tri_area_2d  as _vbsp_area,
        AREA_TOL      as _VBSP_AREA_TOL,
    )
    _HORIZ_Z = 0.9   # |n.z| > threshold → horizontal fill face

    def _pv_fix(bm_pv):
        """One-pass coplanar fix using validate_bsp's exact algorithm."""
        groups_pv: dict = {}
        for _f in bm_pv.faces:
            if len(_f.verts) == 3 and _f.material_index == WALL_IDX:
                groups_pv.setdefault(_vbsp_pk(_f), []).append(_f)

        to_del_pv: set = set()
        for _faces_pv in groups_pv.values():
            if len(_faces_pv) < 2:
                continue
            for _i, _fa in enumerate(_faces_pv):
                if _fa in to_del_pv:
                    continue
                _va_set = set(_fa.verts)
                _tri_a  = list(_vbsp_proj(_fa))
                _area_a = abs(_vbsp_area(_tri_a))
                if _area_a < _VBSP_AREA_TOL:
                    to_del_pv.add(_fa)
                    continue
                _na = _fa.normal.normalized()
                for _fb in _faces_pv[_i + 1:]:
                    if _fb in to_del_pv:
                        continue
                    # Skip anti-parallel pairs (back-to-back walls — one face
                    # per room side on the same partition plane).  These appear
                    # in the same plane group because _plane_key canonicalises
                    # the normal, but they are valid BSP geometry and their
                    # apparent 2-D overlap is intentional.
                    if _na.dot(_fb.normal.normalized()) < -0.5:
                        continue
                    if len(_va_set.intersection(_fb.verts)) >= 2:
                        continue
                    _inter = _vbsp_clip(_tri_a, list(_vbsp_proj(_fb)))
                    if len(_inter) < 3:
                        continue
                    if abs(_vbsp_area(_inter)) > _VBSP_AREA_TOL:
                        _area_b = abs(_vbsp_area(list(_vbsp_proj(_fb))))
                        if _area_a <= _area_b:
                            to_del_pv.add(_fa)
                            break
                        else:
                            to_del_pv.add(_fb)

        # Horizontal fills: bypass safety check; vertical: apply it.
        _horiz_del = {_f for _f in to_del_pv
                      if abs(_f.normal.normalized().z) > _HORIZ_Z}
        _vert_del  = to_del_pv - _horiz_del
        # Safety check on vertical faces only.
        from collections import defaultdict as _dd_pv
        _safe = set(_vert_del)
        for _ in range(len(_vert_del) + 1):
            _all_del = _safe | _horiz_del
            _deg: dict = _dd_pv(int)
            _eo: dict  = {}
            for _f in _safe:
                for _e in _f.edges:
                    _rem = sum(1 for _lf in _e.link_faces if _lf not in _all_del)
                    if _rem == 1:
                        _deg[_e.verts[0]] += 1
                        _deg[_e.verts[1]] += 1
                        _eo[_e] = _f
            _ov = [_v for _v, _d in _deg.items() if _d == 1]
            if not _ov:
                break
            _culp = None
            for _v in _ov:
                for _e, _f in _eo.items():
                    if _v in _e.verts and _f in _safe:
                        _culp = _f; break
                if _culp:
                    break
            if _culp:
                _safe.discard(_culp)
            else:
                break

        _all_delete = _safe | _horiz_del
        if _all_delete:
            bmesh.ops.delete(bm_pv, geom=list(_all_delete), context="FACES")
        return len(_all_delete)

    _obj = bpy.data.objects.get(obj_name)
    if _obj is not None and _obj.type == "MESH":
        for _pv_pass in range(5):
            _dg = bpy.context.evaluated_depsgraph_get()
            _ev = _obj.evaluated_get(_dg)
            _em = _ev.to_mesh()
            _bm = bmesh.new()
            _bm.from_mesh(_em)
            _ev.to_mesh_clear()
            _bm.verts.ensure_lookup_table()
            _bm.edges.ensure_lookup_table()
            _bm.faces.ensure_lookup_table()
            _n_fix = _pv_fix(_bm)
            _bm.edges.ensure_lookup_table()
            _n_bnd = sum(1 for e in _bm.edges if len(e.link_faces) < 2)
            if _n_fix or _n_bnd:
                if _n_bnd:
                    _fill_boundary_with_portal(_bm)
                    _bm.faces.ensure_lookup_table()
                    _new_ngons = [f for f in _bm.faces
                                  if f.material_index == PORTAL_IDX and len(f.verts) > 3]
                    if _new_ngons:
                        bmesh.ops.triangulate(_bm, faces=_new_ngons)
                print(f"[naranjos-level] Pre-validate fix[{_pv_pass}]: "
                      f"removed {_n_fix} overlap(s), boundary={_n_bnd}")
                _bm.to_mesh(_obj.data)
                _obj.data.update()
                _bm.free()
                bpy.context.view_layer.update()
            else:
                _bm.free()
                break  # clean — no changes needed

    print(f"\n[naranjos-level] ── Validating '{obj_name}' ──")
    ok = validate(obj_name)
    verdict = "✓ all checks passed" if ok else "✗ issues found — see above"
    print(f"[naranjos-level] {verdict}")
    return ok


def export_level(
    obj_name: str = BSP_WORLD_NAME,
    output_path: str | None = None,
    map_name: str = "naranjos",
    scale: float = 1.0,
) -> str:
    """Export *obj_name* to JMS v8200 format.

    Parameters
    ----------
    obj_name:
        Name of the BSP mesh object to export (default ``"bsp_world"``).
    output_path:
        Destination ``.jms`` file.  Defaults to ``<naranjos_dir>/naranjos.jms``.
    map_name:
        Embedded label in the JMS comment header.
    scale:
        Uniform scale applied to all vertex positions in the JMS output.
        Equivalent to S→<scale>→Enter in Blender Edit Mode.  Use ``27.0``
        to match the Halo CE world-unit convention (1 BU = 0.55 m).

    Returns
    -------
    Absolute path of the written ``.jms`` file.
    """
    if output_path is None:
        output_path = DEFAULT_JMS_PATH

    path = export_jms(obj_name, output_path, map_name=map_name, scale=scale)
    scale_note = f" (scale ×{scale})" if scale != 1.0 else ""
    print(f"[naranjos-level] JMS written to: {path}{scale_note}")
    return path


def assemble_and_export(
    bsp_source_name: str = BSP_SOURCE_NAME,
    output_name: str = BSP_WORLD_NAME,
    sky_height_bu: float = SKY_HEIGHT_BU,
    ground_margin_bu: float = GROUND_MARGIN_BU,
    export_path: str | None = None,
    jms_scale: float = 1.0,
) -> None:
    """Full pipeline: assemble the Naranjos level and export to JMS.

    This is the single entry-point for the complete level-creation workflow.
    Run it inside Blender after ``generate_naranjos_dsl()`` has been executed::

        import importlib
        import halo_maps.naranjos.level as lvl
        importlib.reload(lvl)
        lvl.assemble_and_export(jms_scale=27.0)

    Parameters
    ----------
    bsp_source_name:
        Source object from ``generate_naranjos_dsl()`` (default ``"bsp_merged"``).
    output_name:
        Name for the final assembled BSP object (default ``"bsp_world"``).
    sky_height_bu:
        Minimum height of the sky box above ground in Blender units.
    ground_margin_bu:
        Margin added around the campus footprint for the sky envelope walls.
    export_path:
        Path for the output ``.jms`` file.  ``None`` → ``<dir>/naranjos.jms``.
    jms_scale:
        Uniform scale applied to vertex positions in the JMS output.
        The mesh in Blender is NOT modified — scale is applied only during
        writing, equivalent to S→<scale>→Enter in Edit Mode.
        Use ``27.0`` for the Halo CE world-unit convention.
    """
    bsp = assemble_naranjos_level(
        bsp_source_name=bsp_source_name,
        output_name=output_name,
        sky_height_bu=sky_height_bu,
        ground_margin_bu=ground_margin_bu,
    )
    if bsp is None:
        return

    validate_and_report(output_name)
    export_level(obj_name=output_name, output_path=export_path, scale=jms_scale)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    assemble_and_export(jms_scale=27.0)
